### ISSUE TITLE
Installer fails

### ISSUE THREAD

**Issue by lesichkovm** [modoboa/modoboa-installer#100]
I had created some long passwords containing **(%)** and the installer failed with the following message:

> Installing modoboa
> Traceback (most recent call last):
>   File "./run.py", line 73, in <module>
>     main()
>   File "./run.py", line 63, in main
>     scripts.install("modoboa", config)
>   File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
>     getattr(script, appname.capitalize())(config).run()
>   File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 40, in __init__
>     super(Modoboa, self).__init__(config)
>   File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 36, in __init__
>     self.dbpasswd = self.config.get(self.appname, "dbpassword")
>   File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
>     return self._interpolate(section, option, value, d)
>   File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
>     self._interpolate_some(option, L, rawval, section, vars, 1)
>   File "/usr/lib/python2.7/ConfigParser.py", line 732, in _interpolate_some
>     "'%%' must be followed by '%%' or '(', found: %r" % (rest,))
> ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%)edF'
>

**Comment by tonioo** [comment]
Indeed, the % character has a special meaning. If you want % characters in your passwords, you need to escape them like this: %%.

**Comment by lesichkovm** [comment]
I thin it might be a good idea for the server to check everything before it starts to make any changes to the filesystem, and roll back all changes on exception.
In this case it did go through some of the steps, then failed. Any additional attempts to run the script just failed, had to delete the whole VPS server.

**Comment by one2next** [comment]
me too. I got error..
Is there any document installing manual?

**Comment by tonioo** [comment]
@one2next Are you talking about the mysql issue?

**Comment by kryskool** [comment]
@tonioo to use %, i think we can use [RawConfigParser](https://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser) safely

**Comment by tonioo** [comment]
@kryskool Some variables are used be the installer so we need interpolation...
