### ISSUE TITLE
mariadb/mysql support

### ISSUE THREAD

**Issue by mlzummo** [modoboa/modoboa-installer#105]
thoughts on difficulty of migrating to a mysql/mariadb backend instead of pgsql? individually would this be complex or as straightforward as changing the maps and python connection?

**Comment by tonioo** [comment]
You mean you have an existing platform running on pgsql and you want to migrate to mysql?

**Comment by tonioo** [comment]
@mlzummo ping

**Comment by mlzummo** [comment]
@tonioo i found the setting in the installer.cfg to change use mysql when installing

**Comment by tonioo** [comment]
Ok, so I close this issue.
