### ISSUE TITLE
add postwhite

### ISSUE THREAD

**Issue by mzummo** [modoboa/modoboa-installer#109]

**Comment by almereyda** [comment]
https://github.com/stevejenkins/postwhite

**Comment by euri10** [comment]
I'm testing it for a few days and I find it a great addition,

I was thinking on adding it to the modoboa installer, I see 2 ways of doing it, either by creating a new entry in the installer.cfg which seem overkill to me, either by adding a `postwhite = true` flag within the [postfix] entry, which seen more logical.

steps are simple,

- cd /usr/local/bin
- git clone https://github.com/stevejenkins/postwhite
- git clone https://github.com/jsarenik/spf-tools
- mv /usr/local/bin/postwhite/postwhite.conf /etc
- change [modoboa-installer/modoboa_installer/scripts/files/postfix/main.cf.tpl](https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/files/postfix/main.cf.tpl#L136-L137)
from:
```
postscreen_access_list =
       permit_mynetworks
```
to:
```
postscreen_access_list =
       permit_mynetworks, cidr:/etc/postfix/postscreen_spf_whitelist.cidr
```
- source /usr/local/bin/postwhite/postwhite

then stop waiting for hours for gmail mails :)
