### ISSUE TITLE
Webmail attachment size setting can't be changed

### ISSUE THREAD

**Issue by amarc** [modoboa/modoboa-installer#11]
Hello,

tried this on multiple browsers and multiple formats (ie. 10MB and 10485760) but whatever I do it still goes back to 2048 bytes which as default is unusable.

Any specific log(s) I should check for this ? 

Also, on that parameters page when I hit 'Save' there is no confirmation that something is done or being done. Maybe adding something like this is good idea.

**Comment by tonioo** [comment]
Hi,
I guess a required parameter is not defined in another tab. Check 'Radicale' one to see you've filled the URL. When everything is filled as expected, you should see a green top notification.

**Comment by amarc** [comment]
Hi and thanks for update.

I really don't see any connections between this and other settings. What does Radicale, Calendar or anything else have to do with Webmail attachment size setting ? What If I do not want to have Radicale or Calendar of anykind? 

For record I am talking about this setting http://i.imgur.com/TIipiFT.png

A.

**Comment by tonioo** [comment]
All parameters (in all tabs) are saved at the same time and so validation is done for all of them too; that's why you can't validate a tab if you have an error in another one...
If you don't want to use the radicale extension, just remove it from MODOBOA_APPS.

**Comment by amarc** [comment]
Thanks,

is this under settings.py on /srv/modoboa ? 

I removed that but still seeing Radicale as option


A.

**Comment by tonioo** [comment]
Yes, settings.py.
You also need to reload your WSGI instance (apache, gunicorn, uwsgi, etc.)

**Comment by amarc** [comment]
I did not reload uwsgi, now everything works OK.  I will have some other questions maybe but I will open separate issue(s)

Thank you.

A.
