### ISSUE TITLE
An internal error occured

### ISSUE THREAD

**Issue by Rowofo** [modoboa/modoboa-installer#113]
# Impacted versions

* Modoboa: 1.7.1
* Distribution: Debian
* Codename: Jessie
* Arch: 64 Bits
* Webserver: Nginx

# Steps to reproduce

Commands before running installer:
<code>sudo apt-get install postgresql-9.4</code>

Create postgres user
sudo su - postgres
psql
CREATE USER modoboa WITH PASSWORD
'JBN1GkltM5sroo7TbloZ0DdnC0Q1KDJHPnIJAcWOkZpgDej';
CREATE DATABASE modoboa OWNER modoboa;
CREATE DATABASE modoboa OWNER modoboa;
CREATE DATABASE spamassassin OWNER modoboa;

My installer.cfg
<blockquote>

[certificate]
generate = true
type = self-signed

[letsencrypt]
email = admin@example.com

[database]
engine = postgres
host = 127.0.0.1
install = true

[postgres]
user = postgres
password =

[mysql]
user = root
password = password
charset = utf8
collation = utf8_general_ci

[modoboa]
user = modoboa
home_dir = /srv/modoboa
venv_path = %(home_dir)s/env
instance_path = %(home_dir)s/instance
timezone = Etc/UTC
dbname = modoboa
dbuser = modoboa
dbpassword = JBN1GkltM5sroo7TbloZ0DdnC0Q1KDJHPnIJAcWOkZpgDej
extensions = modoboa-amavis modoboa-pdfcredentials modoboa-postfix-autoreply modoboa-sievefilters modoboa-stats modoboa-webmail modoboa-radicale modoboa-dmarc
devmode = false

[amavis]
enabled = true
user = amavis
max_servers = 1
dbname = amavis
dbuser = modoboa
dbpassword = JBN1GkltM5sroo7TbloZ0DdnC0Q1KDJHPnIJAcWOkZpgDej

[clamav]
enabled = true
user = clamav

[dovecot]
enabled = true
config_dir = /etc/dovecot
user = vmail
home_dir = /srv/vmail
mailboxes_owner = vmail
extra_protocols = pop3
postmaster_address = postmaster@mail.example.com

[nginx]
enabled = true
config_dir = /etc/nginx

[razor]
enabled = true
config_dir = /etc/razor

[postfix]
enabled = true
config_dir = /etc/postfix
message_size_limit = 11534336

[spamassassin]
enabled = true
config_dir = /etc/mail/spamassassin
dbname = spamassassin
dbuser = modoboa
dbpassword = JBN1GkltM5sroo7TbloZ0DdnC0Q1KDJHPnIJAcWOkZpgDej

[uwsgi]
enabled = true
config_dir = /etc/uwsgi
nb_processes = 4
</blockquote>

# Current behavior
After successful installation and server restart. I hit https://mail.example.com login with username:'admin' and password: 'password' I get:
<blockquote>
Sorry

An internal error occured.
</blockquote>
1 check nginx error log but nothing found. 
2 check modoboa database then see that tables was created.

I maybe doing something wrong. If not, what can possible be the problem?

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@Rowofo Have you tried to run the installer using the --debug option?

You can also activate debug traces by setting DEBUG to True inside /srv/modoboa/instance/instance/settings.py and by reloading uwsgi.

**Comment by almereyda** [comment]
I suggest to create new database credentials for this instance, if they have been reused during multiple deploys.

**Comment by tonioo** [comment]
@Rowofo ping

**Comment by Rowofo** [comment]
I have no luck on my old db, so I simply create a new db for mail and it worked!
