### ISSUE TITLE
automx installation fails

### ISSUE THREAD

**Issue by OCram85** [modoboa/modoboa-installer#115]
# Impacted versions

* Modoboa: 1.7.2
* Distribution: Centos
* Codename: Centos 7
* Arch: 64 Bits
* Webserver: Nginx

# Steps to reproduce
- fresh Centos 7 installation
- selinux + firewallmd disabled
- config customized
- running modobia-installer

# Current behavior
- automx installation fails with error `no such file or directory`

# Expected behavior
- should run without error
- `/src/automx/` content:
![grafik](https://cloud.githubusercontent.com/assets/13993700/24751111/a64333f8-1ac8-11e7-8d16-ec6dfcbcb802.png)

-

# Video/Screenshot link (optional)
![grafik](https://cloud.githubusercontent.com/assets/13993700/24750920/fd7ac984-1ac7-11e7-8f7f-bea79b0b469e.png)

**Comment by UntrustedRoot** [comment]
I made the following change to automx.py to correct the issue. This is a really hacked solution so you may need to adjust to your needs.

Add the following line at line 68,
`        utils.exec_cmd("mkdir /srv/automx/automx-master", sudo_user=self.user, cwd=self.home_dir)
`

The whole function should look like this:
```
    def _setup_venv(self):
        """Prepare a python virtualenv."""
        python.setup_virtualenv(self.venv_path, sudo_user=self.user)
        packages = [
            "future", "lxml", "ipaddress", "sqlalchemy", "python-memcached",
            "python-dateutil", "configparser"
        ]
        python.install_packages(packages, self.venv_path, sudo_user=self.user)
        target = "{}/master.zip".format(self.home_dir)
        if os.path.exists(target):
            os.unlink(target)
        utils.exec_cmd(
            "wget https://github.com/sys4/automx/archive/master.zip",
            sudo_user=self.user, cwd=self.home_dir)
        utils.exec_cmd("mkdir /srv/automx/automx-master", sudo_user=self.user, cwd=self.home_dir)
        self.repo_dir = "{}/automx-master".format(self.home_dir)
        if os.path.exists(self.repo_dir):
            shutil.rmtree(self.repo_dir)
        utils.exec_cmd(
            "unzip master.zip", sudo_user=self.user, cwd=self.home_dir)
        utils.exec_cmd(
            "{} setup.py install".format(
                python.get_path("python", self.venv_path)),
            cwd=self.repo_dir)
```

**Comment by tonioo** [comment]
@OCram85 Looks like the installer failed to download the automx source code from Github... Could you please try again using the --debug option (and without your modification) ?

**Comment by OCram85** [comment]
I will take some time tomorrow and post the results...

**Comment by OCram85** [comment]
So while reading the debug output - I solved it ^^

The Centos7 image doesn't include `wget` ^^ After installing wget it just works perfect! 

[<img src="https://img.memesuper.com/f291ccac95eec1942535475f65909a52_-i-should-laugh-or-facepalm-facepalm-meme_604-453.jpeg">]()

**Comment by ErickLopez76** [comment]
I have to remove user "automx" and gropu "automx" and execute instalation again, and work for me.

**Comment by gittuyn** [comment]
> 我必须删除用户“automx”和组“automx”并再次执行安装，然后为我工作。

Tried to delete the automx user and the automx directory under the related / SRC directory, and rerun run Py, it doesn't happen again. Salute
