### ISSUE TITLE
installer.cfg get overwritten each update of the installer/git pull

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#118]
# Impacted versions

* Modoboa: Any
* Distribution: Any
* Codename: Any
* Arch: Any
* Webserver: Any

# Steps to reproduce

1. Install your Modoboa with this installer, create your `installer.cfg` and wait for a few months for new versions.
2. Update your virtual environment as the `modoboa` user as described in https://github.com/modoboa/modoboa-installer/issues/39#issuecomment-235992040.
3. Pull a new version of this installer via `git`.

# Current behavior

Currently the exemplary template of the installer configuration file `installer.cfg` uses the same name as the file which is used for production environments. Additionally, `run.py` doesn't accept any argument to point it at another file.

```
email# git remote -v
origin	https://github.com/ecobytes/modoboa-installer.git (fetch)
origin	https://github.com/ecobytes/modoboa-installer.git (push)
upstream	https://github.com/modoboa/modoboa-installer (fetch)
upstream	https://github.com/modoboa/modoboa-installer (push)
email# git fetch upstream
remote: Counting objects: 171, done.
remote: Total 171 (delta 76), reused 76 (delta 76), pack-reused 95
Receiving objects: 100% (171/171), 22.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (126/126), completed with 30 local objects.
From https://github.com/modoboa/modoboa-installer
   5509178..d653779  master     -> upstream/master
email# git pull          
Already up-to-date.
email# git pull upstream master
From https://github.com/modoboa/modoboa-installer
 * branch            master     -> FETCH_HEAD
Updating a096a6f..d653779
error: Your local changes to the following files would be overwritten by merge:
	installer.cfg
Please, commit your changes or stash them before you can merge.
Aborting
email# cp installer.cfg installer.cfg.20170408
email# git checkout - installer.cfg
email# git pull upstream master
email# diff installer.cfg installer.cfg.20170408 
email# vim installer.cfg.20170408 
email# cp installer.cfg.20170408 installer.cfg
```

# Expected behavior

1. `run.py` checks for the existence of `installer.cfg` upon run.
  * If it doesn't exist, it creates one from `installer.cfg.tmpl` with strong secrets.
  * If it exists, it checks its schema for missing, updated or removed entries.
2. `run.py` can be invoked with separate configurations, like `./run.py -f ecobytes.cfg`
  * the domain parameter is then optional, as it can be provided from within the configuration file, too.

**Comment by tonioo** [comment]
Done (almost). Config. file check will be added later.

**Comment by almereyda** [comment]
Merci beaucoup!
