### ISSUE TITLE
Installer should enable all installed systemd services...

### ISSUE THREAD

**Issue by OCram85** [modoboa/modoboa-installer#119]
# Impacted versions

* Modoboa: X.X.x
* Distribution: Centos
* Codename: Centos 7
* Arch: 64 Bits
* Webserver: Nginx

# Steps to reproduce
* install modoboa with modoboa-installer
* restart the system

# Current behavior
* postgresql service is disabled
* uwsgi service is disabled
* dovecot service is disabled
* Try to access to the admin console:
  * Gateway error 502

# Expected behavior
* It would be nice if the installer enables the services itself. `systemctl enable XXX`
* I think this would be a consistent behavior for all services which are installed by modoboa-installer itself.

# Video/Screenshot link (optional)

**Comment by tenninjas** [comment]
I'm not sure automating this is the right way to go - generally it is good practice to review and understand installed services before enabling them. Depending on the distributions default behavior, people may or may not expect this. Perhaps it would be better to display a list of the new services and advise the user to enable them?

**Comment by OCram85** [comment]
This would be great!

**Comment by tonioo** [comment]
The purpose of the installer is to automate the installation... Requiring the user to manually enable services looks strange to me.

**Comment by OCram85** [comment]
Well, then the installer should enable all new services.
Again - It would be nice to get a overview of all services modoboa depends on at the end of the installation...

**Comment by tonioo** [comment]
All services should be enabled by default now and you already have a list a dependencies when you start the installer.

**Comment by OCram85** [comment]
Perfect. Thank you!
