### ISSUE TITLE
Is ckeditor removed  ?

### ISSUE THREAD

**Issue by amarc** [modoboa/modoboa-installer#12]
Hello,

i see from some years back conversation online that there was HTML CKeditor for modoboa Webmail. I can not find that option now anywhere. Is this removed or I can not see it.. ?

ty.

**Comment by tonioo** [comment]
No, CKeditor still works with Modoboa. The documentation is available here: http://modoboa-webmail.readthedocs.org/en/latest/setup.html#using-ckeditor.

BTW, your issues are not related to the installer so could you please create them into the modoboa-webmail repository instead ?
