### ISSUE TITLE
Amavis is not installed error

### ISSUE THREAD

**Issue by ununseptium** [modoboa/modoboa-installer#121]
# Impacted versions

* Modoboa: d653779
* Distribution: CentOS 7.3.1611
* Arch: 64 Bits

# Steps to reproduce
literally just

> git clone https://github.com/modoboa/modoboa-installer
> cd modoboa-installer
> sudo ./run.py <your domain>

# Current behavior
Fails during install

```
[...]
Installing amavis
Initializing database ... OK

Redirecting to /bin/systemctl start postgresql.service
CREATE ROLE
0
Amavis is not installed
```

After that, the installer quits.

**Comment by ununseptium** [comment]
Now I'm also getting the annoying message that the Database "amavis" already exists, after i try to launch the script again. It seems that there's no "drop if exists" / force mechanic and i cannot drop the database the script created either.

**Comment by tonioo** [comment]
@ununseptium Can you run the installer using the --debug option please? The message you see about database is just a warning and should not stop the installer.

**Comment by ununseptium** [comment]
That is actually already the output with --debug option.

**Comment by tonioo** [comment]
@ununseptium ok so could you provide a full trace please?

**Comment by ununseptium** [comment]
Well okay

The first error that occured was this one here: 

```
[root@localhost modoboa-installer]# sudo ./run.py do.mäne --debug
Welcome to Modoboa installer!
Your mail server will be installed with the following components:
modoboa automx amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) Y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Paket sudo-1.8.6p7-21.el7_3.x86_64 ist bereits in der neuesten Version installiert.
Overwrite the existing SSL certificate? (y/N) y
Generating new self-signed certificate
Generating a 4096 bit RSA private key
......................++
..............................++
writing new private key to '/etc/pki/tls/private/mail.do.mäne.key'
-----
Installing amavis
Initializing database ... OK

Redirecting to /bin/systemctl start postgresql.service
CREATE ROLE
0
Amavis is not installed
```

and after that one, i'm getting this one here but i cannot remove the database manually with the pgsql user (and no password) that i found inside the installer.cfg. In short: I tried to `psql -U postgres -c 'drop database amavis'` but the authentification for the user didn't work.

```
[root@localhost modoboa-installer]# sudo ./run.py do.mäne --debug
Welcome to Modoboa installer!
Your mail server will be installed with the following components:
modoboa automx amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) Y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Paket sudo-1.8.6p7-21.el7_3.x86_64 ist bereits in der neuesten Version installiert.
Overwrite the existing SSL certificate? (y/N) y
Generating new self-signed certificate
Generating a 4096 bit RSA private key
......................++
..............................++
writing new private key to '/etc/pki/tls/private/mail.do.mäne.key'
-----
Installing amavis
Paket perl-DBD-Pg-2.19.3-4.el7.x86_64 ist bereits in der neuesten Version installiert.
Paket postgresql-server-9.2.18-1.el7.x86_64 ist bereits in der neuesten Version installiert.
Paket postgresql-devel-9.2.18-1.el7.x86_64 ist bereits in der neuesten Version installiert.
Data directory is not empty!

Redirecting to /bin/systemctl start  postgresql.service
1
createdb: Erzeugen der Datenbank ist fehlgeschlagen: FEHLER:  Datenbank »amavis« existiert bereits
Amavis is not installed
```

**Comment by tonioo** [comment]
@ununseptium Have you tried with a domain containing ASCII characters only?

**Comment by ununseptium** [comment]
Oh yea, i hope i weren't confused by my example with the 'ä'. The domain name was literally just lowercase ascii letters. Nothing special. 

Are there any log files the installer creates or something else that would help debugging this issues?

**Comment by tonioo** [comment]
No, when you run with the --debug option, everything should be logged to the console. What's your testing environment? Have you tried a new installation "from scratch"?

**Comment by ununseptium** [comment]
I ran this in a freshly setup linux vm running cent os 7.3. We're using a corporate proxy so i have to put proxy settings to pretty much every application separately. (Besides from the ones that are actually using the environment vars) 

Everything i did was a `yum update` downloaded the modoboa installer and tried installing. I can try on a different machine with similar configuration as well to double check that this isn't just a lucky shot.

**Comment by ununseptium** [comment]
So i tried the Same thing this time with a freshly installed bare metal
maschine. Centos 7.3.1611 as well. Same result. So it either has something
to do with centos 7.3 or it fails due to some download / proxy issues.

Antoine Nguyen <notifications@github.com> schrieb am Di. 25. Apr. 2017 um
14:32:

**Comment by tonioo** [comment]
I've made tests with a vagrant image using CentOS 7.3 and it works as
expected... I guess you can't bypass this proxy?

**Comment by ununseptium** [comment]
No, unfortunately not. But is there stuff going to be downloaded during the setup process with other ways than yum? Maybe pip or ruby gems or stuff like this? I could try to set those proxy settings as well to debug this.

**Comment by tonioo** [comment]
yum, pip, wget and I think that's all.

**Comment by ununseptium** [comment]
So i found the issue and of course the reason was somewhere to put into the proxy category...
The error occured because of missing certificates of our proxy server (for ssl interception stuff hooray -.-) 
I temporarily disabled ssl verification in the yum.conf and the amavisd-new package could be installed (which appears to be the reason that the error was thrown in the first place). I have a bunch of other errors now but the root issue seem to be just the same. 

Oh and is there a uninstall script or something? So that i don't have to create a new VM everytime i want to try a new clean installation? Because right now the whole system got installed but with many many errors so that i think it pretty much won't work.

**Comment by tonioo** [comment]
No, there is no uninstall function for now...

**Comment by ununseptium** [comment]
One last question: Do you know of a possibility to globally disable ssl verification for python requests? All i can't find in the internet is only applicable to the code itself and i really don't want to fork your installer to get this working >.<

**Comment by tonioo** [comment]
Unfortunately no :-(

**Comment by ununseptium** [comment]
Alright, thanks anyway.
I'll close this since the initial issue is resolved.

**Comment by 54330** [comment]
I seem to have the same issue however im not sat behind a proxy i have open internet all good.  Im using 18.04 LTS in vmware and quickly found that rebuilding everytime is a massive waste of time, just use vmwares snapshot feature ;)
My issue = #211
