### ISSUE TITLE
[Feature Request] Use ansible?

### ISSUE THREAD

**Issue by traverseda** [modoboa/modoboa-installer#125]
You might find that using ansible in local mode is nicer (and more reliable) than re-implementing a bunch of ansible features in custom python scripts.

Of course using ansible to run a bunch of custom python scripts is very reasonable, and a pretty common thing to do.

Ansible scripts are also relatively easy to get working, can be expanded to cover multiple machines, and are probably a bit easier to debug, and a bit harder to screw up. See "we need less powerful languages".

**Comment by traverseda** [comment]
You can see a quick pass at this [here](https://github.com/OutsideContextSolutions/modoboa-installer).

You can use the `./deploy.sh` script to run the ansible script located at `ansible/root.yaml`. What is does should be *pretty* self explanatory, but right now all it does is install some linux packages and run the python installer, generating a new config file for it based on the variables in the `root.yaml` file.

**Comment by tonioo** [comment]
Ansible is fine for people who know how to use it and it is not the only available tool if we start such a discussion... The installer was created this way to avoid any new dependency.
Anyway, any contribution to make modoboa deployments easier or more attractive will always be appreciated ;)

**Comment by traverseda** [comment]
Well glad to here you're open to it. It would be nice to have that discussion *before* I put in a bunch of work, but I can convert some more of the installer over to ansible before any decisions are made.

**Comment by traverseda** [comment]
The main reason I'm working on this is because I would like to deploy an LDAP server alongside my install of modoboa, have modoboa manage that ldap server, and get some optional ldap-enabled services running, like rocketchat and seafile.

That's a lot easier if I can use common systems administration tools instead of a bunch of custom scripts that I don't really understand and that don't have a community behind them.

**Comment by tonioo** [comment]
Those simple scripts are managed by the modoboa community, which is enough.
For your information, Modoboa is not designed to manage an LDAP server, it just fetch authentication information when needed.

**Comment by traverseda** [comment]
I am aware of that, but it wouldn't be much of a stretch to have modoboa create ldap users, which starts it down the path towards being more generally usable groupware. Ansible is another block in that, since modoboa has fairly limited manpower available. With ansible it becomes a lot easier for sysadmins to add a "modoboa-rocketchat" plugin, or a "modoboa-someOtherAppThatSupportsLdap". 

While that's certainly not impossible right now, it's pretty impractical, expecting someone to understand a custom set of tools that are modoboa specific, and that do the same job as {ansible, chef, puppet, whatever} in order to add support for some other thing. To say nothing of the time it would take to cluster these things.

Of course it's entirely possible to manage both these custom scripts and an ansible deployment, but maintaining ansible scripts still takes *time*, and with limited manpower available I'd certainly like to see the focus on clean, readable, industry-standard, whatever-scripts.

Is the focus on not adding another dependency worth it? Especially when ansible can be installed via pip like all the other project dependencies?

**Comment by traverseda** [comment]
Also your choice in templating languages freaks me out ;-p

**Comment by tonioo** [comment]
I just wanted a quick result since I'm not familiar with ansible or similar tools. The templating language you're talking about is just the standard (so basic) one: https://docs.python.org/2/library/string.html#template-strings.
Once again, I didn't want to introduce a new dependency...

**Comment by traverseda** [comment]
Ahh, well that's fair enough. Github is reporting the templates as "smarty templates" which are PHP based, and I didn't investigate too deeply. You can understand my concern when I thought that you were using a PHP template language ;p

How are you feeling about introducing an dependency on ansible at this stage though?

You can see an example of an ansible file I wrote [here](https://github.com/traverseda/traverseda-dotfiles/blob/master/ansible/ansibleRoot.yaml). I use it to manage my dotfiles. I don't think it should be too hard for you to work with. Obviously I don't want to introduce any code that you don't feel comfortable maintaining. At this stage you're the only "core maintainer", and you need to be able to have responsibility over the project as a whole, and every component in it.

So my main question is, is this a feature that you'd feel comfortable including and maintaining? Take your time with that, I imagine you're busy and you'd want to spend some time getting comfortable with ansible, and gods knows when you'll have time for that. I'm not going to prioritize this feature until I have some assurances that the project is going to find it useful.

**Comment by tonioo** [comment]
@traverseda Sorry for the lack of reply, I've been pretty busy.

Honestly, I don't know what to think about this. Ansible looks like a great tool but I do not enough time to learn it right now and I use different tools to automate things. I'm not saying your idea is wrong, it's just I can't maintain everything alone. If you want to work on something, please do, I always appreciate contributions and it could be integrated to the repository as an alternative installation way (until we decide to keep only one).

**Comment by traverseda** [comment]
Had some free time and took a first crack at this for my own use. Right now all it does is SSL certificates, uwsgi, nginx, and the virtualenv.

https://github.com/OutsideContextSolutions/modoboa-installer

The pertinent files are `playbook.yaml` and the `roles/` directory.

Any ideas on what features I should prioritize next?

**Comment by kryskool** [comment]
Hi

Can we create a thirdparty folder, with ansible folder and maintained by the community ?

We can also include Puppet, Chef, Fabric ... 

Regards,

**Comment by drzraf** [comment]
clearly the way to go ^^

**Comment by thejhh** [comment]
This would be precisely what I'd need right now, too. 

I am going in the direction to use LDAP to authenticate users, since Modoboa REST API does not provide authentication method for users.

However if Modoboa doesn't support adding new users to LDAP, I guess it doesn't work how I intended to use it, or at least I cannot let customers use Modoboa frontend directly.

**Comment by thejhh** [comment]
I think for the moment I'll use Ansible and Modoboa REST API to automate changes from the LDAP to Modoboa and write my own frontend / REST API for customers to use.

**Comment by drzraf** [comment]
Closed... but still the way to go anyway.
