### ISSUE TITLE
[Feature Request] Configurable menu

### ISSUE THREAD

**Issue by traverseda** [modoboa/modoboa-installer#126]
It would be nice if we could change what appears in the modoboa top bar. Including, ideally, an iframe based view for embedding third-party web apps in the modoboa view.

Of course using iframes like that has some annoying problems, especially as far as bookmarking things go. That can mostly be worked around by using javascript to add the iframes url to the querystring of the pages urls.

**Comment by tonioo** [comment]
Wrong repository, it is not an installer feature. Please move this issue to the modoboa repository.

**Comment by traverseda** [comment]
Ahh, yes. I'm used to dealing with single repo projects and opening new issues is just habitual.

https://github.com/modoboa/modoboa/issues/1116
