### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa-installer#128]
_From @physiii on May 15, 2017 15:39_

Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily

Using Apache

# Steps to reproduce
git clone https://github.com/modoboa/modoboa-installer && cd modoboa* && sudo ./run.py domain.org:8080
...
Congratulations! You can enjoy Modoboa at https://mail.domain.org:8080 (admin:password)

# Current behavior
nothing at https://mail.domain.org:8080

# Expected behavior
Thinking admin site should load

Tried doing the manual install.  Ended up with a mess on my system and had to rebuild OS.

_Copied from original issue: modoboa/modoboa#1125_

**Comment by tonioo** [comment]
Why do you include a port number? Just use a simple domain name, the syntax you're trying to use is not supported by the installer.

**Comment by tonioo** [comment]
_From @physiii on May 16, 2017 15:23_

I tried without the port and get the same result. I am running apache2 on 8080 and a different webserver on 80 so that's why I tried the the 8080 port.

Please let me know what I should do from here. 

 > (env)physiii@s192-169-244-100:~/modoboa-installer$ sudo ./run.py mydomain.org
> Welcome to Modoboa installer!
> Your mail server will be installed with the following components:
> modoboa automx amavis clamav dovecot nginx razor postfix spamassassin uwsgi
> Do you confirm? (Y/n) Y
> The process can be long, feel free to take a coffee and come back later ;)
> Starting...
> Overwrite the existing SSL certificate? (y/N) y
> Generating new self-signed certificate
> Installing amavis
> Installing spamassassin
> Installing razor
> Installing clamav
> Installing modoboa
> User modoboa already exists, skipping creation but please make sure the /srv/modoboa directory exists.
> Target directory for Modoboa deployment (/srv/modoboa/instance) already exists. If you choose to continue, it will be removed.

> Do you confirm? (Y/n) Y
> Installing automx
> User automx already exists, skipping creation but please make sure the /srv/automx directory exists.
> Installing uwsgi
> Installing nginx
> Installing postfix
> Installing dovecot
> User vmail already exists, skipping creation but please make sure the /srv/vmail directory exists.
> Congratulations! You can enjoy Modoboa at https://mail.mydomain.org (admin:password)

**Comment by tonioo** [comment]
Please run the installer once again using the --debug option, you should
have more information.

**Comment by tonioo** [comment]
_From @physiii on May 16, 2017 16:38_

Okay looks like a problem with dovecot, "Address family not supported by protocol"

> ● dovecot.service - Dovecot IMAP/POP3 email server
>    Loaded: loaded (/lib/systemd/system/dovecot.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Tue 2017-05-16 09:06:52 MST; 2min 53s ago
>  Main PID: 5241 (code=exited, status=89)
> 
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: master: Error: service(managesieve-login): listen(::, 4190) failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: master: Error: socket() failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: master: Error: service(imap-login): listen(::, 143) failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: master: Error: socket() failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Error: service(managesieve-login): listen(::, 4190) failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Error: socket() failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Error: service(imap-login): listen(::, 143) failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Error: socket() failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Error: service(imap-login): listen(::, 993) failed: Address family not supported by protocol
> May 16 09:06:52 s192-169-244-100.secureserver.net dovecot[5241]: Fatal: Failed to start listeners
> Synchronizing state of dovecot.service with SysV init with /lib/systemd/systemd-sysv-install...

**Comment by tonioo** [comment]
_From @physiii on May 17, 2017 14:33_

Removed references to IPv6 in nginx and dovecot and now all services appear to be running. Still no access from https://mail.mydomain.org

Here is my nginx config:

```
$ cat /etc/nginx/sites-enabled/mail.mydomain.org.conf
# This file was automatically installed on 2017-05-17T07:01:19.308859
upstream modoboa {
    server unix:/run/uwsgi/app/modoboa_instance/socket fail_timeout=0;
}

server {
    listen 8080;
    server_name mail.mydomain.org;
    rewrite ^ https://$server_name$request_uri? permanent;
}

server {
    listen 443 ssl;
    server_name mail.mydomain.org;
    root /srv/modoboa/instance;

    ssl_certificate /etc/ssl/certs/mail.mydomain.org.cert;
    ssl_certificate_key /etc/ssl/private/mail.mydomain.org.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_verify_depth 3;
    ssl_dhparam /etc/nginx/dhparam.pem;

    client_max_body_size 10M;

    access_log /var/log/nginx/mail.mydomain.org-access.log;
    error_log /var/log/nginx/mail.mydomain.org-error.log;

    location /sitestatic/ {
        try_files $uri $uri/ =404;
    }

    location /media/ {
        try_files $uri $uri/ =404;
    }

    location / {
        include uwsgi_params;
        uwsgi_param UWSGI_SCRIPT instance.wsgi:application;
        uwsgi_pass modoboa;
    }
}

```

**Comment by tonioo** [comment]
@physiii What do you get when you try to access the web interface?

**Comment by tonioo** [comment]
_From @physiii on May 18, 2017 13:11_

I don't even get an error returned, just sits there connecting. I can access my test page from 8080 but if I got to https://mail.mydomain.org, it just sits there trying to connect, not even an error is returned. I have no problems running other ssl applications on my webserver.

**Comment by tonioo** [comment]
Firewall issue? Is your DNS correctly configured?

**Comment by tonioo** [comment]
_From @physiii on May 18, 2017 19:47_

I can run my applications on any port without issue.

**Comment by tonioo** [comment]
_From @almereyda on May 21, 2017 13:25_

Should this issue maybe moved to the modoboa-installer issue tracker?

**Comment by tonioo** [comment]
@almereyda yes

**Comment by tonioo** [comment]
@physii any news?

**Comment by physiii** [comment]
Still having the same errors, not sure where to go from here

**Comment by tonioo** [comment]
@physiii I just tried a fresh install on a ubuntu 15.10 and it works as expected... How did you configure your DNS?

**Comment by tonioo** [comment]
@physiii ping

**Comment by physiii** [comment]
Will check on this tomorrow and report back. Sorry, things are moving fast around here.

**Comment by physiii** [comment]
There was a mail.mydomain.org A record that I removed but I still get the same result - tried both mail.mydomain.org and mail.mydomain.org:8080, no response.

nginx is running and I can access ipaddress:8080 and mydomain.org:8080 but I can't access the https versions.

> $ cat mail.mydomain.org.conf
> upstream modoboa {
>     server unix:/run/uwsgi/app/modoboa_instance/socket fail_timeout=0;
> }
> 
> server {
>     listen 8080;
>     server_name mail.mydomain.org;
>     rewrite ^ https://$server_name$request_uri? permanent;
> }
> 
> server {
>     listen 443 ssl;
>     server_name mail.mydomain.org;
>     root /srv/modoboa/instance;
> 
>     ssl_certificate /etc/ssl/certs/mail.mydomain.org.cert;
>     ssl_certificate_key /etc/ssl/private/mail.mydomain.org.key;
>     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>     ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
>     ssl_prefer_server_ciphers on;
>     ssl_session_cache shared:SSL:10m;
>     ssl_verify_depth 3;
>     ssl_dhparam /etc/nginx/dhparam.pem;
> 
>     client_max_body_size 10M;
> 
>     access_log /var/log/nginx/mail.mydomain.org-access.log;
>     error_log /var/log/nginx/mail.mydomain.org-error.log;
> 
>     location /sitestatic/ {
>         try_files $uri $uri/ =404;
>     }
> 
>     location /media/ {
>         try_files $uri $uri/ =404;
>     }
> 
>     location / {
>         include uwsgi_params;
>         uwsgi_param UWSGI_SCRIPT instance.wsgi:application;
>         uwsgi_pass modoboa;
>     }
> }

Please advice from here.

**Comment by tonioo** [comment]
@physiii Looking at your configuration file, you should be able to reach Modoboa using:
* http://mail.mydomain.org:8080 (redirects to the https version)
* https://mail.mydomain.org
And you're sure your DNS record is well configured now?

**Comment by vkarpyuk** [comment]
Hi Guys,

I've installed the server and didn't have any problems. After the installation, the Nginx server fails with 
mail.timelogbook.com systemd[1]: Starting A high performance web server and a rever>
Jul 02 18:57:11 mail.xxxx.com nginx[709]: nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/mail.xxxx.com/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system .....

Please, help.

Thanks in advance!
~
