### ISSUE TITLE
switch to caddy web server for automatic lets encrypt certificate

### ISSUE THREAD

**Issue by nwgat** [modoboa/modoboa-installer#129]
currently we have to manually update, if using caddy its automaticly
caddy has a host of other useful features too

https://caddyserver.com/
https://github.com/mholt/caddy

**Comment by kunago** [comment]
There is no need to update manually. A simple cron does the job fully automatically.

**Comment by nwgat** [comment]
to what file?

**Comment by tonioo** [comment]
@nwgat The renewal of the certificate is a known issue (see #116) and I need time to look into it. About caddy, I don't want to introduce a dependency to a commercial product...

**Comment by nwgat** [comment]
caddy is open source and not a commercial product

**Comment by tonioo** [comment]
@nwgat Indeed, my bad. Anyway, I think it's better to fix the original issue...

**Comment by nwgat** [comment]
Good, might macgyver my way into caddy ;)

**Comment by warsix4** [comment]
Any suggestions for getting Caddy and Modoboa to work together? Currently it causes too many redirects.
