### ISSUE TITLE
OperationalError: fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by brylie** [modoboa/modoboa-installer#130]
# Impacted versions
Latest

* Distribution: Ubuntu
* Codename: 16.04
* Arch: 64 Bits
* Database: PostgreSQL 

# Steps to reproduce
1. Copy the installer.cfg.example to installer.cfg
2. Make change, such as enabling Letsencrypt
3. Run the installer

By default, the section for Postgres [contains no password](https://github.com/modoboa/modoboa-installer/blob/master/installer.cfg.default#L22):

```
postgres]
user = postgres
password =
```

Other sections of the configuration file seem to have variables in the password settings. E.g. [`password = $mysql_password `](https://github.com/modoboa/modoboa-installer/blob/master/installer.cfg.default#L26) or [`dbpassword = $sa_password`](https://github.com/modoboa/modoboa-installer/blob/master/installer.cfg.default#L98)

# Full trace using --debug option or current behaviour

Site cannot load, fails to connect to Postgres.

## Debug trace
```
OperationalError at /

fe_sendauth: no password supplied

Request Method: 	GET
Request URL: 	https://.../
Django Version: 	1.10.7
Exception Type: 	OperationalError
Exception Value: 	

fe_sendauth: no password supplied

Exception Location: 	/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/__init__.py in connect, line 130
Python Executable: 	/usr/bin/uwsgi-core
Python Version: 	2.7.12
Python Path: 	

['.',
 '',
 '/srv/modoboa/env/lib/python2.7',
 '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu',
 '/srv/modoboa/env/lib/python2.7/lib-tk',
 '/srv/modoboa/env/lib/python2.7/lib-old',
 '/srv/modoboa/env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/srv/modoboa/env/local/lib/python2.7/site-packages']

Server time: 	Wed, 14 Jun 2017 16:58:51 +0200
```

# Expected behavior
Installer would complete and site would work

# Video/Screenshot link (optional)

![screenshot_20170614_175407](https://user-images.githubusercontent.com/17307/27138989-7f38343c-512a-11e7-857d-24a8adfc9ae7.png)

**Comment by tonioo** [comment]
I don't think this issue is related to postgres password... Have you changed modoboa password? Do you see a password in the DATABASES variable contained in /srv/modoboa/instance/instance/settings.py?

**Comment by brylie** [comment]
The only steps I took were to copy the configuration file and enable LetsEncrypt.

**Comment by tonioo** [comment]
You copied the configuration manually? If so, we've found your problem. Actually, the installer will generate a configuration file the first time it is run.

**Comment by brylie** [comment]
Ah, OK. How do I enable LetsEncrypt in that case? I.e. how do I modify the auto-generated configuration file?

**Comment by tonioo** [comment]
Once it is generated, you can change the value to letsencrypt and run the installer one more time.

**Comment by brylie** [comment]
OK. That makes sense. It might be good to document that process, since it is not really 'intuitive'. E.g. why is there an example settings file that users are not supposed to use?

**Comment by brylie** [comment]
In any case, I will follow your advice. Thanks for your help! Also, Modoboa is really well designed :-)

**Comment by tonioo** [comment]
@brylie Thank you. Maybe I should rename the configuration file template (because it is not an example but a template...)

**Comment by brylie** [comment]
Ah, I understand now. Good idea.

I just opened a [feature request/discussion](https://github.com/modoboa/modoboa-installer/issues/133) about allowing the user to configure Modoboa during the installation process (e.g. enabling LetsEncrypt).

**Comment by tonioo** [comment]
@brylie I added a new option to generate the configuration file and stop. This is a simple answer to the issue you encountered, I'll work on a wizard later.
