### ISSUE TITLE
How to set up DKIM for domain name?

### ISSUE THREAD

**Issue by brylie** [modoboa/modoboa-installer#132]
How do users generate DKIM keys for Modoboa hosted mail domains?

# Impacted versions
Modoboa latest

# Steps to reproduce
1. add a new domain to Modoboa

# Expected behavior
It might be important for authenticity purposes to generate DKIM signatures for domain names.

https://www.emailonacid.com/blog/article/email-development/what_is_dkim_everything_you_need_to_know_about_digital_signatures

**Comment by tonioo** [comment]
Are you sure we're talking about an installer feature?

**Comment by brylie** [comment]
Ah, you're right. This issue should go in the main project.
