### ISSUE TITLE
Consider interactive setup 'wizard' (script) to walk users through settings options

### ISSUE THREAD

**Issue by brylie** [modoboa/modoboa-installer#133]
As an end user,
I may want to override the default Modoboa settings
so I can enable additional features or change how Modoboa is configured

It is not obvious how to change Modoboa configuration settings. The process, as explained in a different issue, is to:

1. run the Modoboa installer
2. modify the auto-generated configuration file
3. re-run the setup process

Rather than this, somewhat confusing and redundant, setup process, it might be useful to allow user interaction when generating the configuration file. I.e. the setup process would verify the settings at each step, allowing the user to simply take defaults or override them before running the installation.

# Impacted versions
Modoboa latest

# Example
While it's not Modoboa, the Gitflow utility has a similar setup process.

![peek 2017-06-16 10-53](https://user-images.githubusercontent.com/17307/27217326-157c93ea-5282-11e7-8edf-6c09dd332990.gif)

# Resources
There may be one or more packages to consider related to this feature request:

- [click](http://click.pocoo.org/) - Click is a Python package for creating beautiful command line interfaces in a composable way with as little code as necessary.

**Comment by tonioo** [comment]
Indeed, could be interesting. But it would also require command line options to support silent installations.

**Comment by brylie** [comment]
Ah, good point. E.g. --silent would take all default settings, like the current process does.
