### ISSUE TITLE
Naive datetime warnings

### ISSUE THREAD

**Issue by msssltd** [modoboa/modoboa-installer#134]
# Impacted versions
Latest

* Distribution: Debian 
* Codename: Jessie 
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
Vanilla Debian setup.  Run modoboa-installer + modoboa-radicale plugin

New to modoboa and django.  Apologies if this is the wrong section of the site.

Had a few issues after editing the defaults settings and running the installer, which I managed to resolve.   Modoboa is working but the following warning is being sent to the root mailbox every 2 minutes.
`
Subject: Cron <root@mail> $PYTHON $INSTANCE/manage.py generate_rights

/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1430:
RuntimeWarning: DateTimeField AccessRule.last_update received a naive datetime (2017-06-18
18:48:37) while time zone support is active.
  RuntimeWarning)
`

I have disabled the cron job as a workaround.  I would appreciate knowing how to resolve the issue or how to suppress the warning message.

**Comment by tonioo** [comment]
This issue is related to the radicale plugin and has already been solved (https://github.com/modoboa/modoboa-radicale/issues/13). I'll make a new release soon.
