### ISSUE TITLE
Amavis tip

### ISSUE THREAD

**Issue by msssltd** [modoboa/modoboa-installer#135]
Amavis issues warning for missing archive tools during start up

# Impacted versions
modoboa 1.7.4

* Distribution: Debian
* Codename: Jessie
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
systemctl status amavis

# Expected behavior
Additional dependencies to enable clam to extract archives and avoid the warnings from amavis 

# unarchivers required by amavis
apt-get install arc
apt-get install arj
apt-get install cabextract
apt-get install liblz4-tool
apt-get install lrzip
apt-get install lzop
apt-get install p7zip-full
apt-get install rpm2cpio
apt-get install unrar-free
apt-get install zoo

**Comment by acidsploit** [comment]
Decoder for .doc

apt-get install ripole
