### ISSUE TITLE
incompatibility between MariaDB 10.2.x MySQL-python/perl-DBD-MySQL

### ISSUE THREAD

**Issue by helgew** [modoboa/modoboa-installer#136]
This is just an FYI/documentation improvement suggestion about a [known issue](https://jira.mariadb.org/browse/MDEV-12950) with the latest stable MariaDB releases.

# Impacted versions

* Modoboa: any
* installer used: Yes
* Webserver: Nginx or Apache

# Steps to reproduce

run installer with mysql as DB engine and MariaDB 10.2.x installed

# Current behavior

MySQL-python installation fails

# Expected behavior

MySQL-python is installed

**Comment by tonioo** [comment]
@helgew Do you have any solution to fix this?

**Comment by helgew** [comment]
No. I simply downgraded MariaDB to 10.1.x.

**Comment by fyfe** [comment]
This is fixed in MySQL-python 1.3.11 

PyMySQL/mysqlclient-python#177
