### ISSUE TITLE
CentOS 7 install using apache requires modifications to wsgi.py 

### ISSUE THREAD

**Issue by helgew** [modoboa/modoboa-installer#137]
# Impacted versions

* Modoboa: 1.7.4
* installer used: Yes
* Webserver: Apache

# Steps to reproduce

run the installer and [configure apache](http://modoboa.readthedocs.io/en/latest/manual_installation/webserver.html)

# Current behavior

In order to get the django application to work, I had to insert the following code into `wsgi.py` (right after `import os`):
```python
import sys
sys.path.append("/srv/modoboa/instance")

VIRTUAL_ENV = '/srv/modoboa/env'
# activate virtualenv
_activate = "%s/%s/activate_this.py" % (
    VIRTUAL_ENV,
    'Scripts' if sys.platform == 'win32' else 'bin'
)
if sys.version_info >= (3, 0):
    exec(compile(open(_activate, 'rb').read(), _activate, 'exec'))
else:
    execfile(_activate, dict(__file__=_activate))
```

# Expected behavior

"things just work" (not serious... this is either an improvement request or a cry for help, since I have not worked with django/modoboa before)

**Comment by tonioo** [comment]
@helgew Thanks for sharing this but, actually, the installer does not setup Apache, only nginx.

**Comment by helgew** [comment]
Apache2 is [prominently documented](https://modoboa.readthedocs.io/en/latest/manual_installation/webserver.html) as a web server for mobodoa.

**Comment by tonioo** [comment]
Indeed, but only when you install modoboa manually. The installer only nginx at the moment.

**Comment by helgew** [comment]
Consider this a documentation issue then and a “nice to have” issue for the installer to support Apache as well.

**Comment by tonioo** [comment]
Ok, thanks for your feedback.

**Comment by JoshQuake** [comment]
Having the same issue on Debian 9. Was being served error 500 until I added this, now somewhat gives me the navigation and not much else with lots of errors in apache log.
[error.log](https://github.com/modoboa/modoboa-installer/files/1388985/error.log)

I installed on fresh server

**Comment by helgew** [comment]
@JoshQuake: those errors look unrelated to the django settings and possibly indicate file permission or Apache configuration issues. I find these errors always frustratingly uninformative but usually start with making sure the user httpd is running under is able to read the files in question.

**Comment by JoshQuake** [comment]
@helgew solved that issue, but I get python errors every now and again. Now seems to work for a minute or two and then I just get Internal Server Error at the top and then refresh and just get internal server error page.

I know this is probably off topic, but I've been struggling to get this figured out. I can't find logs that says what the issues are now.
