### ISSUE TITLE
Fails on stretch (9.0) and MariaDB(MySQL) as backend

### ISSUE THREAD

**Issue by SweBarre** [modoboa/modoboa-installer#142]
The installer wants to install libmysqlclient-dev but it has no installation candidate, it should be libmariadbclient-dev as debian changed from MySQL to MariaDB.
Also, the mysql-server is a meta package that installs mariadb, maybe it also needs to be changed to mariadb-server.

# Impacted versions
Current

* Distribution: Debian 
* Codename: Stretch
* Arch: 32 Bits / 64 Bits
* Database: MySQL

# Steps to reproduce

# Full trace using --debug option or current behaviour

# Expected behavior

# Video/Screenshot link (optional)

**Comment by juppees** [comment]
I had the same problem like you. Here is the way I installed Modoboa:
1. cd to /home or any other directory that is user-readable
2. clone git repository and cd into folder
3. run
`./run.py --stop-after-configfile-check <your domain>`
4. modify installer.cfg
4. edit modoboa_installer/database.py (watch out for the right indentation!)
    change line 127 to
(8 blanks)`"deb": ["mariadb-server", "libmariadbclient-dev"],`
   change line 130 to
(4 blanks)`service = "mariadb"` 
    You also might have to disable the mariadb "unix_socket" plugin for user root (not right now), see https://blog.v-gar.de/2017/02/en-solved-error-1698-28000-in-mysqlmariadb/ .  To get a bit more time (2 min) for this, I added after line 141
(8 blanks) `utils.exec_cmd("echo '\r\n\r\n #####################\r\n Modify mysql DB\r\n##########\r\n'; sleep 120;")`
5. run
`./run.py <your domain> --debug`
If you see the message from above open a second command shell and execute the commands mentioned in the hyperlink above - make sure the root password is the same like in your installer.cfg

This is a bit bulky and definitely not an elegant solution - but it's quick and dirty and works quite well :D
