### ISSUE TITLE
Enable SpamAssassin service and sa-update

### ISSUE THREAD

**Issue by pavinjosdev** [modoboa/modoboa-installer#143]
# Impacted versions

1.6.x to 1.8.1

* Distribution: Debian 8.8
* Codename: Jessie
* Arch: 64 Bits
* Database: MySQL

# Steps to reproduce

Install using modoboa-installer!

# Current behaviour

SA service is disabled and sa-update cron does not run

# Expected behavior

1. SA service should be enabled:

```
systemctl enable spamassassin
systemctl start spamassassin
```

2. sa-update should be enabled

In /etc/cron.daily/spamassassin --> Line 9: Change to `CRON=1`
In /etc/default/spamassassin --> Line 34: Change to `CRON=1`

**Comment by tonioo** [comment]
@pavinjosdev the spamassassin service is disabled because amavis calls SA directly (it does not use a socket to communicate)
Anyway, I'll enable the update cron job by default.
