### ISSUE TITLE
lost domain (and identities)

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa-installer#145]
Today I noticed a problem which probably has been present for a while. Under my main domain I have a subdomain with a few email accounts (2 or 3). The subdomain and identities seem to have all but disapeared from the web-UI. The mail still works though but I can add identitied and manage the domain through the web-UI. Login as domain administrator through the web-UI is possible but that is about it. Can't add identies (no premission). The main admin account only lists the main domain and no the othe (sub)domain. In fact I cant' seem to find the way I initially added it! Puzzled (and worried) describes my current state of mind. How to proceed/debug?

# Impacted versions
* v1.6.0 / v1.6.1
* Distribution: Debian v8
* Codename: Jessie 
* Arch:  64 Bits
* Database: PostgreSQL

**Comment by tonioo** [comment]
@JayBeRayBearGun Do you made any change recently?

**Comment by tonioo** [comment]
You can also try the following command:
```bash
> python manage.py modo repair --dry-run
```
If orphan records are found, rerun without the ``--dry-run`` option to fix the issues.

**Comment by tonioo** [comment]
@JayBeRayBearGun ping

**Comment by JayBeRayBearGun** [comment]
Hi there! (sorry was ill and away for a bit)
Did not make any changes (although I wanted to upgrade for ages)
I recently looked at the demo site and noticed I am missing the "Add domain" button.

Your suggested command results in:

root@ns1:/srv/modoboa/instance# python manage.py modo repair --dry-run
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

**Comment by tonioo** [comment]
@JayBeRayBearGun you forgot to load the virtualenv:
```bash
> sudo -u modoboa -i
> source env/bin/activate
> python manage.py modo repair --dry-run
```

**Comment by JayBeRayBearGun** [comment]
Hello Tonioo,
I did:

sudo -u modoboa -i
. env/bin/activate
cd /srv/modoboa/instance
python manage.py modo repair --dry-run

Checking for... Sometimes objects have no owner...
  Alias admin@holding.rhebergen.net has no owner
  Alias admin@rhebergen.net has no owner
  Alias admin@rhebergen.org has no owner

and some more like that.

**Comment by JayBeRayBearGun** [comment]
PS: I compared my installation to the demo version and noticed that the "Add" button in the webinterface for domain admin/setting is missing.

**Comment by tonioo** [comment]
@JayBeRayBearGun Have you run the command withouth the ``--dry-run`` option?

**Comment by JayBeRayBearGun** [comment]
i did indeed :)

**Comment by tonioo** [comment]
Is it better now?

**Comment by tonioo** [comment]
@JayBeRayBearGun ping

**Comment by JayBeRayBearGun** [comment]
Hi Tonioo, I was away for bit,.. and I need to correct myself. I did not ommit the dry-run initially I will try now and report back soon. JBR

**Comment by JayBeRayBearGun** [comment]
Okay tried it,.. seems to be okay now,... but apart from that,... I think I might have misunderstood some the UI to some extend and used the wrong account to login of admin. That explains the missing "Add" button :) I will do a littl more testing but I think it is okay now. Thanks for your attention!
