### ISSUE TITLE
ERROR: SQL: No module named psycopg2

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa-installer#147]
_From @acidsploit on July 24, 2017 17:21_

# Impacted versions
* Modoboa: 1.8.1
* Installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Test automx with automx-test script
See following error in /var/log/uwsgi/app/automx_instance.log:
ERROR: SQL: No module named psycopg2

# Current behavior
Generates: ERROR: SQL: No module named psycopg2

# Expected behavior
Generates no error

# Temp Fix
sudo su - automx 
source env/bin/activate
pip install psycopg2

# Fix
Fix installer?

_Copied from original issue: modoboa/modoboa#1193_

**Comment by acidsploit** [comment]
#148

I think I found the missing piece in the automx script...
