### ISSUE TITLE
ImportError: cannot import name parameters

### ISSUE THREAD

**Issue by Hackbard** [modoboa/modoboa-installer#149]
# Version 1.8.1 from installer

* Distribution: Debian 
* Codename: Jessie 
* Arch: 64 Bits
* Database:  MySQL

# Steps to reproduce

Installed like the installer tell me. Clone the repo and run it.
It runs without errors.

The Webinterface is not working and i see this error in the logs:

> Traceback (most recent call last):
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
>     response = self.get_response(request)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
>     response = self._middleware_chain(request)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 44, in inner
>     response = response_for_exception(request, exc)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
>     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
>     if resolver.urlconf_module is None:
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
>     return import_module(self.urlconf_name)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "./instance/urls.py", line 4, in <module>
>     url(r'', include('modoboa.urls')),
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
>     urlconf_module = import_module(urlconf_module)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/urls.py", line 45, in <module>
>     exts_pool.load_all()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/extensions.py", line 101, in load_all
>     self.load_extension(ext)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/extensions.py", line 82, in load_extension
>     __import__(name, locals(), globals(), [smart_str('modo_extension')])
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_amavis/modo_extension.py", line 16, in <module>
>     from modoboa.lib import parameters
> ImportError: cannot import name parameters

**Comment by tonioo** [comment]
@Hackbard Are you trying to upgrade an existing installation using the installer?

**Comment by Hackbard** [comment]
After i tried it the manuell way and get the same error i tried that.

**Comment by tonioo** [comment]
The installer is not designed to update an existing installation. If you tried manually, I think you forgot to upgrade plugins. What was your original version?

**Comment by Hackbard** [comment]
That was 1.5.X 
I installed it to 1.8.1 and take (hopefully) every update step from
http://modoboa.readthedocs.io/en/latest/upgrade.html

**Comment by tonioo** [comment]
Can you run the following command (load your virtualenv before):

> pip list | grep modoboa

**Comment by Hackbard** [comment]
modoboa (1.8.1)
modoboa-admin (1.1.2)
modoboa-amavis (1.0.6)
modoboa-contacts (0.3.0)
modoboa-dmarc (0.1.0)
modoboa-imap-migration (1.0.4)
modoboa-pdfcredentials (1.0.1)
modoboa-postfix-autoreply (1.1.5)
modoboa-radicale (1.0.4)
modoboa-sievefilters (1.0.4)
modoboa-stats (1.0.4)
modoboa-webmail (1.0.3)

**Comment by tonioo** [comment]
As I said, your extensions are not up-to-date. Please upgrade them to
the latest version. You can also remove the modoboa-admin package which
is obsolete.

**Comment by Hackbard** [comment]
Ok i think is looking good

modoboa (1.8.1)
modoboa-amavis (1.1.3)
modoboa-contacts (0.3.0)
modoboa-dmarc (1.0.0)
modoboa-imap-migration (1.1.1)
modoboa-pdfcredentials (1.1.0)
modoboa-postfix-autoreply (1.2.1)
modoboa-radicale (1.1.0)
modoboa-sievefilters (1.1.0)
modoboa-stats (1.1.0)
modoboa-webmail (1.1.5)

But if i'm going to the dashboard i see HTTP 500 Error.
This is the log

> mail.XXXX.de [pid: 30562|app: 1|req: 8/8] 95.91.224.59 () {52 vars in 1028 bytes} [Fri Jul 28 20:40:36 2017] GET /dashboard/ => generated 889 bytes in 598 msecs (HTTP/1.1 500) 4 headers in 160 bytes (1 switches on core 0)
> mail.XXXX.de [pid: 30562|app: 1|req: 9/9] 95.91.224.59 () {52 vars in 955 bytes} [Fri Jul 28 20:40:36 2017] GET /jsi18n/ => generated 5531 bytes in 75 msecs (HTTP/1.1 200) 4 headers in 132 bytes (1 switches on core 0)

**Comment by tonioo** [comment]
Please set DEBUG to True inside settings.py and reload uwsgi.

You should get a complete trace.

**Comment by Hackbard** [comment]
Hi @tonioo ,
sry i was on vacation.
So that is the Stack

> Request Method: | GET
> -- | --
> https://mail.XXXXXX.de/dashboard/
> 1.10.7
> ProgrammingError
> (1146, "Table 'modoboa.msgrcpt' doesn't exist")
> /srv/modoboa/env/local/lib/python2.7/site-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
> /usr/bin/uwsgi-core
> 2.7.9
> ['.',  '',  '/srv/modoboa/env/lib/python2.7',  '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu',  '/srv/modoboa/env/lib/python2.7/lib-tk',  '/srv/modoboa/env/lib/python2.7/lib-old',  '/srv/modoboa/env/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/srv/modoboa/env/local/lib/python2.7/site-packages']
> Mi, 2 Aug 2017 18:33:45 +0200

**Comment by tonioo** [comment]
Looks like amavis was not installed properly. Do you need it?

**Comment by tonioo** [comment]
@Hackbard ping

**Comment by Hackbard** [comment]
Hi,
i installed modoboa-amavis in 1.1.3 but it is still the same error msg.

**Comment by Hackbard** [comment]
Yes amavis would be great ;)
i have 20 Domains running.
Here are some warnings from the migration process 

```
python manage.py migrate
System check identified some issues:

WARNINGS:
modoboa_amavis.Msgrcpt.mail: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
modoboa_amavis.Quarantine.mail: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, core, lib, limits, modoboa_amavis, modoboa_contacts, modoboa_postfix_autoreply, relaydomains, reversion, sessions, sites
Running migrations:
  No migrations to apply.
```

**Comment by tonioo** [comment]
You can ignore those warnings.
Amavis provides a SQL schema for its database but you have to apply it manually. The installer takes care of it but in your case, I guess you need to do it yourself.
Look at this file for the schema: https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/files/amavis/amavis_mysql_2.10.1.sql.
The installer loads it like this: https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/database.py#L203.

**Comment by Hackbard** [comment]
So nice! i thank you ;) Where is the support button for some coins?

**Comment by tonioo** [comment]
@Hackbard You're welcome ;-)
You can support Modoboa by sponsoring an feature (currently there is only one proposed but I'll add some in the next weeks): https://modoboa.org/en/sponsor/.
