### ISSUE TITLE
Automx doesn't return username while using autoconfig and doesn't return autodiscover

### ISSUE THREAD

**Issue by PseudoAj** [modoboa/modoboa-installer#150]
# Impacted versions

* Distribution: Ubuntu
* Codename: Trusty
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce

## Using `automx-test`

Sourcing into `automx` environment using:

``` shell
sudo su automx
source ~/env/bin/activate
```

running `automx-test` using (I have valid user and domain, just replacing them here):

``` shell
automx-test user@domain.com
```

I got the following output:

```
Testing Autoconfig ...
Connecting to http://autoconfig.domain.com/mail/config-v1.1.xml?emailaddress=user@domain.com ...

  HTTP/1.1 200 OK
  Server: nginx/1.4.6 (Ubuntu)
  Date: Fri, 28 Jul 2017 02:35:44 GMT
  Content-Type: text/xml
  Content-Length: 1070
  Connection: keep-alive
<?xml version='1.0' encoding='utf-8'?>
<clientConfig version="1.1">
  <emailProvider id="domain.com">
    <domain>domain.com</domain>
    <displayName/>
    <displayShortName/>
    <outgoingServer type="smtp">
      <hostname>mail.domain.com</hostname>
      <port>587</port>
      <socketType>STARTTLS</socketType>
      <authentication>password-cleartext</authentication>
      <username>${email}</username>
      <useGlobalPreferredServer>yes</useGlobalPreferredServer>
    </outgoingServer>
    <incomingServer type="imap">
      <hostname>mail.domain.com</hostname>
      <port>143</port>
      <socketType>STARTTLS</socketType>
      <authentication>password-cleartext</authentication>
      <username>${email}</username>
    </incomingServer>
    <incomingServer type="pop3">
      <hostname>mail.domain.com</hostname>
      <port>110</port>
      <socketType>STARTTLS</socketType>
      <authentication>password-cleartext</authentication>
      <username>${email}</username>
    </incomingServer>
  </emailProvider>
</clientConfig>

Autodiscovery domain for Microsoft Outlook(tm) not found (autodiscover.domain.com)


Domain for iOS(tm) not found (domain.com)
```

# Full trace using --debug option or current behaviour

Mentioned trace above

# Expected behavior

Ideally, these two things should happen:

> 1. Instead of `${email}` user email should be returned in above `xml`
> 2. `Autodiscovery` for `outlook` should be returned and similarly for `ios`

**Comment by PseudoAj** [comment]
I could find solution to the first problem, upon checking the logs at `/var/log/uwsgi/app/automx.log` I noticed this:

> ERROR:root:SQL: No module named psycopg2

Clearly, I `psycopg2` wasn't installed in the `automx` `virtualenv`. I installed it using:

```shell
pip install psycopg2 
```

**Comment by tonioo** [comment]
@PseudoAj the psycopg2 issue has already been fixed. You should not need to use username instead of email inside the query because those fields contain the same values most of the time (the email field will be empty for accounts with no mailbox)... The autodiscovery is not enabled by default.
