### ISSUE TITLE
Pop3 Support

### ISSUE THREAD

**Issue by wajidfsd** [modoboa/modoboa-installer#152]
How to enable pop3 and pop3s support in modoboa.

# Impacted versions

* Distribution: Debian / Ubuntu / Centos
* Codename: Jessie / Trusty / Centos 7 / ...
* Arch: 32 Bits / 64 Bits
* Database: MySQL

Thanks in advance.

**Comment by tonioo** [comment]
Look at the config file. In the ``[dovecot]`` section, you can change the ``extra_protocols`` option.

**Comment by wajidfsd** [comment]
After changes in config file . i have to run installer again?

**Comment by tonioo** [comment]
yes.

**Comment by soneydiakotechology** [comment]
Add following entries dovecot configuration

Open :  vim /etc/dovecot/dovecot.conf

Add following entries 

!include_try /usr/share/dovecot/protocols.d/*.protocol
protocols = imap lmtp sieve pop3 pop3s

**Comment by slowaways** [comment]
> Add following entries in dovecot configuration
> 
> Open : vim /etc/dovecot/dovecot.conf
> 
> Add following entries
> 
> !include_try /usr/share/dovecot/protocols.d/*.protocol
> protocols = imap lmtp sieve pop3 pop3s

And next step? Restart the server with `sudo reboot`?
