### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by cozo** [modoboa/modoboa-installer#156]
Hello all, 
i need a little help please

It's a fresh install on debian 9

# Impacted versions

* Distribution: Debian 9
* Codename: Jessie / Trusty / Centos 7 / ...
* Arch: 64 Bits
* Database: PostgreSQL 

Just after a fresh install on a fresh server

Request Method: | GET
-- | --
https://mail.xxxxxxx.xxxxx/
1.10.8
OperationalError
fe_sendauth: no password supplied
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/__init__.py in connect, line 130
/usr/bin/uwsgi-core
2.7.13
['.',  '',  '/srv/modoboa/env/lib/python2.7',  '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu',  '/srv/modoboa/env/lib/python2.7/lib-tk',  '/srv/modoboa/env/lib/python2.7/lib-old',  '/srv/modoboa/env/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/srv/modoboa/env/local/lib/python2.7/site-packages',  '/srv/modoboa/env/lib/python2.7/site-packages']

I try to add a pgsql password but nothing run

thank you

**Comment by tonioo** [comment]
@cozo When did you set the postgres password?

**Comment by cozo** [comment]
Hello tonioo.
I try a fresh install, then set the password in installer config file after then relaunch installer without succes.

**Comment by cozo** [comment]
then i also put a new password after the install with pgsql command line

**Comment by cozo** [comment]
ok i do again the install process, with a pqsql password in tne installer.cfg and its OK now.
