### ISSUE TITLE
Missing pip, activate and LC_ALL setting on clean Ubuntu install

### ISSUE THREAD

**Issue by januszm** [modoboa/modoboa-installer#164]
# Impacted versions
latest

* Distribution: Ubuntu 16.04
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
run the installer with `--debug` option on a clean system installation

Installer stops/breaks when it tries to access /srv/modoboa/env/bin/activate and /srv/modoboa/env/bin/pip . It'll also complain about empty `LC_ALL`.

The solution is to set `LC_ALL=en_US.UTF-8` in `/etc/environment` for example. Then `apt-get install python-pip` manually and then create any virtualenv, eg. with `virtualenv venv --distribute`  and then copy `sudo cp ./venv/bin/activate /srv/modoboa/env/bin/activate` and adjust paths, or generate the link in another way.

We should either let the installer do this or add this information to README.

UPDATE: after all I still have issues, nginx/uwsgi don't see the Django installation inside virtualenv.

```
Traceback (most recent call last):
  File "./instance/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
Fri Oct 27 10:00:00 2017 - unable to load app 0 (mountpoint='mydomain.foo.io|') (callable not found or import error)
```

**Comment by tonioo** [comment]
@januszm What's the default locale of your system?

**Comment by januszm** [comment]
That's a default Ubuntu 16.04 in Amazon AWS. everything was set to en_US.UTF-8 except for LC_ALL which was not set at all.

I ended up using a different solution for the mail server. I couldn't resolve the error mentioned at the end of my first message here. For some reason `uwsgi` was unable to see the Django installation inside virtualenv
