### ISSUE TITLE
DCC seems to be enabled regardless of dcc_enabled var

### ISSUE THREAD

**Issue by evilham** [modoboa/modoboa-installer#167]
From checking the code, there is an "undocumented"* `dcc_enabled` variable in the spamassassin group.
This variable is a bit of a misnomer because (I am guessing here) it expects `''` for "Enable DCC" and `'#'` for "Disable DCC".

(*) By "undocumented" I mean it's not in `modoboa_installer/config_dict_template.py`.

And by checking the template `modoboa_installer/scripts/files/spamassassin/v310.pre.tpl` I see lines
https://github.com/modoboa/modoboa-installer/blob/81b32d21ad723a2706e7111378395b164ba91142/modoboa_installer/scripts/files/spamassassin/v310.pre.tpl#L24
and
https://github.com/modoboa/modoboa-installer/blob/81b32d21ad723a2706e7111378395b164ba91142/modoboa_installer/scripts/files/spamassassin/v310.pre.tpl#L81
with line 81 enabling DCC and overriding whatever the variable intended, which actually defaults to having DCC disabled.

I would recommend removing the last 4 lines.

**Comment by tonioo** [comment]
Indeed, those lines were useless. I think I started to work on a DCC integration but never finished it since there is no debian package available. Maybe I'll integrate it one day...
