### ISSUE TITLE
After install, what changes need to happen to my DNS to access the subdomain?

### ISSUE THREAD

**Issue by balupton** [modoboa/modoboa-installer#168]
I setup a Scaleway CentOS server, and got it going:

```
[root@modoboa modoboa-installer]# sudo ./run.py lupton.cc
Welcome to Modoboa installer!
Configuration file installer.cfg not found, creating new one.
Your mail server will be installed with the following components:
modoboa automx amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing modoboa
Installing automx
Installing uwsgi
Installing nginx
Installing postfix
Installing dovecot
Congratulations! You can enjoy Modoboa at https://mail.lupton.cc (admin:password)
```

However there is zero instructions on what DNS configuration I need to make to have https://mail.lupton.cc work. Nor is there any instructions on the website, docs website, or GitHub repos.

IP address of the Scaleway instance is `51.15.52.47` which produces a ngnix welcome page at http://51.15.52.47

**Comment by tonioo** [comment]
@balupton Indeed, the installer does not manage the DNS part. I guess a piece of documentation could be added at the end of the process... What do you think?

Basically, you just need an A record using the IP address you mentioned (eg. mail.balupton.cc -> 51.15.52.47) and then a MX record using mail.balupton.cc.
