### ISSUE TITLE
Sorry, An internal error occured.

### ISSUE THREAD

**Issue by torpix** [modoboa/modoboa-installer#169]
# Impacted versions

* Distribution: Centos7
* Arch: 64 Bits
* Database: MySQL

Sometimes ( not all the time ) navigating around it sometimes gives a 

Sorry 
An internal error occured.

Every time I try and log out it gives error:

Sorry
An internal error occured.

It is fresh install.

**Comment by tonioo** [comment]
@torpix Can you set DEBUG to True inside settings.py, reload uwsgi and try again please?
