### ISSUE TITLE
No CSS and static content displayed on Clean Centos 7 install

### ISSUE THREAD

**Issue by gjdijkstra** [modoboa/modoboa-installer#177]
# Impacted versions

* Codename: Centos 7 
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
bare install using install script via default instructions on fresh Centos 7 machine. After opening login page, page displays without CSS or static content displayed. Can Login with default password but display is not usable.

When opening static content like utl https://mail......nl/sitestatic/css/modoboa.png a 404 not found is returned.

What am i doing wrong?

GJ

**Comment by gjdijkstra** [comment]
Found it. selinux needs to be disabled on Centos 7. Perhaps a good idea to include in the installation documentation. ;)

thanks GJ

**Comment by wblondel** [comment]
Thanks a lot ! I had the same issue on Centos 7.5
