### ISSUE TITLE
Add modoboa 1.9.1 to installable versions

### ISSUE THREAD

**Issue by pruje** [modoboa/modoboa-installer#180]
# Impacted versions
1.9.1
* Distribution: Ubuntu
* Codename: Xenial
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
`run.py --version=1.9.1`

# Full trace using --debug option or current behaviour
invalid choice: '1.9.1'

# Expected behavior
Could you add the 1.9.1 version to the compatibility matrix? Thanks.

**Comment by pruje** [comment]
I can make a pull request if you want, I just need to know the versions of packages.

**Comment by tonioo** [comment]
This version is indeed missing from the list but even if we add it, the resulting installation will fail because postfix configuration files are now compatible with version 1.10+, they do not depend of the installed version...

**Comment by pruje** [comment]
I see. I no longer need this feature, so I close the issue.
