### ISSUE TITLE
main.cf contains template variables from main.cf.tpl that are not substituted

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#184]
# Steps to reproduce

- Install Modoboa with the installer.

# Current behaviour

After installing, the `main.cf` of postfix will contain useless configuration, since the variables `config_directory` or `data_directory` are not defined anywhere:

```
# grep _directory /etc/postfix/main.cf 
readme_directory = no
smtpd_tls_dh1024_param_file = ${config_directory}/dh2048.pem
smtpd_tls_session_cache_database = btree:$data_directory/smtpd_tls_session_cache
address_verify_map = proxy:btree:$data_directory/verify_cache
```

# Expected behavior

The configuration file `main.cf` is clean.

**Comment by tonioo** [comment]
Those variables are regular postfix variables, they do not need to be replaced. See http://www.postfix.org/postconf.5.html#config_directory.
