### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by norfair00** [modoboa/modoboa-installer#187]
```Sorry
An internal error has occurred```
https://mail.n00.li/

**Comment by norfair00** [comment]
This script corrupt my mysql config very nice script

**Comment by kryskool** [comment]
Hi @norfair00 

If you check the [script](https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/database.py#L130), it use only mysql client and not touch to the configuration.

Can you give us more detail ? (OS, verison, etc.)

**Comment by uzerus** [comment]
OS: ubuntu 16.04
SSL: CloudFlare
I should attach log somewhere, when i find it...

**Comment by tonioo** [comment]
@uzerus All passwords are configured through the installer.cfg file.
