### ISSUE TITLE
Database server statically defined as 'localhost'

### ISSUE THREAD

**Issue by tenninjas** [modoboa/modoboa-installer#19]
There are several places in the installer where 'localhost' is statically used (not pulled from a configuration variable). Not sure if this should be two distinct issues.

The first and most easily fixed is in _deploy_instance (modoboa_installer/scripts/modoboa.py:56) where I can see no reason it should not be using the existing config entry for database/host from installer.cfg.

The second is in DB user creation - assuming the users are connecting from localhost, which will not be the case if database/host is not localhost. This requires a new configuration variable for the 'source' host of the connection.

Example use case: Two low-end VPS, one running as dedicated DB server, one as dedicated mail server, with VPN or internal VLAN. DB server is at 10.0.0.3, mail server at 10.0.0.5. In this case, database/host must always use '10.0.0.3' and localhost will not work, also, the users must be created as coming from '10.0.0.5' (or possibly '10.0.0.0/255.255.255.192'...).

It also should be noted that these variables need to be used everywhere as 127.0.0.1 and localhost _may_ not work the same (e.g.: if using MySQL/MariaDB with skip_name_resolve).

I would be happy to work on a patch for this if there is interest.

**Comment by tonioo** [comment]
Hi,
a patch would be appreciated ;)
Please note that the installer was originally created to provide a quick answer for single server installations. Obviously, it can be enhanced to support multi-server setups but please be careful with actions such as package installations (which only works on localhost since the script uses on ly sudo)

**Comment by vingeni** [comment]
Hello, the fix you commited break the installation with posgres
Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 128, in post_run
    self.apply_settings()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 122, in apply_settings
    query, self.dbname, self.dbuser, self.dbpasswd)
  File "/root/modoboa-installer/modoboa_installer/database.py", line 48, in _exec_query
    self._setup_pgpass(dbname, dbuser, dbpassword)
  File "/root/modoboa-installer/modoboa_installer/database.py", line 84, in _setup_pgpass
    if self.dbname not in ["localhost", "127.0.0.1"]:
AttributeError: 'PostgreSQL' object has no attribute 'dbname'

**Comment by tonioo** [comment]
Ok, thanks for reporting. I'll fix it asap.
