### ISSUE TITLE
migration modoboa_postfix_autoreply.0002_auto_20150728_1236 fails on fresh install

### ISSUE THREAD

**Issue by tenninjas** [modoboa/modoboa-installer#20]
Related to https://github.com/modoboa/modoboa-postfix-autoreply/issues/19; a fresh install including the modoboa_postfix_autoreply extension will fail if the system is set to use InnoDB by default (as all new MySQL & MariaDB setups do). This can be resolved by limiting the field length to 253 instead of 300, as indicated on that ticket.

**Comment by tonioo** [comment]
Ok, so this issue is more related to the autoreply extension, right ?

**Comment by tenninjas** [comment]
Yes, definitely so. I just referenced it here for the benefit of those who may encounter this as blocking a brand new install using the installer.
