### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by mikysal78** [modoboa/modoboa-installer#203]
# Impacted versions
Modoboa | 1.10.3

* Distribution: Debian
* Codename: stretch (9.4)
* Arch: 64 Bits
* Database: PostgreSQL / MySQL

# Steps to reproduce
![schermata da 2018-04-09 22-29-13](https://user-images.githubusercontent.com/7560278/38521269-78bd737c-3c45-11e8-847c-ca8c4aea1c0c.png)

I have install from modobia-install.
now new version
![schermata da 2018-04-09 22-30-26](https://user-images.githubusercontent.com/7560278/38521339-a914e438-3c45-11e8-9bdd-9077237277eb.png)
 
for update?

Best regards,
Michele

**Comment by almereyda** [comment]
Hi @mikysal78 did you already have a look into #39 ?

**Comment by tonioo** [comment]
@mikysal78 You can find upgrade instructions by looking at the [official documentation](http://modoboa.readthedocs.io/en/latest/upgrade.html).
