### ISSUE TITLE
Amavis is not installed | CREATE ROLE 0

### ISSUE THREAD

**Issue by Hexiled** [modoboa/modoboa-installer#204]
# Impacted versions

* Distribution: Debian 7.11
* Codename: Jessie / Trusty / Centos 7 / ...
* Arch:  64 Bits
* Database: PostgreSQL / MySQL

# Steps to reproduce

git clone https://github.com/modoboa/modoboa-installer
cd modoboa-installer
apt-get install python-virtualenv python-pip
y
 ./run.py edited.net --debug
y

# Full trace using --debug option or current behaviour
`Starting...
Hit http://mirrors.digitalocean.com wheezy Release.gpg
Hit http://mirrors.digitalocean.com wheezy Release
Hit http://mirrors.digitalocean.com wheezy/main Sources
Hit http://mirrors.digitalocean.com wheezy/main amd64 Packages
Hit http://mirrors.digitalocean.com wheezy/main Translation-en
Get:1 http://security.debian.org wheezy/updates Release.gpg [1,601 B]
Get:2 http://security.debian.org wheezy/updates Release [52.3 kB]
Get:3 http://security.debian.org wheezy/updates/main Sources [344 kB]
Get:4 http://security.debian.org wheezy/updates/main amd64 Packages [618 kB]
Get:5 http://security.debian.org wheezy/updates/main Translation-en [339 kB]
Fetched 1,354 kB in 1s (758 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
sudo is already the newest version.
The following packages will be upgraded:
  wget
1 upgraded, 0 newly installed, 0 to remove and 53 not upgraded.
Need to get 770 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://security.debian.org/ wheezy/updates/main wget amd64 1.13.4-3+deb7u5 [770 kB]
Fetched 770 kB in 0s (4,516 kB/s)
Reading changelogs...
(Reading database ... 30397 files and directories currently installed.)
Preparing to replace wget 1.13.4-3+deb7u4 (using .../wget_1.13.4-3+deb7u5_amd64.deb) ...
Unpacking replacement wget ...
Processing triggers for man-db ...
Processing triggers for install-info ...
Setting up wget (1.13.4-3+deb7u5) ...
Generating new self-signed certificate
Generating a 4096 bit RSA private key
.........................................................++
................................................................................................................++
writing new private key to '/etc/ssl/private/mail.edited.net.key'
-----
Installing amavis
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package liblz4-tool
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  comerr-dev cpp cpp-4.7 dctrl-tools gcc gcc-4.7 krb5-multidev libc-dev-bin
  libc6-dev libgmp10 libgomp1 libgssapi-krb5-2 libgssrpc4 libitm1 libk5crypto3
  libkadm5clnt-mit8 libkadm5srv-mit8 libkdb5-6 libkrb5-3 libkrb5-dev
  libkrb5support0 libmpc2 libmpfr4 libpq-dev libpq5 libquadmath0 libssl-dev
  libssl-doc libssl1.0.0 linux-libc-dev manpages-dev postgresql-9.1
  postgresql-client-9.1 postgresql-client-common postgresql-common
  postgresql-server-dev-9.1 zlib1g-dev
Suggested packages:
  doc-base cpp-doc gcc-4.7-locales debtags gcc-multilib make autoconf
  automake1.9 libtool flex bison gdb gcc-doc gcc-4.7-multilib
  libmudflap0-4.7-dev gcc-4.7-doc libgcc1-dbg libgomp1-dbg libitm1-dbg
  libquadmath0-dbg libmudflap0-dbg libcloog-ppl0 libppl-c2 libppl7
  binutils-gold krb5-doc glibc-doc krb5-user postgresql-doc-9.1 oidentd
  ident-server locales-all
The following NEW packages will be installed:
  comerr-dev cpp cpp-4.7 dctrl-tools gcc gcc-4.7 krb5-multidev libc-dev-bin
  libc6-dev libgmp10 libgomp1 libgssrpc4 libitm1 libkadm5clnt-mit8
  libkadm5srv-mit8 libkdb5-6 libkrb5-dev libmpc2 libmpfr4 libpq-dev libpq5
  libquadmath0 libssl-dev libssl-doc linux-libc-dev manpages-dev postgresql
  postgresql-9.1 postgresql-client-9.1 postgresql-client-common
  postgresql-common postgresql-server-dev-9.1 postgresql-server-dev-all
  zlib1g-dev
The following packages will be upgraded:
  libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0 libssl1.0.0
5 upgraded, 34 newly installed, 0 to remove and 48 not upgraded.
Need to get 12.3 MB/31.7 MB of archives.
After this operation, 87.0 MB of additional disk space will be used.
Get:1 http://mirrors.digitalocean.com/debian/ wheezy/main dctrl-tools amd64 2.22.2 [167 kB]
Get:2 http://mirrors.digitalocean.com/debian/ wheezy/main comerr-dev amd64 2.1-1.42.5-1.1+deb7u1 [42.8 kB]
Get:3 http://mirrors.digitalocean.com/debian/ wheezy/main zlib1g-dev amd64 1:1.2.7.dfsg-13 [215 kB]
Get:4 http://security.debian.org/ wheezy/updates/main libssl1.0.0 amd64 1.0.1t-1+deb7u4 [1,279 kB]
Get:5 http://security.debian.org/ wheezy/updates/main libk5crypto3 amd64 1.10.1+dfsg-5+deb7u9 [114 kB]
Get:6 http://security.debian.org/ wheezy/updates/main libgssapi-krb5-2 amd64 1.10.1+dfsg-5+deb7u9 [150 kB]
Get:7 http://security.debian.org/ wheezy/updates/main libkrb5-3 amd64 1.10.1+dfsg-5+deb7u9 [394 kB]
Get:8 http://security.debian.org/ wheezy/updates/main libkrb5support0 amd64 1.10.1+dfsg-5+deb7u9 [50.7 kB]
Get:9 http://security.debian.org/ wheezy/updates/main libgssrpc4 amd64 1.10.1+dfsg-5+deb7u9 [88.5 kB]
Get:10 http://security.debian.org/ wheezy/updates/main libkadm5clnt-mit8 amd64 1.10.1+dfsg-5+deb7u9 [69.1 kB]
Get:11 http://security.debian.org/ wheezy/updates/main libkdb5-6 amd64 1.10.1+dfsg-5+deb7u9 [68.1 kB]
Get:12 http://security.debian.org/ wheezy/updates/main libkadm5srv-mit8 amd64 1.10.1+dfsg-5+deb7u9 [85.8 kB]
Get:13 http://security.debian.org/ wheezy/updates/main linux-libc-dev amd64 3.2.96-3 [879 kB]
Get:14 http://security.debian.org/ wheezy/updates/main krb5-multidev amd64 1.10.1+dfsg-5+deb7u9 [154 kB]
Get:15 http://security.debian.org/ wheezy/updates/main libpq5 amd64 9.1.24lts2-0+deb7u2 [141 kB]
Get:16 http://security.debian.org/ wheezy/updates/main libssl-dev amd64 1.0.1t-1+deb7u4 [1,786 kB]
Get:17 http://security.debian.org/ wheezy/updates/main libkrb5-dev amd64 1.10.1+dfsg-5+deb7u9 [40.7 kB]
Get:18 http://security.debian.org/ wheezy/updates/main libpq-dev amd64 9.1.24lts2-0+deb7u2 [197 kB]
Get:19 http://security.debian.org/ wheezy/updates/main libssl-doc all 1.0.1t-1+deb7u4 [1,225 kB]
Get:20 http://security.debian.org/ wheezy/updates/main postgresql-client-common all 134wheezy6 [63.6 kB]
Get:21 http://security.debian.org/ wheezy/updates/main postgresql-client-9.1 amd64 9.1.24lts2-0+deb7u2 [1,007 kB]
Get:22 http://security.debian.org/ wheezy/updates/main postgresql-common all 134wheezy6 [138 kB]
Get:23 http://security.debian.org/ wheezy/updates/main postgresql-9.1 amd64 9.1.24lts2-0+deb7u2 [3,292 kB]
Get:24 http://security.debian.org/ wheezy/updates/main postgresql all 9.1+134wheezy6 [42.8 kB]
Get:25 http://security.debian.org/ wheezy/updates/main postgresql-server-dev-9.1 amd64 9.1.24lts2-0+deb7u2 [559 kB]
Get:26 http://security.debian.org/ wheezy/updates/main postgresql-server-dev-all all 134wheezy6 [47.1 kB]
Fetched 12.3 MB in 1s (10.3 MB/s)
Reading changelogs...
Extracting templates from packages: 100%
Preconfiguring packages ...
(Reading database ... 30397 files and directories currently installed.)
Preparing to replace libssl1.0.0:amd64 1.0.1t-1+deb7u2 (using .../libssl1.0.0_1.0.1t-1+deb7u4_amd64.deb) ...
Unpacking replacement libssl1.0.0:amd64 ...
Preparing to replace libk5crypto3:amd64 1.10.1+dfsg-5+deb7u8 (using .../libk5crypto3_1.10.1+dfsg-5+deb7u9_amd64.deb) ...
Unpacking replacement libk5crypto3:amd64 ...
Preparing to replace libgssapi-krb5-2:amd64 1.10.1+dfsg-5+deb7u8 (using .../libgssapi-krb5-2_1.10.1+dfsg-5+deb7u9_amd64.deb) ...
Unpacking replacement libgssapi-krb5-2:amd64 ...
Preparing to replace libkrb5-3:amd64 1.10.1+dfsg-5+deb7u8 (using .../libkrb5-3_1.10.1+dfsg-5+deb7u9_amd64.deb) ...
Unpacking replacement libkrb5-3:amd64 ...
Preparing to replace libkrb5support0:amd64 1.10.1+dfsg-5+deb7u8 (using .../libkrb5support0_1.10.1+dfsg-5+deb7u9_amd64.deb) ...
Unpacking replacement libkrb5support0:amd64 ...
Selecting previously unselected package libgssrpc4:amd64.
Unpacking libgssrpc4:amd64 (from .../libgssrpc4_1.10.1+dfsg-5+deb7u9_amd64.deb) ...
Selecting previously unselected package libkadm5clnt-mit8:amd64.
Unpacking libkadm5clnt-mit8:amd64 (from .../libkadm5clnt-mit8_1.10.1+dfsg-5+deb7u9_amd64.deb) ...
Selecting previously unselected package libkdb5-6:amd64.
Unpacking libkdb5-6:amd64 (from .../libkdb5-6_1.10.1+dfsg-5+deb7u9_amd64.deb) ...
Selecting previously unselected package libkadm5srv-mit8:amd64.
Unpacking libkadm5srv-mit8:amd64 (from .../libkadm5srv-mit8_1.10.1+dfsg-5+deb7u9_amd64.deb) ...
Selecting previously unselected package libgmp10:amd64.
Unpacking libgmp10:amd64 (from .../libgmp10_2%3a5.0.5+dfsg-2_amd64.deb) ...
Selecting previously unselected package libgomp1:amd64.
Unpacking libgomp1:amd64 (from .../libgomp1_4.7.2-5_amd64.deb) ...
Selecting previously unselected package libitm1:amd64.
Unpacking libitm1:amd64 (from .../libitm1_4.7.2-5_amd64.deb) ...
Selecting previously unselected package libmpfr4:amd64.
Unpacking libmpfr4:amd64 (from .../libmpfr4_3.1.0-5_amd64.deb) ...
Selecting previously unselected package libquadmath0:amd64.
Unpacking libquadmath0:amd64 (from .../libquadmath0_4.7.2-5_amd64.deb) ...
Selecting previously unselected package libmpc2:amd64.
Unpacking libmpc2:amd64 (from .../libmpc2_0.9-4_amd64.deb) ...
Selecting previously unselected package cpp-4.7.
Unpacking cpp-4.7 (from .../cpp-4.7_4.7.2-5_amd64.deb) ...
Selecting previously unselected package cpp.
Unpacking cpp (from .../cpp_4%3a4.7.2-1_amd64.deb) ...
Selecting previously unselected package dctrl-tools.
Unpacking dctrl-tools (from .../dctrl-tools_2.22.2_amd64.deb) ...
Selecting previously unselected package gcc-4.7.
Unpacking gcc-4.7 (from .../gcc-4.7_4.7.2-5_amd64.deb) ...
Selecting previously unselected package gcc.
Unpacking gcc (from .../gcc_4%3a4.7.2-1_amd64.deb) ...
Selecting previously unselected package libc-dev-bin.
Unpacking libc-dev-bin (from .../libc-dev-bin_2.13-38+deb7u12_amd64.deb) ...
Selecting previously unselected package linux-libc-dev:amd64.
Unpacking linux-libc-dev:amd64 (from .../linux-libc-dev_3.2.96-3_amd64.deb) ...
Selecting previously unselected package libc6-dev:amd64.
Unpacking libc6-dev:amd64 (from .../libc6-dev_2.13-38+deb7u12_amd64.deb) ...
Selecting previously unselected package comerr-dev.
Unpacking comerr-dev (from .../comerr-dev_2.1-1.42.5-1.1+deb7u1_amd64.deb) ...
Selecting previously unselected package krb5-multidev.
Unpacking krb5-multidev (from .../krb5-multidev_1.10.1+dfsg-5+deb7u9_amd64.deb) ...
Selecting previously unselected package libpq5.
Unpacking libpq5 (from .../libpq5_9.1.24lts2-0+deb7u2_amd64.deb) ...
Selecting previously unselected package zlib1g-dev:amd64.
Unpacking zlib1g-dev:amd64 (from .../zlib1g-dev_1%3a1.2.7.dfsg-13_amd64.deb) ...
Selecting previously unselected package libssl-dev.
Unpacking libssl-dev (from .../libssl-dev_1.0.1t-1+deb7u4_amd64.deb) ...
Selecting previously unselected package libkrb5-dev.
Unpacking libkrb5-dev (from .../libkrb5-dev_1.10.1+dfsg-5+deb7u9_amd64.deb) ...
Selecting previously unselected package libpq-dev.
Unpacking libpq-dev (from .../libpq-dev_9.1.24lts2-0+deb7u2_amd64.deb) ...
Selecting previously unselected package libssl-doc.
Unpacking libssl-doc (from .../libssl-doc_1.0.1t-1+deb7u4_all.deb) ...
Selecting previously unselected package manpages-dev.
Unpacking manpages-dev (from .../manpages-dev_3.44-1_all.deb) ...
Selecting previously unselected package postgresql-client-common.
Unpacking postgresql-client-common (from .../postgresql-client-common_134wheezy6_all.deb) ...
Selecting previously unselected package postgresql-client-9.1.
Unpacking postgresql-client-9.1 (from .../postgresql-client-9.1_9.1.24lts2-0+deb7u2_amd64.deb) ...
Selecting previously unselected package postgresql-common.
Unpacking postgresql-common (from .../postgresql-common_134wheezy6_all.deb) ...
Adding 'diversion of /usr/bin/pg_config to /usr/bin/pg_config.libpq-dev by postgresql-common'
Selecting previously unselected package postgresql-9.1.
Unpacking postgresql-9.1 (from .../postgresql-9.1_9.1.24lts2-0+deb7u2_amd64.deb) ...
Selecting previously unselected package postgresql.
Unpacking postgresql (from .../postgresql_9.1+134wheezy6_all.deb) ...
Selecting previously unselected package postgresql-server-dev-9.1.
Unpacking postgresql-server-dev-9.1 (from .../postgresql-server-dev-9.1_9.1.24lts2-0+deb7u2_amd64.deb) ...
Selecting previously unselected package postgresql-server-dev-all.
Unpacking postgresql-server-dev-all (from .../postgresql-server-dev-all_134wheezy6_all.deb) ...
Processing triggers for man-db ...
Processing triggers for install-info ...
Setting up libssl1.0.0:amd64 (1.0.1t-1+deb7u4) ...
Setting up libkrb5support0:amd64 (1.10.1+dfsg-5+deb7u9) ...
Setting up libk5crypto3:amd64 (1.10.1+dfsg-5+deb7u9) ...
Setting up libkrb5-3:amd64 (1.10.1+dfsg-5+deb7u9) ...
Setting up libgssapi-krb5-2:amd64 (1.10.1+dfsg-5+deb7u9) ...
Setting up libgssrpc4:amd64 (1.10.1+dfsg-5+deb7u9) ...
Setting up libkadm5clnt-mit8:amd64 (1.10.1+dfsg-5+deb7u9) ...
Setting up libkdb5-6:amd64 (1.10.1+dfsg-5+deb7u9) ...
Setting up libkadm5srv-mit8:amd64 (1.10.1+dfsg-5+deb7u9) ...
Setting up libgmp10:amd64 (2:5.0.5+dfsg-2) ...
Setting up libgomp1:amd64 (4.7.2-5) ...
Setting up libitm1:amd64 (4.7.2-5) ...
Setting up libmpfr4:amd64 (3.1.0-5) ...
Setting up libquadmath0:amd64 (4.7.2-5) ...
Setting up libmpc2:amd64 (0.9-4) ...
Setting up cpp-4.7 (4.7.2-5) ...
Setting up cpp (4:4.7.2-1) ...
Setting up dctrl-tools (2.22.2) ...
Setting up gcc-4.7 (4.7.2-5) ...
Setting up gcc (4:4.7.2-1) ...
Setting up libc-dev-bin (2.13-38+deb7u12) ...
Setting up linux-libc-dev:amd64 (3.2.96-3) ...
Setting up libc6-dev:amd64 (2.13-38+deb7u12) ...
Setting up comerr-dev (2.1-1.42.5-1.1+deb7u1) ...
Setting up krb5-multidev (1.10.1+dfsg-5+deb7u9) ...
Setting up libpq5 (9.1.24lts2-0+deb7u2) ...
Setting up zlib1g-dev:amd64 (1:1.2.7.dfsg-13) ...
Setting up libssl-dev (1.0.1t-1+deb7u4) ...
Setting up libkrb5-dev (1.10.1+dfsg-5+deb7u9) ...
Setting up libpq-dev (9.1.24lts2-0+deb7u2) ...
Setting up libssl-doc (1.0.1t-1+deb7u4) ...
Setting up manpages-dev (3.44-1) ...
Setting up postgresql-client-common (134wheezy6) ...
Setting up postgresql-client-9.1 (9.1.24lts2-0+deb7u2) ...
update-alternatives: using /usr/share/postgresql/9.1/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
Setting up postgresql-common (134wheezy6) ...
Adding user postgres to group ssl-cert
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Setting up postgresql-9.1 (9.1.24lts2-0+deb7u2) ...
Creating new cluster (configuration: /etc/postgresql/9.1/main, data: /var/lib/postgresql/9.1/main)...
Moving configuration file /var/lib/postgresql/9.1/main/postgresql.conf to /etc/postgresql/9.1/main...
Moving configuration file /var/lib/postgresql/9.1/main/pg_hba.conf to /etc/postgresql/9.1/main...
Moving configuration file /var/lib/postgresql/9.1/main/pg_ident.conf to /etc/postgresql/9.1/main...
Configuring postgresql.conf to use port 5432...
update-alternatives: using /usr/share/postgresql/9.1/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
[ ok ] Starting PostgreSQL 9.1 database server: main.
Setting up postgresql (9.1+134wheezy6) ...
Setting up postgresql-server-dev-9.1 (9.1.24lts2-0+deb7u2) ...
Setting up postgresql-server-dev-all (134wheezy6) ...
/bin/sh: 1: systemctl: not found
Running clusters: 9.1/main
[ ok ] Restarting PostgreSQL 9.1 database server: main.
CREATE ROLE
0
Amavis is not installed`
# Expected behavior
Installed Modoboa
# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@Hexiled If you look at the README, Debian 7 is not supported by the installer. Only versions > 8 are supported.
