### ISSUE TITLE
Postfix not accepting mail on port 25, and Dovecot not accepting connections from the internet

### ISSUE THREAD

**Issue by dmaroulidis** [modoboa/modoboa-installer#205]
# Impacted versions

* Distribution: Debian
* Codename: Stretch
* Arch: 64 Bits
* Database: MySQL

# Steps to reproduce
1. Run modoboa-installer on freshly installed VM
2. Check to see whether Dovecot is responding to external connections, by using your email client to send email using SMTP.
3. Try sending email to the domain setup in modoboa, with all MX, DKIM, SPF records setup, from another email account (outside of modoboa)
4. Run nmap on hostname and check to see whether ports 25 and 587 are open.
# Full trace using --debug option or current behaviour
Doesn't accept email, or allow users to connect through smtp to Dovecot. (Note that there aren't any firewalls blocking any ports.)
# Expected behavior
After the installer finishes and the DNS records are set (MX, DKIM), the server should accept mail for its users, from the internet, it should allow MUAs to connect to it to send mail, and forward sent emails destined for other mailservers.

**Comment by tonioo** [comment]
@dmaroulidis Have you checked that ports are opened on your server? (what does netstat says)

**Comment by dmaroulidis** [comment]
I have checked and they aren't. Also there's no firewall blocking the ports. I can run telnet on port 25 and I can connect fine.

**Comment by tonioo** [comment]
@dmaroulidis Can you provide more information? logs?
