### ISSUE TITLE
502 Bad Gateway Fresh Install

### ISSUE THREAD

**Issue by carbans** [modoboa/modoboa-installer#206]
# Impacted versions

* Distribution: Debian
* Codename: Stretch
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
./run.py --interactive domain.com

# Full trace using --debug option or current behaviour
`File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/urls.py", line 10, in <module>
    from .views import (
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/views/export.py", line 22, in <module>
    from backports import csv
ImportError: No module named backports`

# Expected behavior
After finnish install I can login in the admin panel.

**Comment by altergui** [comment]
As far as i understand, this will be solved when 1.10.5 is released,
until then (i bumped into the same problem as you), i'm doing this workaround https://github.com/modoboa/modoboa-installer/issues/197#issuecomment-385621392 to have a usable install
hope that helps in the meantime :)

**Comment by carbans** [comment]
Thanks for your help you!!
