### ISSUE TITLE
opendkim not properly configured on ubuntu 16.04

### ISSUE THREAD

**Issue by donaldsteele** [modoboa/modoboa-installer#207]
# Impacted versions
1.10.4
* Distribution: Debian / Ubuntu / Centos
Ubuntu
* Codename: Jessie / Trusty / Centos 7 / ...
Xenial Xerus
* Arch: 32 Bits / 64 Bits
64
* Database: PostgreSQL / MySQL
PostgreSQL 
# Steps to reproduce
Install modoboa 
set new domain up and enable dkim 
send email

# Full trace using --debug option or current behaviour

# Expected behavior
dkim signs outbound email 
# Video/Screenshot link (optional)

# Fix / Workaround
This seems to be caused by /etc/default/opendkim only containing the default of 
SOCKET="local:/var/run/opendkim/opendkim.sock"

postfix is configured to connect on port 12345

adding this line to the  /etc/default/opendkim fixes the issue when you restart opendkim 
SOCKET="inet:12345@127.0.0.1"

**Comment by FastFelix771** [comment]
Same on Debian 9!
SOCKET=local:$RUNDIR/opendkim.sock is configured by default.

No DKIM key gets generated on domain creation.

**Comment by oscarcarlsson** [comment]
I've seen this as well, on a fresh installation on Ubuntu 16.04. What I did to fix it:

* Add `SOCKET="inet:12345@127.0.0.1"` to the end of my `/etc/default/opendkim`
* Restart opendkim, `systemctl restart opendkim.service`
* Manually run the cronjob for creating the dkim keys, `/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo manage_dkim_keys`

I tinkered around a lot so more steps *might* be required, but I think the above are the only relevant steps.

**Comment by malgoe** [comment]
I'm on Centos 7. Installed with the modoboa installer. I have no `/etc/default/opendkim` file, but I did find `/etc/opendkim.conf` and it contains this line already:
`Socket                  inet:12345@localhost`
I still have the problem described in this issue.

**Comment by malgoe** [comment]
And now I realise this issue is about the key not being generated at all. *facepalm* sorry about that :/

**Comment by tonioo** [comment]
@malgoe Can you check that opendkim is running?

**Comment by malgoe** [comment]
It wasn't running. I restarted it and it started fine, but now I couldn't send any e-mail. However `service opendkim status -l` gives me this:
 `key data is not secure: /var/lib/dkim/mydomain.tld.pem can be read or written by other users
A49A9210E56D: error loading key '1'`

What chmod would be correct for the key?

**Comment by malgoe** [comment]
There we go! A chmod 600 for the key did it. I guess that'd be a separate issue for the installer. Sorry for spamming this issue.

**Comment by jichu4n** [comment]
Hmm, commit ab1c825 did not fix this issue for me on a fresh install on Ubuntu 16.04.

Following a clean Modoboa install, the file `/etc/default/opendkim` looked like the following for me:

```bash
# Command-line options specified here will override the contents of
# /etc/opendkim.conf. See opendkim(8) for a complete list of options.
#DAEMON_OPTS=""
#
# Uncomment to specify an alternate socket
# Note that setting this will override any Socket value in opendkim.conf
# default:
SOCKET="local:/var/run/opendkim/opendkim.sock"
# listen on all interfaces on port 54321:
#SOCKET="inet:54321"
# listen on loopback on port 12345:
#SOCKET="inet:12345@localhost"
# listen on 192.0.2.1 on port 12345:
#SOCKET="inet:12345@192.0.2.1"
```

Note that neither of the two substitutions in ab1c825 had any effect:
* The first substitution `/^SOCKET=local:\$RUNDIR\/opendkim\.sock/` failed because a) the originally *un*commented line does not include `$RUNDIR` - it includes an absolute path, and b) it includes double quotes around the value.
* The second substitution `/^#SOCKET=inet:12345\@localhost$/` failed because the value includes double quotes.

Instead of hard-coding the value of two lines, I wonder if the following would be a better approach:

* Comment out any *un*commented lines beginning with `SOCKET=`:
```python
pattern = 's/^(SOCKET=.*)/#\1/'
utils.exec_cmd("perl -pi -e '{}' /etc/default/opendkim".format(pattern))
```
* Append the line we actually want:
```python
socket_var = 'SOCKET="inet:12345@localhost"'
utils.exec_cmd("echo -e '\n{}' >> /etc/default/opendkim".format(socket_var))
```
