### ISSUE TITLE
cron errors on fresh install

### ISSUE THREAD

**Issue by sethkush** [modoboa/modoboa-installer#213]
# Impacted versions

* Distribution: Debian
* Codename: Stretch
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
Run through install using letsencrypt

# Full trace using --debug option or current behaviour

Here's cron's log output from /var/log/syslog:
`May 25 12:21:01 mail cron[379]: (*system*letsencrypt) ERROR (Missing newline before EOF, this crontab file will be ignored)
May 25 12:29:01 mail cron[379]: Error: bad username; while reading /etc/cron.d/modoboa
May 25 12:29:01 mail cron[379]: (*system*modoboa) ERROR (Syntax error, this crontab file will be ignored)`

# Expected behavior
It should run the cron jobs. I was able to fix the letsencrypt one by adding a newline. I'm still working figuring out the modoboa one.

**Comment by sethkush** [comment]
/etc/cron.d/modoboa was fixed by running `touch /etc/cron.d/modoboa`. I don't know why that worked.

**Comment by tonioo** [comment]
I think this issue has been already fixed.
