### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Mladenovic92** [modoboa/modoboa-installer#22]
So, when i try to "**./run.py mail.serv.er**" i get:

> Traceback (most recent call last):
>   File "./run.py", line 64, in <module>
>     main()
>   File "./run.py", line 54, in main
>     scripts.install("modoboa", config)
>   File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
>     getattr(script, appname.capitalize())(config).run()
>   File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
>     self.post_run()
>   File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 114, in post_run
>     self.apply_settings()
>   File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 92, in apply_settings
>     utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
>   File "/root/modoboa-installer/modoboa_installer/utils.py", line 97, in mkdir
>     os.mkdir(path, mode)
> OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'
> 

When i run "**./run.py --debug mail.serv.er**", i get:

> Traceback (most recent call last):
>   File "/srv/modoboa/env/bin/modoboa-admin.py", line 7, in <module>
>     handle_command_line()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 95, in handle_command_line
>     commands[args.command](commands, verbose=args.verbose).run(remaining)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 36, in run
>     self.handle(args)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/deploy.py", line 178, in handle
>     'startproject', parsed_args.name, verbosity=False
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
>     return command.execute(*args, **defaults)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
>     output = self.handle(*args, **options)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/commands/startproject.py", line 33, in handle
>     super(Command, self).handle('project', project_name, target, **options)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/templates.py", line 80, in handle
>     raise CommandError(message)
> django.core.management.base.CommandError: '/srv/modoboa/instance' already exists
> Traceback (most recent call last):
>   File "./run.py", line 64, in <module>
>     main()
>   File "./run.py", line 54, in main
>     scripts.install("modoboa", config)
>   File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
>     getattr(script, appname.capitalize())(config).run()
>   File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
>     self.post_run()
>   File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 114, in post_run
>     self.apply_settings()
>   File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 92, in apply_settings
>     utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
>   File "/root/modoboa-installer/modoboa_installer/utils.py", line 97, in mkdir
>     os.mkdir(path, mode)
> OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'
> 

Folder tree:
![ffktm](https://cloud.githubusercontent.com/assets/6660598/13502169/1ffc8134-e16a-11e5-93eb-a084bec9f6e9.jpg)

**Comment by tonioo** [comment]
Can you try to remove the /srv/modoboa/instance folder and run the installer with --debug once again please ?

**Comment by Mladenovic92** [comment]
So i installed new server, tried to install again and get same error like in my first post.
After deleting /instance folder, this is what i get:

> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
>     django.setup()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
>     app_config.ready()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 68, in ready
>     load_core_settings()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 56, in load_core_settings
>     parameters.register(GeneralParametersForm, ugettext_lazy("General"))
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 192, in register
>     form = formclass()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/app_settings.py", line 261, in __init__
>     super(GeneralParametersForm, self).__init__(*args, **kwargs)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 62, in __init__
>     self._load_initial_values()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 96, in _load_initial_values
>     if not db_utils.db_table_exists("lib_parameter"):
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/db_utils.py", line 12, in db_table_exists
>     return table in connection.introspection.table_names()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
>     with self.connection.cursor() as cursor:
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 164, in cursor
>     cursor = self.make_cursor(self._cursor())
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
>     self.ensure_connection()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
>     self.connect()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
>     self.connect()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, async=async)
> django.db.utils.OperationalError: could not connect to server: Connection refused
> 	Is the server running on host "127.0.0.1" and accepting
> 	TCP/IP connections on port 5432?
> 
> 
> python manage.py migrate --noinput failed, check your configuration
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
>     django.setup()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
>     app_config.ready()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 68, in ready
>     load_core_settings()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 56, in load_core_settings
>     parameters.register(GeneralParametersForm, ugettext_lazy("General"))
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 192, in register
>     form = formclass()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/app_settings.py", line 261, in __init__
>     super(GeneralParametersForm, self).__init__(*args, **kwargs)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 62, in __init__
>     self._load_initial_values()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 96, in _load_initial_values
>     if not db_utils.db_table_exists("lib_parameter"):
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/db_utils.py", line 12, in db_table_exists
>     return table in connection.introspection.table_names()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
>     with self.connection.cursor() as cursor:
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 164, in cursor
>     cursor = self.make_cursor(self._cursor())
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
>     self.ensure_connection()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
>     self.connect()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
>     self.connect()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, async=async)
> django.db.utils.OperationalError: could not connect to server: Connection refused
> 	Is the server running on host "127.0.0.1" and accepting
> 	TCP/IP connections on port 5432?
> 
> 
> python manage.py load_initial_data  failed, check your configuration
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
>     django.setup()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
>     app_config.ready()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 68, in ready
>     load_core_settings()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 56, in load_core_settings
>     parameters.register(GeneralParametersForm, ugettext_lazy("General"))
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 192, in register
>     form = formclass()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/app_settings.py", line 261, in __init__
>     super(GeneralParametersForm, self).__init__(*args, **kwargs)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 62, in __init__
>     self._load_initial_values()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 96, in _load_initial_values
>     if not db_utils.db_table_exists("lib_parameter"):
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/db_utils.py", line 12, in db_table_exists
>     return table in connection.introspection.table_names()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
>     with self.connection.cursor() as cursor:
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 164, in cursor
>     cursor = self.make_cursor(self._cursor())
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
>     self.ensure_connection()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
>     self.connect()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
>     self.connect()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, async=async)
> django.db.utils.OperationalError: could not connect to server: Connection refused
> 	Is the server running on host "127.0.0.1" and accepting
> 	TCP/IP connections on port 5432?
> 
> 
> python manage.py collectstatic --noinput failed, check your configuration
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
>     django.setup()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
>     app_config.ready()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 68, in ready
>     load_core_settings()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 56, in load_core_settings
>     parameters.register(GeneralParametersForm, ugettext_lazy("General"))
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 192, in register
>     form = formclass()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/app_settings.py", line 261, in __init__
>     super(GeneralParametersForm, self).__init__(*args, **kwargs)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 62, in __init__
>     self._load_initial_values()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 96, in _load_initial_values
>     if not db_utils.db_table_exists("lib_parameter"):
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/db_utils.py", line 12, in db_table_exists
>     return table in connection.introspection.table_names()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
>     with self.connection.cursor() as cursor:
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 164, in cursor
>     cursor = self.make_cursor(self._cursor())
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
>     self.ensure_connection()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
>     self.connect()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
>     self.connect()
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
>     connection = Database.connect(**conn_params)
>   File "/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, async=async)
> django.db.utils.OperationalError: could not connect to server: Connection refused
> 	Is the server running on host "127.0.0.1" and accepting
> 	TCP/IP connections on port 5432?
> 
> 
> python manage.py set_default_site jepse.xyz failed, check your configuration
> Traceback (most recent call last):
>   File "./run.py", line 64, in <module>
>     main()
>   File "./run.py", line 54, in main
>     scripts.install("modoboa", config)
>   File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
>     getattr(script, appname.capitalize())(config).run()
>   File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
>     self.post_run()
>   File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 128, in post_run
>     self.apply_settings()
>   File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 122, in apply_settings
>     query, self.dbname, self.dbuser, self.dbpasswd)
>   File "/root/modoboa-installer/modoboa_installer/database.py", line 48, in _exec_query
>     self._setup_pgpass(dbname, dbuser, dbpassword)
>   File "/root/modoboa-installer/modoboa_installer/database.py", line 84, in _setup_pgpass
>     if self.dbname not in ["localhost", "127.0.0.1"]:
> AttributeError: 'PostgreSQL' object has no attribute 'dbname'
>

**Comment by tonioo** [comment]
Hi,

I think I fixed this issue. Could you try again please ?

**Comment by Mladenovic92** [comment]
It works, thanks.
