### ISSUE TITLE
just a question regarding automated installer

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa-installer#226]
Hi there,

Currently I am manually installing modoboa. Its a good learning experience but I might still revert to the automatic one. 

Does the automatic installer support apache as the webserver? (or could I fool it into using/installing apache?)

regards,
JBR

# Impacted versions

* Distribution: Debian / Ubuntu / Centos
* Codename: Jessie / Trusty / Centos 7 / ...
* Arch: 32 Bits / 64 Bits
* Database: PostgreSQL / MySQL

# Steps to reproduce

# Full trace using --debug option or current behaviour

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@JayBeRayBearGun The installer does not support apache2 for now.
