### ISSUE TITLE
what is the preferred/advised way to configure letsencrypt after installing using a self signed cert?

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa-installer#231]
OK, the subject says it all.

Seems like my installation is working after some DNS, SPF and DKIM tweaking. Next I'd like to upgrade to using a letsencrypt certificate. What would be the best approach? Do it by 'hand' so to speak? Or is there a python script in the instance which can be of use and knows where to put so modoboa's universe is happy ;)

Thanks,
Jan

**Comment by vac** [comment]
What I did was to run installation script again after changing configuration (enabling let's encrypt).
It seems to works. Have some issues with cron but I think it is not modoboa bug.

**Comment by rebbuh** [comment]
Is there really no better way to handle this than running the installation script again?
Can I rely on the modoboa-installer being idempotent, especially w.r.t. configurations, databases etc.?

**Comment by tonioo** [comment]
@rebbuh What would you suggest?

**Comment by rebbuh** [comment]
@tonioo I'm looking forward to the installer's upgrade mode, which I've already sponsored.
