### ISSUE TITLE
Desktop client rejected

### ISSUE THREAD

**Issue by nickdbush** [modoboa/modoboa-installer#237]
# Impacted versions

* Distribution: Ubuntu
* Codename: Bionic Beaver
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
1. Install a fresh copy of modoboa using the installer
2. Create an identity
3. Try to send an email from that identity

# Full trace using --debug option or current behaviour
``` NOQUEUE: reject: RCPT from [HOME_IP_ADDRESS]:61079: 550 5.7.1 Service unavailable; client [HOME_IP_ADDRESS] blocked using zen.spamhaus.org```

I'm not sure if it could have anything to do with another error in the log: ```fatal: in parameter smtpd_relay_restrictions or smtpd_recipient_restrictions, specify at least one working instance of: reject_unauth_destination, defer_unauth_destination, reject, defer, defer_if_permit or check_relay_domains```

I haven't touched any file on the server since the installer ran. Reinstalled the entire OS once and had the same results.

# Expected behavior
The user authenticates properly and the message sends. This works from the webmail dashboard, and fails using any email client (tested with Windows and Thunderbird).

Thanks for making such an amazing tool and I am very much looking forward to resolving these small issues!

**Comment by nickdbush** [comment]
Possibly related to #205, but I can't work out for the life of me why it would work out of the box for some people and not others

**Comment by tonioo** [comment]
@nickdbush How did you configure your email client?
The error you pasted should be fixed anyway, can you paste the complete config file somewhere please?

**Comment by nickdbush** [comment]
Can send mail from email apps on my phone using mobile data, however my home network is the one that is being blocked from accessing. My IP range is on a blocklist, but that's because it's a residential connection (owned by Plusnet, an ISP).

**Comment by tonioo** [comment]
Are you using port 587 with authentication for your email client?

**Comment by nickdbush** [comment]
Yes, 587 with STARTTLS. Having changed that line, and without changing my account settings further, the emails are now sent.
