### ISSUE TITLE
MySQL question

### ISSUE THREAD

**Issue by 0xNeffarion** [modoboa/modoboa-installer#243]
Hello, I have a question

How safe is it to install modoboa on a server with an already existing MySQL instalation? Will it replace anything thats already existing?

**Comment by aurora** [comment]
While the installer seems to work just fine with an existing MySQL server (located on a different host in my case) - all databases are created but the mysql.user table does not have the additional users in it, after an - apparently successful - run of the installer. The users amavis, modoboa, spamassassin and opendkim are missing. Also the view 'dkim' is missing in the modoboa table. I am not sure, if anything else is missing ...
