### ISSUE TITLE
Install modoboa using a remote database server

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa-installer#251]
Hi!

I'm trying to figure what will be needed to install modoboa database and theses plugins at another place than "localhost".

In installer.cfg, we have:

```
[database]
engine = mysql
host = 127.0.0.1
install = false

[mysql]
user = root
password = xxxxxxxxxxx
charset = utf8
collation = utf8_general_ci

[modoboa]
dbname = modoboa
dbuser = modoboa
dbpassword = xxxxxxxxxxx

[amavis]
dbname = amavis
dbuser = amavis
dbpassword = xxxxxxxxxxx

[spamassassin]
dbname = spamassassin
dbuser = spamassassin
dbpassword = xxxxxxxxxxx

[opendkim]
dbuser = opendkim
dbpassword = xxxxxxxxxxx
```

Does the "host" field in [database] used for all database location?
How is handled database, user and tables creation if the database is remote?
What's append if the user creating all these stuff do not have the SUPER privilege?

I'm trying to setup modoboa on AWS with a RDS mariadb database and the SUPER privilege is not available and I got this when I import the database.

```
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`modoboa`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `dkim` AS (select `admin_domain`.`id` AS `id`,`admin_domain`.`name` AS `domain_name`,`admin_domain`.`dkim_private_key_path` AS `private_key_path`,`admin_domain`.`dkim_key_selector` AS `selector` from `admin_domain` where (`admin_domain`.`enable_dkim` = 1)) */
MySQL said: Documentation

#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation
```

**Comment by stefaweb** [comment]
Found a problem using a remote database (not localhost or 127.0.0.1)

The file "postlogin.sh" don not contains the db host in this line:

```
DBNAME=modoboa DBUSER=modoboa DBPASSWORD=xxxxx

echo "UPDATE core_user SET last_login=now() WHERE username='$USER'" | mysql -u $DBUSER -p$DBPASSWORD $DBNAME
```

Seems we need to add:

```
DBHOST=my.remote.host

echo "UPDATE core_user SET last_login=now() WHERE username='$USER'" | mysql -h $DBHOST -u $DBUSER -p$DBPASSWORD $DBNAME
```

**Comment by stefaweb** [comment]
One more.

We may be need a switch in installer.

If dbhost is not localhost, do not install db binary (mysql or other) in the modoboa server.

**Comment by stefaweb** [comment]
Hi @tonioo!

I tried a fresh install with a remote database (MariaDB 10.2 RDS instance on AWS).

The dbuser modoboa and opendkim are well created in MariaDB but the modoboa database not.

Do you know where/how I can have more log during install to check what is wrong during the database creation?

**Comment by tonioo** [comment]
@stefaweb Hi, use the --debug option when you install.

**Comment by stefaweb** [comment]
The last for today.

I finally got more detail on the lxml problem.

`Command "/srv/modoboa/env/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kWRYpt/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-Wd6QRn/install-record.txt --single-version-externally-managed --compile --install-headers /srv/modoboa/env/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-install-kWRYpt/lxml/
`

I enclosed the full output file to this post.
[lxml.errors.txt](https://github.com/modoboa/modoboa-installer/files/2629610/lxml.errors.txt)

**Comment by tonioo** [comment]
About the collation, it looks like ``utf8mb4_unicode_ci`` is not available on RDS. I don't know why but maybe you should look for similar issues.
About lxml, its compilation takes a lot of resource. I guess gcc is being killed because there no enough RAM or something like that.

**Comment by stefaweb** [comment]
@tonioo 

Yes, utf8mb4_unicode_ci is available both on RDS MariaDB or Aurora MySQL (not tried Postgresql). I'm currently using it with others db.

![capture d ecran 2018-11-29 a 19 15 00](https://user-images.githubusercontent.com/12907102/49242538-4db00900-f40b-11e8-9bc6-94c5f43fb737.png)

May be the SQL command sent by the installer is not "compatible" with RDS databases?

Do you have the SQL command sent? I will try manually.

**Comment by stefaweb** [comment]
Hi @tonioo!

I've found the problem. Big error from me.

We need in installer.cfg.

```
[mysql]
user = admin
password = xxxxxxxx
charset = utf8mb4
collation = utf8mb4_unicode_ci
```

NOT "charset = utf8"...

I've done a new install and all is ok now except the problem with `postlogin.sh` and `lxml`.

For lxml, the AWS instance is a 2 cores / 1Mo of RAM with 2 hours of burst. It must be ok to compile lxml but it's to the case in fact.

**Comment by stefaweb** [comment]
More on `lxml` compilation. I made some testing with different EC2 instance.

**The minimum ressource is 2Go or RAM and two cores.**

**Comment by stefaweb** [comment]
Close this issue and create a specific issue for postlogin.sh.

https://github.com/modoboa/modoboa-installer/issues/256
