### ISSUE TITLE
Help request-- login remotely from iOS or Apple Mail?

### ISSUE THREAD

**Issue by arzachel23** [modoboa/modoboa-installer#259]
Sorry to open an issue here, but haven't had any luck finding anyone over on the IRC channel.

So I've managed to get Modoboa installed and working (sending & receiving mail) mostly using LinuxBabe's great guide (https://www.linuxbabe.com/mail-server/email-server-ubuntu-18-04-modoboa).

My problem is that I can't log into my mail remotely from my laptop or iPhone's mail clients.  I'm unsure if I need to set up LDAP to do this (didn't have to with a postfix/dovecot/postgres mailserver I previously set up), or what piece I might be missing.  Any guidance would be most appreciated.

Many thanks!

**Comment by tonioo** [comment]
@arzachel23 you don't need LDAP for this. You should be able to use email services remotely using the hostname of your modoboa instance, port 587, STARTTLS and your account for SMTP and port 143, STARTTLS and your account for IMAP.

**Comment by arzachel23** [comment]
Apple Mail, terrible program that it is, doesn't give any options past Incoming Mail Server & Outgoing Mail server.  Nothing for STARTTLS, no port options (though I tried tacking those on the end of the server after a colon, which didn't work).  :-(

**Comment by arzachel23** [comment]
Thunderbird connects to it just fine.  Befuddled.

**Comment by arzachel23** [comment]
Also got it working on iOS.  I'm going to go w/Apple Mail being FUBAR.  Thanks very much for your help!
