### ISSUE TITLE
TLS Forward Secrecy in Postfix

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#26]
The [main.cf template](https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/files/postfix/main.cf.tpl) currently does not enable [TLS Forward Secrecy in Postfix](http://www.postfix.org/FORWARD_SECRECY_README.html), as no `dhparams` are being generated.

One could copy ideas from

* https://github.com/andryyy/mailcow/blob/18a758cbd02580799c92858754b2b583db3c6f3b/postfix/conf/main.cf#L24-L25
* https://github.com/andryyy/mailcow/blob/18a758cbd02580799c92858754b2b583db3c6f3b/postfix/conf/main.cf#L33-L37
* https://github.com/mail-in-a-box/mailinabox/blob/87d3f2641df010a0ec697d28b61ad895bc91130a/setup/mail-postfix.sh#L124

Is this worth a little update?

**Comment by tonioo** [comment]
Indeed, I think I can add this. Something like:
```ini
[postfix]
tls_forward_secrecy=true|false
```
which will (if enabled) generate a 2048 bits key.
?
