### ISSUE TITLE
amavisd refuses to start in systemd

### ISSUE THREAD

**Issue by cbertelli** [modoboa/modoboa-installer#264]
Context:
Centos 7, 64 bits, PostgreSQL 9.2, fresh install

Mail not received
Systemctl shows:

amavisd.service loaded **failed failed**
amavisd-clean-quarantine.timer loaded active waiting
amavisd-clean-tmp.timer loaded active waiting

when starting amavisd.service the answer is:
Job for amavisd.service failed because the control process exited with error code. See "systemctl status amavisd.service" and "journalctl -xe" for details.

mag 04 11:58:48 myhost systemd[1]: amavisd.service: control process exited, code=exited status=255
mag 04 11:58:48 myhost systemd[1]: Failed to start Amavisd-new is an interface between MTA and content checkers..
mag 04 11:58:48 myhost systemd[1]: Unit amavisd.service entered failed state.
mag 04 11:58:48 myhost systemd[1]: amavisd.service failed.
mag 04 11:58:49 myhost systemd[1]: amavisd.service holdoff time over, scheduling restart.
mag 04 11:58:49 myhost systemd[1]: Stopped Amavisd-new is an interface between MTA and content checkers..
mag 04 11:58:49 myhost systemd[1]: start request repeated too quickly for amavisd.service
mag 04 11:58:49 myhost systemd[1]: Failed to start Amavisd-new is an interface between MTA and content checkers..
mag 04 11:58:49 myhost systemd[1]: Unit amavisd.service entered failed state.
mag 04 11:58:49 myhost systemd[1]: amavisd.service failed.

Amavisd was installed by modoboa, postfix was already installed.

Any suggestion?

**Comment by cbertelli** [comment]
Amavisd started after adding
myhostname = myhost.my.domain (the fully qualified name of my machine),
following this page: https://www.server-world.info/en/note?os=CentOS_7&p=mail&f=6
in the comments of /etc/amavisd/amavisd.conf myhostname is supposed to be optional.

**Comment by ionescu77** [comment]
Hi, ran into the same problem:
- my hostname does not use `mail.my.domain` syntax
- I had to generate the config from template
- modify the config and start `run.py` again

The lines are here in `config_dict_template.py` [line 24](https://github.com/modoboa/modoboa-installer/blob/63c29c34b9d3816467c93567bd0589c08b97f67e/modoboa_installer/config_dict_template.py#L24):
```python
        "name": "general",
        "values": [
            {
                "option": "hostname",
                "default": "mail.%(domain)s",
            }
        ]
```
Hmm, I thought about a simple fix, but a hack is not elegant.
Cause we want to be consistent  with the  `--domain` parameter in `modoba.py` :-(

**Comment by ionescu77** [comment]
I will do it manual first.

- I will run it once in interactive and generate config
`./run.py --stop-after-configfile-check --interactive <your domain>`

- set the hostname acording to [README](https://github.com/modoboa/modoboa-installer#change-the-generated-hostname)
- then start again with `./run.py --debug`

I'll see if I get any ideas.
