### ISSUE TITLE
Support for Let's encrypt behind reverse proxy

### ISSUE THREAD

**Issue by markussc** [modoboa/modoboa-installer#267]
# Impacted versions

* Distribution: Ubuntu 18.04
* Arch: 64 Bits
* Database: N/A to issue

# Steps to reproduce
Try to create letsencrypt certificates when mail server is behind reverse proxy.

# Full trace using --debug option or current behaviour
No certificates are created, all services trying to access the certificates fail to start.

# Expected behavior
Use http-01 webroot authentication for Let's encrypt instead of tls-sni-01 method.

**Comment by horvan** [comment]
It is relatively easy to do this manually by using certbot. and manual reconfiguration. But it would be great if modoboa would provide the option to install apache2 as second server e.g on 8080 and generate a nginx config file for the main domain. So modoboa could be insalled with more ease by useing the autoinstaller and a normal website could be provided by useing apache if someone likes to do so. You can use nginx upstream directive to do this.
