### ISSUE TITLE
Multiserver clusters (Question)

### ISSUE THREAD

**Issue by tumbledcoin** [modoboa/modoboa-installer#269]
# Multi server installation
1.13.1
Ubuntu
Xenial 
64 Bits
PostgreSQL / MySQL

This is not an issue more a question. Is Modoboa capable of being ran within a cluster? I have attempted to search and read through the documentation and I see no mention of this. 

My preferred setup would be to have either a primary server and failover server, or dual node setup. 
Would this be as simple as just sharing the modoboa database between 2 or more servers?

**Comment by tonioo** [comment]
@tumbledcoin Building a multiserver mail architecture can be tricky. It is not just about modoboa, think about postfix, dovecot and the antispam. Modoboa frontend is just a web app so it is pretty easy to make it run on a cluster.
