### ISSUE TITLE
Enable API programatically

### ISSUE THREAD

**Issue by planetscripton** [modoboa/modoboa-installer#270]
# Impacted versions
Latest

* Distribution: Ubuntu
* Codename: Xenial
* Arch: 64 Bits
* Database: PostgreSQL

Hello, is there any way to programatically enable the API either during install (using modoboa_installer), or after install via the command line? I would also want to be able to manually set, or get the API token programatically too.
This is so that I can install, and then programatically create domains and mailboxes for a test-lab environment, using Ansible.

Thanks for your help.
Dan

**Comment by tonioo** [comment]
@planetscripton It is possible currently.

**Comment by planetscripton** [comment]
> @planetscripton It is possible currently.

Did you mean that it is possible? Or it is not possible?

Thanks.

**Comment by tonioo** [comment]
@planetscripton Sorry, I meant it is not possible.
