### ISSUE TITLE
How to log in after installation

### ISSUE THREAD

**Issue by fcantell** [modoboa/modoboa-installer#271]
Hello I have installed twice the Modoboa
and both time I didn't recevie at the end any indication on how to access the admin page
I tried few url from the same server but I alwasy get browser error

DNS has been configured as per requirements
Hostanme of the server is also in the format mail.<domain>

Any advice/help?
thanks
Franco 

Welcome to Modoboa installer!

Configuration file installer.cfg not found, creating new one.
Warning:
Before you start the installation, please make sure the following DNS records exist for domain 'tpuc.com':
  mail IN A   <IP ADDRESS OF YOUR SERVER>
       IN MX  mail.tpuc.com.

Your mail server will be installed with the following components:
modoboa automx amavis clamav dovecot nginx razor postfix postwhite spamassassin uwsgi radicale opendkim
Do you confirm? (Y/n) Y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Overwrite the existing SSL certificate? (y/N) y
Generating new self-signed certificate
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing modoboa
User modoboa already exists, skipping creation but please make sure the /srv/modoboa directory exists.

# Impacted versions

* Distribution: Centos
* Codename: Centos 7 /
* Arch:  64 Bits

# Steps to reproduce

# Full trace using --debug option or current behaviour

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@fcantell There is a message at the end of the installation process containing the information you're looking for, unless the installation failed before the end...
