### ISSUE TITLE
Broken VirtualEnv after system python updates: Debian 10 Buster

### ISSUE THREAD

**Issue by gianks** [modoboa/modoboa-installer#273]
# Impacted versions
1.14.0

* Distribution: Debian
* Codename: Buster
* Arch: 64 Bits
* Database: PostgreSQL
# Steps to reproduce
Steps to upgrade as described here: https://modoboa.readthedocs.io/en/latest/upgrade.html
After last updates of debian packages the virtualenv is broken and need to be rebuilt.
Need a procedure to do it gracefully without reinstalling the entire mailserver.
The attemps to reinstall deleting modoboa have all failed, needed to rollback the vm.

# Full trace using --debug option or current behaviour
```
modoboa@mx1:~$ source  /srv/modoboa/env/bin/activate
(env) modoboa@mx1:~$ pip
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/_internal/__init__.py", line 5, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

```
# Expected behavior
Regular upgrade

# Video/Screenshot link (optional)

**Comment by gianks** [comment]
Seems i've been able to 'repair' the virtual environment ( see: https://gist.githubusercontent.com/ttimasdf/34bc85ac008f68b2ee098850cab2979c/raw/56143d3301322136714e429079c164664f603945/fix_virtualenv taken from here: https://gist.github.com/tevino/1a557a0c200d61d4e4fb), it required to reinstall the needed modoboa modules (webmail, contacts, and so on) via pip but after all i've been able to run "run.py upgrade" and it didn't raise errors, but during the deploy the following warning were raised:
```
WARNINGS:
?: (modoboa-amavis.W001) AMAVIS_DEFAULT_DATABASE_ENCODING does not match the character encoding used by the Amavis database.
        HINT: Check your database character encoding and set/update AMAVIS_DEFAULT_DATABASE_ENCODING.
?: (security.W001) You do not have 'django.middleware.security.SecurityMiddleware' in your MIDDLEWARE so the SECURE_HSTS_SECONDS, SECURE_CONTENT_TYPE_NOSNIFF, SECURE_BROWSER_XSS_FILTER, and SECURE_SSL_REDIRECT settings will have no effect.
```

Now i get a error 500 surfing the web frontend, even after restarting the whole system.
Looking into /var/log/uwsgi/app/modoboa_instance.log i see:
```
Traceback (most recent call last):
  File "./instance/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/apps/registry.py", line 78, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Sat Jul 13 22:05:05 2019 - unable to load app 0 (mountpoint='mail.XXX.it|') (callable not found or import error)
Sat Jul 13 22:05:05 2019 - --- no python application found, check your startup logs for errors ---
mail.XXX.it [pid: 3586|app: -1|req: -1/16] 10.0.4.10 () {52 vars in 1011 bytes} [Sat Jul 13 22:05:05 2019] GET /favicon.ico => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
```

As  far as i understood out of a quick search the problem seems to be related to nginx and django and could be caused by the nginx architecture in certain scenarios, expecially with uwsgi, reason to consider potentially switching to apache.

**Comment by tonioo** [comment]
@gianks When you upgrade your operating system, python version will be updated too. That's generally why virtualenvs are broken after. One solution to fix issues is to reinstall the virtualenv from scratch like you did. About the reentrant issue, it can happen sometimes. Have you found a solution?
