### ISSUE TITLE
postlogin.sh script is public read and should not be.

### ISSUE THREAD

**Issue by erenfro** [modoboa/modoboa-installer#275]
# Impacted versions
1.14.0

* Distribution: Debian
* Codename: Stretch
* Arch: 64 Bits
* Database: MySQL

# Steps to reproduce
Use modoboa-installer to install modoboa normally.

# Full trace using --debug option or current behaviour

# Expected behavior
/usr/local/bin/postlogin.sh is not world readable (it has passwords!) Also it really should not be in /usr/local/ because of it's security nature. At the very least, however, it should not be in /usr/local/bin nor should it be public world readable. Alternative locations would include /usr/local/sbin, and /srv/modoboa/ as alternatives, since it's specifically related to modoboa.

# Video/Screenshot link (optional)

**Comment by tomcrus001** [comment]
Maybe this would be fixed if my suggestion of using an additional subcommand of *Modoboa*'s `manage.py` command (like `manage.py update-last-login` gets accepted, see [Annoing warning in error log with mysql DB](https://github.com/modoboa/modoboa/issues/1477)
