### ISSUE TITLE
Modoba installer broke nginx configuration 

### ISSUE THREAD

**Issue by abkrim** [modoboa/modoboa-installer#276]
# Impacted versions

* Distribution: Ubuntu 18.04
* Codename: Bionic
* Arch: 64 Bits
* Database: MySQL

# Steps to reproduce

- I just [install modoba](git clone https://github.com/modoboa/modoboa-installer) in server with nginx 1.16.0 + php-fpm + MySQL 8.0 installed. 
- In server 2 blocks of nginx (virtual hosts)
- After install if any user go to incorrect URL on any domain aliases of any of two blocks, nginx redirect to first block instead server errror on own block
- After I'm investigating issue,  solution is simple:
   - Remove form niginx, blocks of modoba. After this action,  my system work fine.

**Comment by tonioo** [comment]
@abkrim You installed modoboa on a running server? (with already deployed components)

**Comment by findSaif** [comment]
I faced a similar issue where my nginx kept giving this error **bind() to 0.0.0.0:443 failed (98: Address already in use)**. I installed modoboa on a running LEMP stack. This is how I fixed it:

`sudo fuser -k 443/tcps`
`sudo service nginx restart`

**Comment by silversky120** [comment]
I've got the same issue. Thats how I fixed it:

I changed the `server_names_hash_bucket_size` in **/etc/nginx/nginx.conf** to 64.


`server_names_hash_bucket_size 64;`

Than restart the nginx service.

`systemctl restart nginx`

What is server_names_hash_bucket_size?
https://gist.github.com/muhammadghazali/6c2b8c80d5528e3118613746e0041263
