### ISSUE TITLE
Error after "Installing amavis" Error = "Amavis is not installed"

### ISSUE THREAD

**Issue by gldtn** [modoboa/modoboa-installer#277]
# Impacted versions

* Distribution: Ubuntu 19.04
* Codename: Disco
* Arch: 64 Bits
* Database: PostgreSQL
* python-pip  version (18.1-5)
* python-virtualenv version (15.1.0+ds-2).

# Steps to reproduce
I followed this guide: https://www.linuxbabe.com/mail-server/email-server-ubuntu-18-04-modoboa

# Full trace using --debug option or current behavior
`$ sudo ./run.py --interactive --debug  glaudston.com
Welcome to Modoboa installer!

Warning:
Before you start the installation, please make sure the following DNS records exist for domain 'glaudston.com':
  mail IN A   <IP ADDRESS OF YOUR SERVER>
       IN MX  mail.glaudston.com.

Your mail server will be installed with the following components:
modoboa automx amavis clamav dovecot nginx razor postfix postwhite spamassassin uwsgi radicale opendkim
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Hit:1 http://mirrors.linode.com/ubuntu disco InRelease
Hit:2 http://mirrors.linode.com/ubuntu disco-updates InRelease
Hit:3 http://mirrors.linode.com/ubuntu disco-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu disco-security InRelease [97.5 kB]
Hit:5 http://archive.canonical.com/ubuntu disco InRelease
Hit:6 http://ppa.launchpad.net/certbot/certbot/ubuntu disco InRelease
Fetched 97.5 kB in 1s (103 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
sudo is already the newest version (1.8.27-1ubuntu1).
wget is already the newest version (1.20.1-1ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Generating new certificate using letsencrypt
--2019-09-01 17:31:54--  https://dl.eff.org/certbot-auto
Resolving dl.eff.org (dl.eff.org)... 2a04:4e42:46::201, 199.232.36.201
Connecting to dl.eff.org (dl.eff.org)|2a04:4e42:46::201|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68689 (67K) [application/octet-stream]
Saving to: ‘certbot-auto.8’

certbot-auto.8          100%[============================>]  67.08K  --.-KB/s    in 0.007s

2019-09-01 17:31:54 (10.0 MB/s) - ‘certbot-auto.8’ saved [68689/68689]

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for mail.glaudston.com
Cleaning up challenges
Problem binding to port 80: Could not bind to IPv4 or IPv6.
Can't open /etc/letsencrypt/renewal/mail.glaudston.com.conf: No such file or directory.
Installing amavis
Reading package lists...
Building dependency tree...
Reading state information...
Package ripole is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package zoo is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ripole' has no installation candidate
E: Package 'zoo' has no installation candidate
Reading package lists...
Building dependency tree...
Reading state information...
postgresql is already the newest version (11+199).
postgresql-server-dev-all is already the newest version (199).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable postgresql
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sun 2019-09-01 17:30:37 EDT; 1min 22s ago
 Main PID: 24942 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   Memory: 0B
   CGroup: /system.slice/postgresql.service

Sep 01 17:30:37 kitana systemd[1]: Starting PostgreSQL RDBMS...
Sep 01 17:30:37 kitana systemd[1]: Started PostgreSQL RDBMS.
1
createdb: database creation failed: ERROR:  database "amavis" already exists
Amavis is not installed`

First time it said "Installing amavis.." and it gave me the error "Amavis is not installed"

**Comment by allamiro** [comment]
I have the same issue 

```


Installing amavis
Reading package lists...
Building dependency tree...
Reading state information...
Package ripole is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package zoo is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ripole' has no installation candidate
E: Package 'zoo' has no installation candidate
Reading package lists...
Building dependency tree...
Reading state information...
postgresql is already the newest version (11+199).
postgresql-server-dev-all is already the newest version (199).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Synchronizing state of postgresql.service with SysV service script with /lib/sys                                                                                                                                                                                                                                                                           temd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable postgresql
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor prese
   Active: active (exited) since Sat 2019-09-21 06:39:44 UTC; 1min 8s ago
 Main PID: 11195 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 1146)
   Memory: 0B
   CGroup: /system.slice/postgresql.service

Sep 21 06:39:44 mail systemd[1]: Starting PostgreSQL RDBMS...
Sep 21 06:39:44 mail systemd[1]: Started PostgreSQL RDBMS.
lines 1-10/10 (END)...skipping...
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2019-09-21 06:39:44 UTC; 1min 8s ago
 Main PID: 11195 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 1146)
   Memory: 0B
   CGroup: /system.slice/postgresql.service

Sep 21 06:39:44 mail systemd[1]: Starting PostgreSQL RDBMS...
Sep 21 06:39:44 mail systemd[1]: Started PostgreSQL RDBMS.





```

**Comment by treegit** [comment]
This seems to be because of extra package dependencies for amavisd-new on dpkg backends which are no longer available in Debian Buster:

ripole
zoo

Removing those packages allows the install to proceed.

Note that ripole is used to investigate MS document attachments, so if you are an MS Office user there may be side effects.

Cheers

**Comment by treegit** [comment]
I should add that what actually happens is the amavisd-new install fails, but the installer then continues to install postgresql afterwards.

The last part of the amavis install is to run the sql to create the amavis schema, but this fails because it cannot determine which version of amavis is installed (because no version is installed).

It would be better if the error message stated why Amavis was not installed on the FatalError line in scripts/amavis.py get_sql_schema_path

**Comment by tonioo** [comment]
This issue should be fixed now, and I added a fix to make the installer stop if it can't install a package.
