### ISSUE TITLE
Got an Spamassassin Issue

### ISSUE THREAD

**Issue by ThSeyfarth** [modoboa/modoboa-installer#278]
Hey Guys, 
i tried to run your Installation Guide but if i run the Scritp "./run.py" i got an Spamassassin Error Failurecode(2)

* Distribution: Debian 9
Nevermind i did something wrong. 
Anyone know about this issue?

**Comment by ThSeyfarth** [comment]
...sorry was forgotten to post you the Errorlog:

spamassassin (3.4.2-1~deb9u1) wird eingerichtet ...
-su: 29: /usr/share/bash-completion/bash_completion: [[: not found
-su: 35: /usr/share/bash-completion/bash_completion: [[: not found
-su: 51: /usr/share/bash-completion/bash_completion: shopt: not found
-su: 57: /usr/share/bash-completion/bash_completion: complete: not found
-su: 62: /usr/share/bash-completion/bash_completion: complete: not found
-su: 65: /usr/share/bash-completion/bash_completion: complete: not found
-su: 68: /usr/share/bash-completion/bash_completion: complete: not found
-su: 71: /usr/share/bash-completion/bash_completion: complete: not found
-su: 74: /usr/share/bash-completion/bash_completion: complete: not found
-su: 77: /usr/share/bash-completion/bash_completion: complete: not found
-su: 80: /usr/share/bash-completion/bash_completion: complete: not found
-su: 83: /usr/share/bash-completion/bash_completion: complete: not found
-su: 86: /usr/share/bash-completion/bash_completion: complete: not found
-su: 89: /usr/share/bash-completion/bash_completion: complete: not found
-su: 92: /usr/share/bash-completion/bash_completion: complete: not found
-su: 101: /usr/share/bash-completion/bash_completion: Syntax error: "(" unexpected (expecting "}")
dpkg: Fehler beim Bearbeiten des Paketes spamassassin (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 2 zurück

The German words mean in: 
Line   1: spamassassin will be organized
Line 18: Failure during editing of spamassassin
Line 19: Subprocess installed post-installation-script returns Value 2

Hope any of you can help me about this Issue.

**Comment by tonioo** [comment]
@ThSeyfarth what shell are you runing?
