### ISSUE TITLE
ADD CUSTOM LOGO 

### ISSUE THREAD

**Issue by cenix102** [modoboa/modoboa-installer#279]
Modoboa version 1.14.

* Distribution: Ubuntu
* Codename: Bionic Beaver
* Arch: 364 Bits
* Database: MySQL

enable and changing the variable CUSTOM_LOGO in the settings.py 
`MODOBOA_CUSTOM_LOGO = os.path.join(MEDIA_URL, "mylogo.png")`

looking for the MEDIA_ROOT directory: 
`cat /settings.py | grep MEDIA_ROOT
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')`

add mylogo to media directory 
`root@mysrv:/srv/modoboa/instance/media# pwd
/srv/modoboa/instance/media
root@mysrv#:/srv/modoboa/instance/media# ll
total 20
drwxr-xr-x 3 modoboa modoboa 4096 Sep 30 21:52 ./
drwxr-xr-x 5 modoboa modoboa 4096 Sep 30 19:45 ../
-rw-r--r-- 1 modoboa modoboa 6386 Sep 30 21:52 mylogo.png
drwxr-x--- 2 modoboa modoboa 4096 Sep 30 19:45 webmail/`

restarting nginx
`systemctl restart nginx.service`

clearing browser cache:
... 

looking for logo: 
![image](https://user-images.githubusercontent.com/46600012/65913458-40b7c980-e3d0-11e9-89e2-a7b71630506e.png)

First off all your doing a awesome job! I really like modoboa... 

What I'm doing wrong here? Thanks for your help!

**Comment by tonioo** [comment]
@cenix102 You must reload uwsgi too.

**Comment by cenix102** [comment]
@tonioo Works now perfect! Thanks a lot! 

For the community: 
`systemctl restart uwsgi`

**Comment by sabo14** [comment]
can you please tell me exact path where i can copy custom logo

**Comment by kaif77** [comment]
> can you please tell me exact path where i can copy custom logo

path to add media files
/srv/modoboa/instance/media

then restart uwsgi
