### ISSUE TITLE
I can not upgrade!

### ISSUE THREAD

**Issue by foxinstone** [modoboa/modoboa-installer#280]
# Impacted versions

* Distribution: Ubuntu
* Codename: 16.04.6.
* Arch: 64 Bits
* Database: PostgreSQL

 Follow the upgrade guide or reinstall ,  i can not upgrade my modoboa from 1.10.6 to 1.14.0.
Why?
The last error:

![image](https://user-images.githubusercontent.com/35874666/66265872-9d3f3c80-e847-11e9-9c97-00d0cef6ec51.png)

**Comment by foxinstone** [comment]
In fact, At first I used the PIP upgrade method, but the post-upgrade page showed an internal error. So , I tried to reinstall, so I manually deleted /srv/modoboa and deleted the user modoboa, but I encountered this error.
BTW, I Just upgrade my OS to 18.04, The fault remains。
I think it will be a database problem, but I can't delete the old database because I can't stop modoboa...

**Comment by foxinstone** [comment]
I just deleted old database, but the fault remains。

**Comment by tonioo** [comment]
@foxinstone Can you run the installer using the --debug option?

**Comment by foxinstone** [comment]
ok， --debug：
![image](https://user-images.githubusercontent.com/35874666/66694228-7798b400-ecdb-11e9-909c-94aff194c521.png)

**Comment by tonioo** [comment]
@foxinstone Can you paste the full trace somewhere?

**Comment by foxinstone** [comment]
I don't quite understand what you mean. Because the previous installation steps are not wrong!
the full trace:
[Full trace.txt](https://github.com/modoboa/modoboa-installer/files/3721734/Full.trace.txt)

**Comment by tonioo** [comment]
@foxinstone Can you try to remove the modoboa system group and retry the installer?

**Comment by foxinstone** [comment]
OK, After deleting the system group, the installation can proceed to "Enjoy...", but the web page still cannot be accessed normally.
![image](https://user-images.githubusercontent.com/35874666/66990545-9a1e3900-f0f0-11e9-9d54-7b33a8c87d09.png)

**Comment by tonioo** [comment]
@foxinstone Can you check if uwsgi is running?

**Comment by foxinstone** [comment]
no, i can not do this, How?
But i do not think so, because there are 0-lines in /var/log/app/modoboa_instance.log.

**Comment by cremesk** [comment]
@foxinstone you can check the uwsgi service with:
`systemctl status uwsgi.service`

**Comment by foxinstone** [comment]
thanks, i forgot this!
![image](https://user-images.githubusercontent.com/35874666/67018559-9ce75100-f125-11e9-9520-f032f6d321a5.png)
it is runing! But i am sure that I have not modified nginx, Why can't I access it after upgrading?

**Comment by foxinstone** [comment]
![image](https://user-images.githubusercontent.com/35874666/67019704-48dd6c00-f127-11e9-8600-d8935aad56db.png)
![image](https://user-images.githubusercontent.com/35874666/67019736-55fa5b00-f127-11e9-8068-d3087381b26f.png)

these sections was auto created, Except ssl_certificate & ssl_certificate_key, I have not modified any place! And as you can see, SSL is good.

**Comment by foxinstone** [comment]
BTW. Now, the  /var/log/app/modoboa_instance.log is a long file...
