### ISSUE TITLE
NotImplementedError: Sorry, this distribution is not supported yet.

### ISSUE THREAD

**Issue by amalvijayanneovibe** [modoboa/modoboa-installer#282]
![Screenshot from 2019-10-21 18-54-50](https://user-images.githubusercontent.com/46814040/67209054-48e5b080-f434-11e9-8bc8-7b916e44925c.png)
# Impacted versions

* Distribution: Debian / Ubuntu / Centos
* Codename: Jessie / Trusty / Centos 7 / ...
* Arch: 32 Bits / 64 Bits
* Database: PostgreSQL / MySQL

# Steps to reproduce

# Full trace using --debug option or current behaviour

# Expected behavior

# Video/Screenshot link (optional)

i got an error like this while executing "sudo ./run.py [my domain here]"

Traceback (most recent call last):
  File "./run.py", line 13, in <module>
    from modoboa_installer import package
  File "/home/amal/modoboa-installer/modoboa_installer/package.py", line 105, in <module>
    backend = get_backend()
  File "/home/amal/modoboa-installer/modoboa_installer/package.py", line 101, in get_backend
    "Sorry, this distribution is not supported yet.")
NotImplementedError: Sorry, this distribution is not supported yet.

My OS is ubuntu 18.04 LTS

![Screenshot from 2019-10-21 18-54-50](https://user-images.githubusercontent.com/46814040/67209348-d0cbba80-f434-11e9-902a-2b04e2307ba8.png)

**Comment by tonioo** [comment]
@amalvijayanneovibe Ubuntu is actually a supported distribution so it should not happen. Is your OS installation special in some way?

**Comment by Aadilhassan** [comment]
I am facing the same error....
![image](https://user-images.githubusercontent.com/68943818/224414631-37a4de5d-f162-4157-8ebb-5a128b42a7c2.png)
