### ISSUE TITLE
"generate_rights" for radicale runs every 2 minutes even if radicale not installed, clogs up root mailfile

### ISSUE THREAD

**Issue by lunimon** [modoboa/modoboa-installer#283]
# Impacted versions

* Distribution: Ubuntu
* Codename: Trusty
* Arch: 64 Bits
* Database: MySQL

# Steps to reproduce
Download installer, start installer, back out. 
Edit installer.cfg to have in the [radicale] section: "enabled = false"
Run installation, everything else default (other than DB mysql)
Check /var/mail/root after install and see it grow a bit every 2 minutes
Mail with error message about "generate rights" command.
When you edit /etc/cron.d/modoboa and comment out the "# Radicale rights file" section, then the problem stops.

Maybe I should have also removed the "modoboa-radicale" part in the extensions line in the installer.cfg. (should I?) couldn't find much info on it.

Suggestion: when disabling a tool, make sure modoboa doesn't try to run it repeatedly (automatically disable extension?)

**Comment by tonioo** [comment]
To fully disable radicale, you need to set the `enabled` flag to `false` in the `radicale` section AND you must remove the `modoboa-radicale` extension from the list available in the `modoboa` section. The cron command is linked to the modoboa extension, not the radicale server itself.
