### ISSUE TITLE
Integration with FreeIPA (ldap) for external authentication

### ISSUE THREAD

**Issue by km1** [modoboa/modoboa-installer#284]
# Impacted versions
1.14.0

* Distribution: Centos
* Codename: Centos 7
* Arch: 64 Bits
* Database: PostgreSQL

I would like to integrate with FreeIPA just for "External Authentication". I don't need to synchronize accounts. I filled up the:
* LDAP Settings - those are fine (I verified it connecting using cmd)
* LDAP authentication settings:
BIND DN: uid=$USER,cn=users,cn=accounts,dc=example,dc=com
Users search base: dc=example,dc=com
Search filter: mail 

Not sure those option correct? Have tried with: cn=users,cn=accounts

* LDAP synchronization settings
Left with both option set to "No". No other option are set. 

All configuration as in documentation is done (settings.py), services restarted. 
After configuration it still uses internal password which was set during account creation in modoboa. Tested on Thunderbird.

Maybe there is someone who has integrated modoboa with FreeIPA and has some knowledge how to connect it?

**Comment by tonioo** [comment]
@km1 Have you modified the `AUTHENTICATION_BACKENDS` setting? (https://modoboa.readthedocs.io/en/latest/configuration.html#ldap)
