### ISSUE TITLE
Installation on Fresh Ubuntu 18.04 fails. HTTP returns NGINX default page. HTTPS returns "Bad Request (400)"

### ISSUE THREAD

**Issue by dmccabe-kinex** [modoboa/modoboa-installer#286]
# Impacted versions

* Distribution: Debian / Ubuntu / Centos
* Codename: Jessie / Trusty / Centos 7 / ...
* Arch: 32 Bits / 64 Bits
* Database: PostgreSQL / MySQL

# Steps to reproduce

# Full trace using --debug option or current behaviour

# Expected behavior

# Video/Screenshot link (optional)

After installing a fresh Ubuntu 18.04.3 LTS, and updating all stock packages, I followed the steps indicated in the installer, including sudo apt install --install-recommends python-virtualenv python-pip

The installer "successfully" installs. However, when I try to access the site using it's lP address, both HTTP and HTTPS exhibit errors. HTTP displays the nginx default page. HTTPS prompts for secure certificate, and then displays "Bad Request (400)" after acceptance of certificate. I have tried it on Debian 10 as well as Ubuntu 18.04.3 with the same results. 

Please advise.

**Comment by tonioo** [comment]
@dmccabe-kinex You can't access the modoboa interface using an IP address but using the hostname printed at the end of the installation process. If your DNS is not setup yet, just add an entry to your local /etc/hosts file.
