### ISSUE TITLE
automx is no longer developed. Switch to automx2 in the next release ?

### ISSUE THREAD

**Issue by vinayaga-raman** [modoboa/modoboa-installer#287]
Auto configuration using automx is not working well in many cases in the existing modoboa installations. This is of course because of the old automx configurations.

automx2 seems to be much more relevant and works across a spectrum of devices. Should modoboa try and switch to automx2 ?

# Impacted versions

* Distribution: Debian / Ubuntu / Centos
* Codename: Jessie / Trusty / Centos 7 / ...
* Arch: 32 Bits / 64 Bits
* Database: PostgreSQL / MySQL

# Steps to reproduce

# Full trace using --debug option or current behaviour

# Expected behavior

# Video/Screenshot link (optional)

**Comment by indiverbadal** [comment]
Is there a plan to support or switch to automx2 soon?
