### ISSUE TITLE
Can't opem unix socket

### ISSUE THREAD

**Issue by mrananyan** [modoboa/modoboa-installer#288]
# Impacted versions

* Distribution: Debian 
* Codename: 9.11 stretch
* Arch: 64 Bits
* Database: MySQL

# Steps to reproduce

after installing by ```./run.py --interactive domain.com``` mail.domain.com show 502 error. I tried to restart uwsgi ```/etc/init.d/uwsgi restart``` and runed it manually ```uwsgi /etc/uwsgi/apps-enabled/modoboa_instance.ini ``` but it's not helped. 

# UPD

```` /run/uwsgi/app/modoboa_instance/socket``` is exists but it's empty. After removing and restarting uwsgi it's creating automaticly but empty

# Expected behavior

# Video/Screenshot link (optional)

# HOW TO FIX 
After updating debian to 9.11 (31.12.2019) you need to give permission to allow nginx to use sockets from /run/ folder

**Comment by vinayaga-raman** [comment]
Im seeing the same behaviour in Ubuntu. Changing trhe permissions to 666 seems to help

**Comment by tonioo** [comment]
@mrananyan @vinayaga-raman  A UNIX socket is not a real file so it is normal if it's empty. About permissions, the socket should be created with a 660 mask (which authorizes write operation to group members) and should belong to modoboa:modoboa. The nginx user (www-data on debian like systems) should be a member of the modoboa group and you can check it using the following command:
```
$ groups www-data
```
And also make sure the socket belongs to the right user/group.
