### ISSUE TITLE
Failures after upgrade

### ISSUE THREAD

**Issue by scrolls-mckenzie** [modoboa/modoboa-installer#29]
I am having webmail GUI access issues with users. My superadmin account can access webmail GUI fine, but all others receive this error when trying to load the GUI

Error: Connection to IMAP server failed: [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Comment by tonioo** [comment]
Hi, I guess there is an issue with the SSL certificate installed on your server. Is it a valid one or the one provided by default by the installer ?

**Comment by tonioo** [comment]
@scrolls-mckenzie ping
