### ISSUE TITLE
Problem with the Installer: module 'platform' has no attribute 'linux_distribution'

### ISSUE THREAD

**Issue by ghost** [modoboa/modoboa-installer#290]
Impacted versions

Modoboa: BRAND NEW
installer used: Yes
Webserver: Nginx
Steps to reproduce

I downloaded the installer and I get the following error when I run it.

Traceback (most recent call last):
File "./run.py", line 13, in 
from modoboa_installer import package
File "/home/codiergott/modoboa-installer/modoboa_installer/package.py", line 105, in 
backend = get_backend()
File "/home/codiergott/modoboa-installer/modoboa_installer/package.py", line 93, in get_backend
distname = utils.dist_name()
File "/home/codiergott/modoboa-installer/modoboa_installer/utils.py", line 79, in dist_name
name, version, _id = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

I use ArchLinux and Python 3.8.1.

**Comment by gzubicki** [comment]
I have the same problem,  ubuntu 20.4, Python 3.8.2

**Comment by tonioo** [comment]
@gzubicki On which distribution are you trying to install modoboa?

**Comment by gzubicki** [comment]
I said,  ubuntu 20.4, Python 3.8.2. It's work

**Comment by janpieper** [comment]
See https://docs.python.org/3.7/library/platform.html#platform.linux_distribution.

> ### platform.linux_distribution([...])
> [...]
> Deprecated since version 3.5, will be removed in version 3.8: See alternative like the distro package.

Seems like Modoboa does not support python 3.8 at the moment.

**Comment by almereyda** [comment]
This seems to be fixed in current `master`. Checking it out gives me:

```
def dist_info():
    """Try to return information about the system we're running 
on."""
    try:
        # Python 3.8 and up way
        import distro
        return distro.linux_distribution()
    except ImportError:
        # Python 3.7 and down way
        import platform
        return platform.linux_distribution()
    printcolor(
        "Failed to retrieve information about your system, abort
ing.",
        RED)
    sys.exit(1)


def dist_name():
    """Try to guess the distribution name."""
    name, version, _id = dist_info()
    return name.lower()

```
