### ISSUE TITLE
[domain relay] error mx and more...

### ISSUE THREAD

**Issue by mikysal78** [modoboa/modoboa-installer#295]
I set Modoboa for secondary mx and i see this error. DNS is ok!
https://pasteboard.co/ISJ07M8.png

**Comment by tonioo** [comment]
@mikysal78 you're talking about subdomains? Have you made some manual tests from the command line to see if DNS resolving is fine?

**Comment by mikysal78** [comment]
> @mikysal78 you're talking about subdomains? Have you made some manual tests from the command line to see if DNS resolving is fine?

yes, ping and no firewall
