### ISSUE TITLE
Modoboa Web Frontend not working after reboot

### ISSUE THREAD

**Issue by snics** [modoboa/modoboa-installer#30]
Hallo,

The Modoboa Frontend not working after reboot. I'm use a Debian System and and also Nginx Server but the Modoboa Frontend is not available.

Can someone help me?

**Comment by tonioo** [comment]
Hi, could you give more information please? What kind of error do you encounter?

**Comment by snics** [comment]
Hi tomioo,

Thanks for your answer!

The installation went without problems and until also works perfect first time. But after restart my Debian Server I got the following error on browser:

Failed to load resource: net::ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY.

Where can I find then a error log file so I can give them?

Thank you very much
Nico

**Comment by tonioo** [comment]
Have you tried using different browsers? What is the one you use?
I guess there is an issue with the default SSL certificate used by the installer... Have you changed this part in the installer config file?

**Comment by snics** [comment]
Hi tonioo, it's working again.

the problem were the following nginx settings:
#ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
#ssl_ciphers RC4:HIGH:!aNULL:!MD5;
#ssl_prefer_server_ciphers on;
#ssl_verify_depth 3;

thanks for helping!!!

**Comment by almereyda** [comment]
@snics Are these your old or newly adapted nginx settings?

**Comment by tonioo** [comment]
The installer now generates a self-signed certificate by default so this issue should be fixed.
