### ISSUE TITLE
clamav errors on ubuntu 18

### ISSUE THREAD

**Issue by doftorul** [modoboa/modoboa-installer#306]
* installer used: Yes
* Webserver: Nginx

# Current behavior

Mar 23 00:36:36 mail amavis[2252]: (02252-08) (!)connect to /var/run/clamav/clamd.ctl failed, attempt modoboa/modoboa#1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: Connection refused
Mar 23 00:36:37 mail amavis[2252]: (02252-08) (!)connect to /var/run/clamav/clamd.ctl failed, attempt modoboa/modoboa#1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: Connection refused
Mar 23 00:36:37 mail amavis[2252]: (02252-08) (!)ClamAV-clamd: All attempts (1) failed connecting to /var/run/clamav/clamd.ctl, retrying (2)
Mar 23 00:36:43 mail amavis[2252]: (02252-08) (!)connect to /var/run/clamav/clamd.ctl failed, attempt modoboa/modoboa#1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: Connection refused
Mar 23 00:36:43 mail amavis[2252]: (02252-08) (!)ClamAV-clamd av-scanner FAILED: run_av error: Too many retries to talk to /var/run/clamav/clamd.ctl (All attempts (1) failed connecting to /var/run/clamav/clamd.ctl) at (eval 114) line 659.\n
Mar 23 00:36:43 mail amavis[2252]: (02252-08) (!)WARN: all primary virus scanners failed, considering backups

#### FIX #####

Edit  /etc/clamav/clamd.conf and add "AllowSupplementaryGroups true" to the end of file.
Restart the clamav-daemon service and all should be well.
Tested on Debian Jessie and Ubunutu 18.04.2

**Comment by tonioo** [comment]
@doftorul That's strange because the installer is already supposed to do it: https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/clamav.py#L41. Are you using the latest version?

**Comment by doftorul** [comment]
![image](https://user-images.githubusercontent.com/848034/77311763-2d037500-6d1a-11ea-8313-da28a745fc79.png)

These are my versions.
I tried again to replicate just now on another VPS - using vultr - and it had the same issue.

Did it on Digital Ocean - The issue didn't manifest itself.

However, the initial fix, manually adding the "AllowSupplementaryGroups true" to the end of clamd.conf seems to be fixing the issue

**Comment by bcsanford** [comment]
installer used: Yes
OS: Ubuntu 20.04.1 LTS
Webserver: Nginx
Hosted: Digital Ocean

**Previously Suggested Fix Ignored @ runtime**

Jan 05 20:09:58 mail.domain.com clamd[1369010]: WARNING: Ignoring deprecated option AllowSupplementaryGroups at /etc/clamav/clamd.conf:88


### **Current behavior**

root@mail:~# systemctl status clamav-daemon.service
● clamav-daemon.service - Clam AntiVirus userspace daemon
     Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/clamav-daemon.service.d
             └─extend.conf
     Active: active (running) since Tue 2021-01-05 19:50:18 EST; 1min 11s ago
       Docs: man:clamd(8)
             man:clamd.conf(5)
             https://www.clamav.net/documents/
    Process: 1348708 ExecStartPre=/bin/mkdir -p /run/clamav (code=exited, status=0/SUCCESS)
    Process: 1348717 ExecStartPre=/bin/chown clamav /run/clamav (code=exited, status=0/SUCCESS)
   Main PID: 1348718 (clamd)
      Tasks: 2 (limit: 2344)
     Memory: 606.0M
     CGroup: /system.slice/clamav-daemon.service
             └─1348718 [clamd]

Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> Portable Executable support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> ELF support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> Mail files support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> OLE2 support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> PDF support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> SWF support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> HTML support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> XMLDOCS support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> HWP3 support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> Self checking every 3600 seconds.
root@mail:~# systemctl status clamav-daemon.service
● clamav-daemon.service - Clam AntiVirus userspace daemon
     Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/clamav-daemon.service.d
             └─extend.conf
     Active: failed (Result: signal) since Tue 2021-01-05 19:51:30 EST; 1s ago
       Docs: man:clamd(8)
             man:clamd.conf(5)
             https://www.clamav.net/documents/
    Process: 1348708 ExecStartPre=/bin/mkdir -p /run/clamav (code=exited, status=0/SUCCESS)
    Process: 1348717 ExecStartPre=/bin/chown clamav /run/clamav (code=exited, status=0/SUCCESS)
    Process: 1348718 ExecStart=/usr/sbin/clamd --foreground=true (code=killed, signal=KILL)
   Main PID: 1348718 (code=killed, signal=KILL)

Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> Mail files support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> OLE2 support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> PDF support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> SWF support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> HTML support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> XMLDOCS support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> HWP3 support enabled.
Jan 05 19:50:52 mail.domain.com clamd[1348718]: Tue Jan  5 19:50:52 2021 -> Self checking every 3600 seconds.
Jan 05 19:51:30 mail.domain.com systemd[1]: clamav-daemon.service: Main process exited, code=killed, status=9/KILL
Jan 05 19:51:30 mail.domain.com systemd[1]: clamav-daemon.service: Failed with result 'signal'.


**from mail.log**
Jan  6 00:43:53 mail postfix/submission/smtpd[1342029]: Anonymous TLS connection established from blah[blah]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Jan  6 00:43:53 mail postfix/submission/smtpd[1342029]: NOQUEUE: client=blah[blah], sasl_method=PLAIN, sasl_username=user@domain.com
Jan  6 00:43:54 mail amavis[683357]: (683357-06) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl:Connection refused
Jan  6 00:43:55 mail amavis[683357]: (683357-06) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl:Connection refused
Jan  6 00:43:55 mail amavis[683357]: (683357-06) (!)ClamAV-clamd: All attempts (1) failed connecting to /var/run/clamav/clamd.ctl, retrying (2)
Jan  6 00:44:01 mail amavis[683357]: (683357-06) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl:Connection refused
Jan  6 00:44:01 mail amavis[683357]: (683357-06) (!)ClamAV-clamd av-scanner FAILED: run_av error: Too many retries to talk to /var/run/clamav/clamd.ctl (All attempts (1) failed connecting to /var/run/clamav/clamd.ctl) at (eval 114) line 659.\n
Jan  6 00:44:01 mail amavis[683357]: (683357-06) (!)WARN: all primary virus scanners failed, considering backups





![image](https://user-images.githubusercontent.com/185097/103716519-47e56400-4f91-11eb-9309-624ebe9e8bd4.png)

**Comment by bcsanford** [comment]
@kryskool @tonioo @doftorul

As mentioned before

installer used: Yes
OS: Ubuntu 20.04.1 LTS
Webserver: Nginx
Hosted: Digital Ocean

now realize relevant but not mentioned at the time
2GB RAM

the following error:
`ERROR: Failed to change socket ownership to group clamav`
will cause:
`(!)connect to /var/run/clamav/clamd.ctl failed`

this should be troubleshooted as Insufficient Memory
--
this error is the same as
https://github.com/modoboa/modoboa/issues/1775
