### ISSUE TITLE
Upgrade error - Modobao interface error

### ISSUE THREAD

**Issue by btafoya** [modoboa/modoboa-installer#315]
# Impacted versions
Latest GIT pull.

* Distribution: Ubuntu 18.04 LTS
* Arch: 64
* Database: PostgreSQL

# Steps to reproduce

./run.py --upgrade {domain}

# Full trace using --debug option or current behaviour

502 Bad Gateway

`
Current thread 0x00007fc8b183d5c0 (most recent call first):
Mon May 11 22:11:08 2020 - *** Starting uWSGI 2.0.15-debian (64bit) on [Mon May 11 22:11:07 2020] ***
Mon May 11 22:11:08 2020 - compiled with version: 7.3.0 on 28 September 2018 15:41:15
Mon May 11 22:11:08 2020 - os: Linux-4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020
Mon May 11 22:11:08 2020 - nodename: {domain}
Mon May 11 22:11:08 2020 - machine: x86_64
Mon May 11 22:11:08 2020 - clock source: unix
Mon May 11 22:11:08 2020 - pcre jit disabled
Mon May 11 22:11:08 2020 - detected number of CPU cores: 1
Mon May 11 22:11:08 2020 - current working directory: /
Mon May 11 22:11:08 2020 - writing pidfile to /run/uwsgi/app/modoboa_instance/pid
Mon May 11 22:11:08 2020 - detected binary path: /usr/bin/uwsgi-core
Mon May 11 22:11:08 2020 - dropping root privileges as early as possible
Mon May 11 22:11:08 2020 - setgid() to 1000
Mon May 11 22:11:08 2020 - setuid() to 1000
Mon May 11 22:11:08 2020 - chdir() to /srv/modoboa/instance
Mon May 11 22:11:08 2020 - your processes number limit is 7782
Mon May 11 22:11:08 2020 - your memory page size is 4096 bytes
Mon May 11 22:11:08 2020 - detected max file descriptor number: 1024
Mon May 11 22:11:08 2020 - VirtualHosting mode enabled.
Mon May 11 22:11:08 2020 - lock engine: pthread robust mutexes
Mon May 11 22:11:08 2020 - thunder lock: disabled (you can enable it with --thunder-lock)
Mon May 11 22:11:08 2020 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/modoboa_instance/socket fd 3
Mon May 11 22:11:08 2020 - dropping root privileges after socket binding
Mon May 11 22:11:08 2020 - Python version: 3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0]
Mon May 11 22:11:08 2020 - Set PythonHome to /srv/modoboa/env
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

`

# Expected behavior

Functional web interface. :)

# Video/Screenshot link (optional)

Any help is greatly appreciated! The server is accepting mail, but I am unable to access the modoboa management interface.

**Comment by Master13011** [comment]
tuto :
cd /srv/modoboa
mv env env.bck

git clone https://github.com/modoboa/modoboa-installer
cd modoboa-installer
sudo ./run.py --upgrade

**Comment by btafoya** [comment]
Thank you, figured that out last night after I happened to come across the note about python 3.
