### ISSUE TITLE
DeprecationWarning: SafeConfigParser renamed to ConfigParser

### ISSUE THREAD

**Issue by jsayles** [modoboa/modoboa-installer#324]
# Impacted versions

* Distribution: Ubuntu 20.04 LTS
* Python: 3.8.2
* Arch: 64 Bit
* Database: PostgreSQL

# Steps to reproduce
- Run the install.
- See Deprecation Warnings

`
run.py:82: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  config = configparser.SafeConfigParser()
run.py:84: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(fp)
`

**Comment by tonioo** [comment]
https://github.com/modoboa/modoboa-installer/commit/1fa390513dbcba4c355458e5e6a9f17f64e409de
