### ISSUE TITLE
Feature Request: Add prosody XMPP server

### ISSUE THREAD

**Issue by neonknight** [modoboa/modoboa-installer#331]
It would be great if an XMPP chatserver such as prosody could be installed and set up with a reasonable default configuration using modoboa-installer.

I suggest prosody as it is lean, easy to install and provides plugins which allow authentication against dovecot (either dovecot auth or plain imap), thus allowing seamless integration into the existing user base. A user can then use the chat functionality with his standard email address as user name and his usual email password.

Additionally, more future functions could be added, such as mail notification.

**Comment by tsabi** [comment]
Chatting is different kind of service than mail servicing. Than why not a mattermost? It's much better than a simple xmpp server.
