### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by marcoceppi** [modoboa/modoboa-installer#336]
# Impacted versions

* Modoboa: latest
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

Create a fresh Ubuntu 20.04 instance - which comes with Python 3.8 installed and Python 2.7 in the archive.

Installer fails because of changes to `platform`. Install Python 3.7 via deadsnakes ppa

Setup fails to perform letsencrypt and other packages setup - likely due to `$HOME/env` being setup with `python3` (Python 3.8) and not allowing to pass a python path or supporting Python 3.8 in totality.

**Comment by tonioo** [comment]
Fixed by https://github.com/modoboa/modoboa-installer/commit/1fa390513dbcba4c355458e5e6a9f17f64e409de
