### ISSUE TITLE
Modoboa on Ubuntu 20.04 throws errors for Let's Encrypt + Dovecot!

### ISSUE THREAD

**Issue by PontusTideman** [modoboa/modoboa-installer#338]
# Impacted versions

* Modoboa: 1.15.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Either do an upgrade from 18.04 -> 20.04 or a clean version of 20.04 LTS. Do a `./run.py --stop-after-configfile-check example.com` and edit the .cfg to use Let's Encrypt for certificate. Run the installer again, and Nginx refuse to start because the certifcate can't be found.

# Current behavior
`/lib/systemd/system/dovecot.service:19: PIDFile= references a path below legacy directory /var/run/, updating /var/run/dovecot/master.pid → /run/dovecot/master.pid; >`

`nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/mail.domain.TLD/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No>`

Oh, and even though I have Python 3 installed, I was forced to install Python 2.7 for the installer to work!

# Expected behavior
Just work as it should!

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
I guess the best move here would be to replace certbot-auto by certbot.
