### ISSUE TITLE
UNABLE to switch to LDAP authentication

### ISSUE THREAD

**Issue by ptchek** [modoboa/modoboa-installer#339]
# Impacted versions

* Distribution:  Ubuntu 
* Codename:  Ubuntu 18.04.5 LTS Bionic
* Arch: 64 Bits
* Database:  MySQL

# Steps to reproduce

Install modoboa by pulling repo https://github.com/modoboa/modoboa-installer, then 'sudo ./run.py my.domain.com'

THEN install LDAP extension

apt-get install build-essential python3-dev python2.7-dev \
    libldap2-dev libsasl2-dev tox \
    lcov valgrind –y

sudo su - modoboa
bash
source env/bin/activate
pip install python-ldap django-auth-ldap

Switch to LDAP authetication by changing below config in 
/srv/modoboa/instance/instance/settings.py

AUTHENTICATION_BACKENDS = (
    'modoboa.lib.authbackends.LDAPBackend',
    # 'modoboa.lib.authbackends.SMTPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

Allow LDAP synchronization by adding in 
/usr/lib/python3/dist-packages/cloudinit/settings.py

MODOBOA_APPS = (
'modoboa',
'modoboa.core',
'modoboa.lib',
'modoboa.admin',
'modoboa.transport',
'modoboa.relaydomains',
'modoboa.limits',
'modoboa.parameters',
'modoboa.dnstools',
'modoboa.ldapsync',
)

then /etc/init.d/uwsgi restart

# Full trace using --debug option or current behaviour

In Modoboa control panel fill LDAP like on this image

![Modoboa control panel](https://user-images.githubusercontent.com/4922096/94341550-78207c80-000a-11eb-9481-51012c676c70.png)

Create an LDAP user in (OpenLDAP) like on this image

![LDAP user](https://user-images.githubusercontent.com/4922096/94341599-f41ac480-000a-11eb-9818-2d181007f907.png)

# Current behavior

Try to connect with email address

![Try to connect](https://user-images.githubusercontent.com/4922096/94341719-e7e33700-000b-11eb-9d8f-8f4978f3f1b3.png)

![Try to connect error](https://user-images.githubusercontent.com/4922096/94341731-034e4200-000c-11eb-9f26-37b1ed21addd.png)

Error on ldap server log

![LDAP Log](https://user-images.githubusercontent.com/4922096/94341803-bcad1780-000c-11eb-856f-e20a98726adf.png)

Try to connect with dn like i use to do with ldapmyadmin

cn=Pierre TCHEKOUTEU,ou=People,dc=cloudsas,dc=xyz

![Try to connect with dn](https://user-images.githubusercontent.com/4922096/94341753-3bee1b80-000c-11eb-9e62-e5366b0e0259.png)

the same error

Error on ldap server log

![error with dn](https://user-images.githubusercontent.com/4922096/94341810-c767ac80-000c-11eb-8282-978cb7bf0254.png)

# Expected behavior
ldap server seams to be aware of modoboa mail server
why connexion keep failling ?

Please your Help will be appreciate
Thanks

**Comment by tonioo** [comment]
You're user DN template field contains a wrong value. But looking at your LDAP structure, you won't be able to retrieve the DN from the user email directly. I suggest you switch to "Search&Bind" authentication.

**Comment by ptchek** [comment]
Hello

Thanks you for your Reply.
It was very Helpfull to moving forward

I'm encounting a news issue.
I can now connect to Dashboard with LDAP, but can't go to the Webmail TAB
maybe I've missed some parameters

**Here is how My MODOBOA LDAP Setting look like now**

![LDAP Setting MODOBOA](https://user-images.githubusercontent.com/4922096/94361661-5977bf80-00b6-11eb-84a6-6fbd3ff492ca.png)

**Try  to connect**

![LDAP connexion Modoboa](https://user-images.githubusercontent.com/4922096/94361674-70b6ad00-00b6-11eb-8b95-6dd4df815df0.png)

**and Hurrah, Connexion made (i'm very happy here, a hurge step forward)**

![LDAP Connexion Succeed modoboa](https://user-images.githubusercontent.com/4922096/94361730-d99e2500-00b6-11eb-9950-9ccf9327164f.png)

**Now let go to webmail**

![LDAP Mailbox Modoboa](https://user-images.githubusercontent.com/4922096/94361737-ef134f00-00b6-11eb-93ec-941795c7406d.png)

then authentication failed


![AUTHENTICATION FAILED](https://user-images.githubusercontent.com/4922096/94361757-136f2b80-00b7-11eb-9d36-09756f1831bd.png)

what am I missing please ?

Thank you very much

**Comment by ptchek** [comment]
after installing dovecot-ldap
uncomment line ldap in this file /etc/dovecot/conf.d/10-auth.conf

change file auth-ldap.conf.ext
to getting connection from etc/dovecot/dovecot-ldap.conf.ext
and here how my dovecot ldap looks like

dn = cn=admin,dc=cloudsas,dc=xyz
dnpass = xxxxxxx
auth_bind = no
base = ou=people,dc=cloudsas,dc=xyz
user_filter = (&(objectClass=posixAccount)(uid=%u))
pass_attrs = userPostfix=user,userPassword=password
pass_filter = (&(objectClass=posixAccount)(uid=%u))


I still can't connect

![dovecot failed](https://user-images.githubusercontent.com/4922096/94363910-d5c5cf00-00c5-11eb-8631-7ae7dbcf3ef7.png)

Sorry to distrub
any help will be appreciate

**Comment by ptchek** [comment]
Even if I've change my Modoboa LDAP Setting like  this.

![MODOBOA LDAP Setting 2](https://user-images.githubusercontent.com/4922096/94370450-5a2d4780-00f0-11eb-9c37-1996c37d76e4.png)

and my devecot-ldap file like this



hosts = ldap.cloudsas.xyz
dn = cn=admin,dc=cloudsas,dc=xyz
dnpass = ******************
auth_bind = yes
auth_bind_userdn = mail=%u,ou=People,dc=cloudsas,ou=xyz
ldap_version = 3
base = ou=people,dc=cloudsas,dc=xyz
user_attrs = homeDirectory=home
user_filter = (uid=%(user)s)
pass_attrs = userPostfix=user,userPassword=password
pass_filter = (&(objectClass=posixAccount)(uid=%u))

DOVECOT is trying using my email as cn 

![DEvecot is using my email](https://user-images.githubusercontent.com/4922096/94370526-d4f66280-00f0-11eb-9845-a149980f17a1.png)

Where can we change this behavior ?

Thanks

**Comment by tonioo** [comment]
@ptchek Are you sure your filter is correct? Looking at your example, maybe you should use the mail attribute instead of uid?
