### ISSUE TITLE
Make compatibility to ubuntu 20.04

### ISSUE THREAD

**Issue by florealcab** [modoboa/modoboa-installer#342]
# Impacted versions

* Distribution: Ubuntu
* Codename: focal (20.04)
* Arch: 64 Bits
* Database: PostgreSQL
# Steps to reproduce

Modoboa installer is not compatible with ubuntu 20.04, is it possible to make it compatible? I need to stick on 18.04 waiting for a fix

**Comment by tsabi** [comment]
It's compatible. Why you think it isn't? Please provide correct error report, nobody can fix the "not works" type of yields.

**Comment by tonioo** [comment]
@florealcab Indeed, I worked on fex weeks ago on the Ubuntu 20.04 compatibility but maybe I've missed something?

**Comment by florealcab** [comment]
Oh it's my fault, I used an old fork... seems to be okay with the new version (not tested, but changed I made are done here. Sorry. I close the ticket, so
