### ISSUE TITLE
Radicale Looks Like It Is Not Installed, and Causes a 500 error when using anything related to the contacts, or calendars.

### ISSUE THREAD

**Issue by vthg2themax** [modoboa/modoboa-installer#351]
# Impacted versions

* Distribution: Ubuntu 18.05 LTS
* Codename: 18.05 LTS
* Arch: 64 Bits
* Database: PostgreSQL 

# Steps to reproduce
Install using the installer.
# Full trace using --debug option or current behaviour
Current behavior is a 500 error when trying to do anything with the CalDav server. I tried systemctl status radicale, and it found nothing. I tried setting the debug = True in the settings.py file,but it made no difference which makes sense if the radicale part is not installed or working. I am not familiar with it, but would love to get it working. Please let me know what you need to make that happen.
# Expected behavior
I expect that I can create and access the contacts, and calendar.
# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
There was an issue with Radicale plugin. A new version has been released so it shoud now be fixed.
