### ISSUE TITLE
emails werden nichtr gesendet

### ISSUE THREAD

**Issue by HeXGamingDEV** [modoboa/modoboa-installer#352]
# Impacted versions

* Distribution: Debian / Ubuntu / Centos
* Arch:  64 Bits
* Database:  MySQL

# Steps to reproduce

hallo zusammen habe ein problem kann keine emails versenden da kommt immer der fehler in thunderbird

Fehler beim Senden der Nachricht: Der Mail-Server antwortete: 
451 4.3.5 <empfänger email>: Recipient address rejected: Server configuration problem.
 Bitte überprüfen Sie die E-Mail-Adresse des Empfängers "empfänger email" und wiederholen Sie den Vorgang.

weiß nicht weiter
habe installer benutzt

**Comment by kryskool** [comment]
HI @HeXGamingDEV 

In english please
