### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by GoldenretriverYT** [modoboa/modoboa-installer#353]
# Impacted versions

* Distribution: Debian
* Codename: Stretch
* Arch: 64 Bits
* Database: MySQL

# Steps to reproduce
Run installer
# Full trace using --debug option or current behaviour
Hit:1 https://mirror.klaus-uwe.me/mariadb/repo/10.5/debian stretch InRelease
Ign:2 https://repo.mongodb.org/apt/debian stretch/mongodb-org/4.2 InRelease
Hit:3 https://repo.mongodb.org/apt/debian stretch/mongodb-org/4.2 Release
Hit:5 https://repo.pritunl.com/stable/apt stretch InRelease
Get:6 https://dlm.mariadb.com/repo/maxscale/latest/debian stretch InRelease [3516 B]
Hit:7 http://ftp.debian.org/debian stretch-backports InRelease
Hit:8 https://downloads.mariadb.com/MariaDB/mariadb-10.5/repo/debian stretch InRelease
Ign:10 http://ftp.us.debian.org/debian stretch InRelease
Hit:9 https://downloads.mariadb.com/Tools/debian stretch InRelease
Hit:11 http://ftp.us.debian.org/debian stretch-updates InRelease
Hit:12 http://ftp.us.debian.org/debian stretch Release
Ign:14 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy InRelease
Ign:15 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy Release
Ign:16 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main all Packages
Ign:17 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main amd64 Packages
Ign:18 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main Translation-en
Ign:16 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main all Packages
Ign:17 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main amd64 Packages
Ign:18 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main Translation-en
Ign:16 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main all Packages
Ign:17 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main amd64 Packages
Ign:18 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main Translation-en
Ign:16 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main all Packages
Ign:17 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main amd64 Packages
Ign:18 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main Translation-en
Ign:16 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main all Packages
Ign:17 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main amd64 Packages
Ign:18 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main Translation-en
Ign:16 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main all Packages
Err:17 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main amd64 Packages
  404  Not Found [IP: 91.189.95.83 80]
Ign:18 http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy/main Translation-en
Hit:19 http://security.debian.org stretch/updates InRelease
Fetched 3516 B in 15s (231 B/s)
Reading package lists...
W: The repository 'http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu groovy Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu/dists/groovy/main/binary-amd64/Packages  404  Not Found [IP: 91.189.95.83 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
sudo is already the newest version (1.8.19p1-2.1+deb9u2).
wget is already the newest version (1.18-5+deb9u3).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Generating new certificate using letsencrypt
Reading package lists...
Building dependency tree...
Reading state information...
certbot is already the newest version (0.28.0-1~deb9u2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for mail.goldenretriverstudios.eu
Cleaning up challenges
Problem binding to port 80: Could not bind to IPv4 or IPv6.
Can't open /etc/letsencrypt/renewal/mail.goldenretriverstudios.eu.conf: No such file or directory.
Installing modoboa
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.3).
cron is already the newest version (3.0pl1-128+deb9u1).
libffi-dev is already the newest version (3.2.1-6).
libxslt1-dev is already the newest version (1.1.29-2.1+deb9u2).
libssl-dev is already the newest version (1.1.0l-1~deb9u1).
python3-dev is already the newest version (3.5.3-1).
redis-server is already the newest version (3:3.2.6-3+deb9u3).
librrd-dev is already the newest version (1.6.0-1+b2).
rrdtool is already the newest version (1.6.0-1+b2).
supervisor is already the newest version (3.3.1-1+deb9u1).
libjpeg-dev is already the newest version (1:1.5.1-2+deb9u1).
libxml2-dev is already the newest version (2.9.4+dfsg1-2.2+deb9u3).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
User modoboa already exists, skipping creation but please make sure the /srv/modoboa directory exists.
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'modoboa'@'%'
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'modoboa'@'localhost'
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting modoboa
  Using cached modoboa-1.17.0.tar.gz (8.3 MB)
Collecting django<2.3,>=2.2
  Using cached Django-2.2.17.tar.gz (8.9 MB)
Collecting django-braces==1.14.0
  Using cached django-braces-1.14.0.tar.gz (48 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /srv/modoboa/env/bin/python3 /srv/modoboa/env/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpz61smszj
       cwd: /tmp/pip-install-y3kfcp8n/django-braces
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/srv/modoboa/env/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/srv/modoboa/env/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/srv/modoboa/env/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-0140y2ok/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-0140y2ok/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-0140y2ok/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      import braces
  ImportError: No module named 'braces'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /srv/modoboa/env/bin/python3 /srv/modoboa/env/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpz61smszj Check the logs for full command output.
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting rrdtool
  Using cached rrdtool-0.1.15.tar.gz (21 kB)
Collecting modoboa-pdfcredentials
  Using cached modoboa_pdfcredentials-1.4.0-py2.py3-none-any.whl (70 kB)
Collecting modoboa-postfix-autoreply
  Using cached modoboa_postfix_autoreply-1.6.0-py2.py3-none-any.whl (86 kB)
Collecting modoboa-sievefilters
  Using cached modoboa_sievefilters-1.5.0-py2.py3-none-any.whl (122 kB)
Collecting modoboa-webmail
  Using cached modoboa_webmail-1.6.0-py2.py3-none-any.whl (198 kB)
Collecting modoboa-contacts
  Using cached modoboa_contacts-0.8.1-py2.py3-none-any.whl (710 kB)
Collecting modoboa-radicale
  Using cached modoboa_radicale-1.5.0-py2.py3-none-any.whl (1.7 MB)
Collecting mysqlclient
  Using cached mysqlclient-2.0.1.tar.gz (87 kB)
    ERROR: Command errored out with exit status 1:
     command: /srv/modoboa/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1zctwfk7/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1zctwfk7/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xf4sfpts
         cwd: /tmp/pip-install-1zctwfk7/mysqlclient/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1zctwfk7/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-1zctwfk7/mysqlclient/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-1zctwfk7/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
bash: modoboa-admin.py: command not found
# Expected behavior
Should install modoboa

**Comment by tonioo** [comment]
@GoldenretriverYT Are you trying to install modoboa on a running server? What is your distribution? You indicate Debian stretch but I see references to Ubuntu repositories in your logs...
