### ISSUE TITLE
Errors during installation causing calendars to not work. 

### ISSUE THREAD

**Issue by ghost** [modoboa/modoboa-installer#354]
# Impacted versions

* Distribution: Debian / Ubuntu
* Codename: Debian 9 / Debian 10 / Ubuntu 18.04 LTS / Ubuntu 20.04 LTS
* Arch: 64 Bits
* Database: MySQL

# Steps to reproduce

Run the modoboa installer in interactive and debug mode on freshly installed linux systems with no other software.  You will see the errors in the output.  

The installation will complete and modoboa works for the most part except calendars do not display in the web gui.  It seems like I am able to create calendars but they also will not display. it's a white page.  No error messages in the web gui.  I've reinstalled maybe 20 times and have tried various versions of both Ubuntu and Debian but get the same result.  I'm not sure what has changed with modoboa in the last several months but what used to work now doesn't.  Please investigate this and provide a fix.  

# Full trace using --debug option or current behaviour

Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /srv/modoboa/env/bin/python3 /srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp1a8b8a15
       cwd: /tmp/pip-install-ediyhhaa/django-braces
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-2jzvjhlr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-2jzvjhlr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-2jzvjhlr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      import braces
  ModuleNotFoundError: No module named 'braces'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /srv/modoboa/env/bin/python3 /srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp1a8b8a15 Check the logs for full command output.

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

modoboa-radicale 1.5.0 requires caldav==0.7.1, but you'll have caldav 0.6.2 which is incompatible.
modoboa-radicale 1.5.0 requires django-filter==2.4.0, but you'll have django-filter 2.2.0 which is incompatible.

# Expected behavior

modoboa should install without errors and all features functional as it has in the past.  

# Video/Screenshot link (optional)

**Comment by rlconsulting** [comment]
Looking further into this.  It appears that the module django_braces is not installed with the installer.  I decided to try and install it using pip3 install django_braces then rerun the modoboa installer.  Calendars are now working.

**Comment by rlconsulting** [comment]
Update: I'm still unable to create shared calendars or events. The option doesn't show up under the calendars tab when creating a new calendar. CalDAV and CardDAV still appear to not be working.  When I try to access contacts URL. I get an error in my browser that says The Requested Resource could not be found.  Can someone help me figure this out.  The rest of modoboa appears to be working as normal and I am able to send/receive email.  Thank You
