### ISSUE TITLE
Installer completes, 502 Bad Gateway - unix:/run/uwsgi/app/modoboa_instance/socket failed (13: Permission denied)

### ISSUE THREAD

**Issue by XenonFiber** [modoboa/modoboa-installer#356]
# Impacted versions
Latest @ 12/19/20

* Distribution: Ubuntu (Server)
* Codename: Bionic Beaver
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
Run 'sudo python3 ./run.py slime.server.xenonfiber.space --debug'
Install completes
Browser gets 504
Nginx error log says, '2020/12/19 07:58:38 [crit] 4107#4107: *263 connect() to unix:/run/uwsgi/app/modoboa_instance/socket failed (13: Permission denied) while connecting to upstream, client: [my ip], server: mail.[fqdn], request: "GET / HTTP/2.0", upstream: "uwsgi://unix:/run/uwsgi/app/modoboa_instance/socket:", host: "mail.[fqdn]"'

The output can vary depending on what's been done, but it's always roughly the same, and results in the same outcome. There is nothing out of the ordinary, besides the effects of running the install script more than once.

# Full trace using --debug option or current behaviour
The databases, users, and directory already exist. I've checked to make sure that this was the case. It's just a 504 with an error.

This process is being done on an existing production server. I use Nginx and PostgreSQL.

# Expected behavior
Login page

**Comment by tonioo** [comment]
@XenonFiber Can you check if uwsgi is running?

**Comment by kgnfth** [comment]
@Toniob yes its running

**Comment by kgnfth** [comment]
Bump

**Comment by tonioo** [comment]
@kgnfth Can you check permissions on this file: /run/uwsgi/app/modoboa_instance/socket

**Comment by kgnfth** [comment]
@tonioo 
My Python version 3.9.5


❯ `ls -la /run/uwsgi/app/modoboa_instance`
```
drwxr-xr-x 2 modoboa  modoboa 80 Jul  1 19:03 .
drwxr-xr-x 4 root     root    80 Jul  1 19:03 ..
-rw-r--r-- 1 root     root     7 Jul  1 19:03 pid
srw-rw---- 1 www-data root     0 Jul  1 19:03 socket
```

also i have this error

❯ `sudo tail -f /var/log/uwsgi/app/modoboa_instance.log`
```
  File "/srv/modoboa/env/lib/python3.9/site-packages/modoboa/urls.py", line 16, in <module>
    from modoboa.core import signals as core_signals, views as core_views
  File "/srv/modoboa/env/lib/python3.9/site-packages/modoboa/core/views/__init__.py", line 12, in <module>
    from .dashboard import DashboardView
  File "/srv/modoboa/env/lib/python3.9/site-packages/modoboa/core/views/dashboard.py", line 3, in <module>
    import feedparser
  File "/srv/modoboa/env/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
```

feedparser using base64.decodestrings which was deprecated and now removed in python 3.9

See: 
https://github.com/kurtmckee/feedparser/pull/206
https://github.com/kurtmckee/feedparser/issues/201

**Comment by kgnfth** [comment]
Just to see if it would work i ran

(env) modoboa@mail:~$ `pip install --upgrade --force-reinstall feedparser==6.0.8`

but now i get 
![image](https://user-images.githubusercontent.com/73314940/124166718-0de4ae80-da58-11eb-8e11-cab5f8a4fc3c.png)

**Comment by kgnfth** [comment]
Running in debug mode, i see this error

![image](https://user-images.githubusercontent.com/73314940/124167705-1e495900-da59-11eb-87e7-c637c84b60ad.png)

should i use ubuntu 20.04 or other ??

**Comment by kgnfth** [comment]
oke i have installed it successfully on Ubuntu 20.04

**Comment by tonioo** [comment]
@kgnfth Modoboa is not compatible with python 3.9 yet
