### ISSUE TITLE
Can't login to web interface 1.5.2, 14.04, clean install, no data in MySQL

### ISSUE THREAD

**Issue by WhereIsPedro** [modoboa/modoboa-installer#36]
**Can't login into modoboa. **

New installation 1.5.2 based on Ubuntu 14.04 LTS and I can't not log in to the administrative panel

> Congratulations! You can enjoy Modoboa at https://*******(admin:password)

**web:**

> Your username and password didn't match. Please try again.

**SQL:**

`mysql> use modoboa;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+-----------------------------------+
| Tables_in_modoboa                 |
+-----------------------------------+
| admin_alias                       |
| admin_domain                      |
| admin_domainalias                 |
| admin_mailbox                     |
| admin_mailboxoperation            |
| admin_objectdates                 |
| admin_quota                       |
| auth_group                        |
| auth_group_permissions            |
| auth_permission                   |
| authtoken_token                   |
| core_log                          |
| core_objectaccess                 |
| core_user                         |
| core_user_groups                  |
| core_user_user_permissions        |
| django_content_type               |
| django_migrations                 |
| django_session                    |
| django_site                       |
| lib_parameter                     |
| lib_userparameter                 |
| limits_domainobjectlimit          |
| limits_userobjectlimit            |
| modoboa_admin_aliasrecipient      |
| postfix_autoreply_arhistoric      |
| postfix_autoreply_armessage       |
| postfix_autoreply_transport       |
| postfix_relay_domains_relaydomain |
| postfix_relay_domains_service     |
| reversion_revision                |
| reversion_version                 |
+-----------------------------------+
32 rows in set (0.00 sec)`

`mysql> SELECT * from admin_domain;
Empty set (0.01 sec)

mysql> SELECT * from core_user;   
Empty set (0.00 sec)

mysql> SELECT * from admin_quota;
Empty set (0.00 sec)

mysql> SELECT * from reversion_version;
Empty set (0.00 sec)

mysql> SELECT * from reversion_revision;
Empty set (0.00 sec)`

**Comment by almereyda** [comment]
For me manually creating the superuser with `createsuperuser` instead of `changepassword` as in https://github.com/modoboa/modoboa-installer/issues/28#issuecomment-208497375 helped.

**Comment by almereyda** [comment]
I can now confirm the same empty tables.
Login errors are anyway logged in `core_log`.

```
mysql> select * from core_log;
+----+---------------------+--------------------------------------------------------------+---------+--------------+
| id | date_created        | message                                                      | level   | logger       |
+----+---------------------+--------------------------------------------------------------+---------+--------------+
|  1 | 2016-05-10 14:08:55 | Failed connection attempt from '0.0.0.0' as user 'admin' | WARNING | modoboa.auth |
+----+---------------------+--------------------------------------------------------------+---------+--------------+
1 row in set (0.00 sec)
```

**Comment by tonioo** [comment]
Actually, there is some kind of race condition here. The plugin works like this:
* It is configured to store documents in /var/lib/modoboa/pdf_credentials by default
* It generates a new document each time a new account is created
* Before saving the document, it checks if the configured directory exists and creates it using mkdir if it doesn't

The installer changes the storage directory to /srv/modoboa/pdf_credentials but AFTER the deploy. Unfortunately, the deployment process creates an initial user (admin) so the the plugin tries to create a document but mkdir fails since /var/lib/modoboa does not exist (and we don't want it to exist)

A quickfix is to disable modoboa_pdf_credentials from the installed extensions (like you did) before starting the installer.
