### ISSUE TITLE
Modoboa issue while installing

### ISSUE THREAD

**Issue by similarSurrounding** [modoboa/modoboa-installer#362]
# Impacted versions

* Distribution:Ubuntu 16.04 LTS

I wanted to set up an email-server, so i startet doing it with a tutorial.
I set up the dns records, took a plain Ubuntu 16.04 server and everything worked fine.
Then i startet the installation skrypt via ./run.py --interactive ***************.com, confirmed with y and this happened

# Video/Screenshot link (optional)
![Unbenannt](https://user-images.githubusercontent.com/77742088/105201718-78a4cc00-5b41-11eb-9810-3dac9f3198fc.PNG)

**Comment by kryskool** [comment]
Hi @similarSurrounding 

Cans you launch the installer with --interactive and --debug arguments ?

Regards,
