### ISSUE TITLE
Default password scheme only show "plain"

### ISSUE THREAD

**Issue by tsumi** [modoboa/modoboa-installer#364]
# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
- setup a basic centos installation
- install modoboa trough installer https://modoboa.readthedocs.io/en/latest/installation.html#recommended-way

# Current behavior
modoboa > parameters > Default password scheme only show "plain" no crypt methods are available

# Expected behavior
I should able to chose SHA512-CRYPT etc

# Video/Screenshot link (optional)

https://imgur.com/j9AWgda

**Comment by fpiccinali** [comment]
For ubuntu 20.04

apt install python3-crypto
