### ISSUE TITLE
ubuntu 20.04 with mysql installed modoboa-installer fails at modoboa dependencies

### ISSUE THREAD

**Issue by atiteam** [modoboa/modoboa-installer#365]
Collecting modoboa
  Using cached modoboa-1.17.0.tar.gz (8.3 MB)
Collecting django<2.3,>=2.2
  Using cached Django-2.2.17.tar.gz (8.9 MB)
Collecting django-braces==1.14.0
  Using cached django-braces-1.14.0.tar.gz (48 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /srv/modoboa/env/bin/python3 /srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp7n90tsk1
       cwd: /tmp/pip-install-ose85an5/django-braces_7b9f66d4ef0e447e818949fe4429b99d
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-b_zk8bym/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-b_zk8bym/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-b_zk8bym/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      import braces
  ModuleNotFoundError: No module named 'braces'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e5/c3/4e3c4296ce085ad570278aa8cc4b7958553bff9ef8f1f2abb93ebd303cbe/django-braces-1.14.0.tar.gz#sha256=83705b78948de00804bfacf40c315d001bb39630f35bbdd8588211c2d5b4d43f (from https://pypi.org/simple/django-braces/). Command errored out with exit status 1: /srv/modoboa/env/bin/python3 /srv/modoboa/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp7n90tsk1 Check the logs for full command output.
Collecting modoboa
  Using cached modoboa-1.16.1.tar.gz (8.3 MB)
  Using cached modoboa-1.16.0.tar.gz (8.3 MB)
  Using cached modoboa-1.15.0.tar.gz (8.2 MB)
  Using cached modoboa-1.14.0.tar.gz (6.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /srv/modoboa/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ose85an5/modoboa_cd64314516d949099c900e616e854b0c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ose85an5/modoboa_cd64314516d949099c900e616e854b0c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-m0tieuht
         cwd: /tmp/pip-install-ose85an5/modoboa_cd64314

# Impacted versions

* Distribution: Debian / Ubuntu / Centos
* Codename: Jessie / Trusty / Centos 7 / ...
* Arch: 32 Bits / 64 Bits
* Database: PostgreSQL / MySQL

# Steps to reproduce

# Full trace using --debug option or current behaviour

# Expected behavior

# Video/Screenshot link (optional)

**Comment by t-jones14** [comment]
Any update on this? Running into same issue.

**Comment by ScionOfDesign** [comment]
I ran into the same issue at #379 .
