### ISSUE TITLE
modoboa-installer with manual apache installation preferred?

### ISSUE THREAD

**Issue by samweisgamdschie** [modoboa/modoboa-installer#367]
# Impacted versions

* Distribution: Debian10
* Arch: 64 Bits

# Steps to reproduce

    ./run.py mydomain.org 

with installer.cfg:

    [nginx]
    enabled = false

Afterwards installing apache using:

    apt install apache2

configuring apache2 manually.

# Question
This is more a question than a bug description...

 1. If I want to install and upgrade modoboa but need to use apache, is the above way the way to go?
2. Will the system stay valid if I disable nginx this way?
3. Or is it saver to install nginx, reconfigure it to another port and install and configure afterwards to proxy traffic to nginx? (I guess not, but just completeness)

**Comment by samweisgamdschie** [comment]
Any suggestions for us?

**Comment by ByteSizedMarius** [comment]
I have figured out a way to do it the way you described, but I can not get automx to work properly. Otherwise it seems to work, but I also didn't really have the time to test everything properly yet. You can also disable [uwsgi], because if you look in the [manual installation](https://modoboa.readthedocs.io/en/latest/manual_installation/webserver.html), mod_wsgi is being used instead. 

As I cannot get automx to work myself with apache right now, I'm going to be rather cautious in giving others advice though ;)

**Comment by samweisgamdschie** [comment]
Hey @ByteSizedMarius, funny to hear from you. Actually we are going to set modoboa to production right now and run in pretty similar problems about non-working automx. Have you a tip for an apache admin, how to setup automx correctly?

**Comment by ByteSizedMarius** [comment]
Yes, but I cannot guarantee that this is stylistically correct and/or the correct way to do this. But it works for me on deb10
Here is my automx-vhost:

```
<VirtualHost *:80>
	ServerName autoconfig.example.com
	ServerAdmin admin@example.com
	DocumentRoot /srv/automx/instance

	WSGIScriptAlias /mail/config-v1.1.xml /srv/automx/instance/automx_wsgi.py
	WSGIDaemonProcess autoconf.example.com python-path=/srv/automx/instance:/srv/automx/env/lib/python3.7/site-packages
	WSGIProcessGroup autoconf.example.com
	WSGIPassAuthorization On

	<Directory "/srv/automx/instance/automx_wsgi.py">
		Require all granted
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

<VirtualHost *:443>
	ServerName autodiscover.example.com:443
	ServerAdmin admin@example.com
	DocumentRoot /srv/automx/instance
	
	WSGIDaemonProcess autodisc.example.com python-path=/srv/automx/instance:/srv/automx/env/lib/python3.7/site-packages
	WSGIProcessGroup autodisc.example.com	
	
	# Will not work if in vir-env: ImportError: Interpreter change detected - this module can only be loaded into one interpreter per process.
	#WSGIScriptAlias /autodiscover/autodiscover.xml /srv/automx/instance/automx_wsgi.py
	#WSGIScriptAlias /mobileconfig /srv/automx/instance/automx_wsgi.py
	
	# Instead, this is my solution (less nice):
	WSGIScriptAlias / /srv/automx/instance/automx_wsgi.py	
	
	# Not sure if this is needed here
	WSGIPassAuthorization On

	<Directory "/srv/automx">
		Require all granted
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

	Include /etc/letsencrypt/options-ssl-apache.conf
	SSLCertificateFile /etc/letsencrypt/live/autodiscover.example.com/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/autodiscover.example.com/privkey.pem
</VirtualHost>

```

You can test it by manually activating the env 
`source /srv/automx/env/bin/activate`
and then 
`/srv/automx/env/bin/automx-test existingMail@example.com`
Everything should come out as `200 OK`

**Comment by samweisgamdschie** [comment]
Hi @ByteSizedMarius, thank you for your apache config example! I had time today to test it out and optimise it according to let's say best-practise apache config (although I am not that familiar with the WSGI stuff). Here is what I will use for now:

```
<VirtualHost *:80>
    ServerName SGWVwiNTc3JUGRAP 
    ServerAlias autodiscover.* autoconfig.*

    DocumentRoot /srv/automx/instance

    WSGIScriptAlias /mail/config-v1.1.xml /srv/automx/instance/automx_wsgi.py
    WSGIDaemonProcess autodisco python-path=/srv/automx/instance:/srv/automx/env/lib/python3.7/site-packages
    WSGIProcessGroup autodisco

    <Files "automx_wsgi.py">
        Require all granted
    </Files>

    ErrorLog ${APACHE_LOG_DIR}/autoconfig_error.log
    CustomLog ${APACHE_LOG_DIR}/autoconfig_access.log combined
</VirtualHost>
```
This is for `http://`. It works with thunderbird that way. I have not tried to implement `https://` if it is not necessary because of the certificate mess. The certificate stuff will be done at the very end ;) . **Important hint**: you can change the `ServerName` directive, but do **_NOT_** remove it entirely because otherwise apache will try to use it's own hostname/etc. with this `<VirtualHost>` config (see https://httpd.apache.org/docs/current/mod/core.html#servername). But maybe you have a better idea here.

Another thing, I have tested the line

`WSGIScriptAlias / /srv/automx/instance/automx_wsgi.py`

at least with `http://` and it does not worked for me. Does it really work with `https://` (means, do the MUAs use another path than /mail/config-v1.1.xml with https:// in your setup)? https://gitlab.com/automx/automx2/-/blob/master/doc/automx2.adoc#autoconfig says different things, and

**Comment by ByteSizedMarius** [comment]
modoboa ships with automx, not automx2. I'm not an expert in any way, everything I know I gathered from docs or forums. As per [automx's installation-doc](https://github.com/sys4/automx/blob/master/INSTALL), autoconfig only uses http, autodiscover only uses https. The example-vhosts given in the doc do not work for me, more precisely the wsgiscriptaliases. My current configuration works for me, but I didn't yet test it with anything other than windows mail yet.
 
I agree the ssl-certs are pretty confusing and difficult to manage, as dovacot and postfix have their own configuration. I couldn't get the installer to create working letsencrypt-certs without having to install nginx, so I used certbot to replace the self-signed one. This means you have to reconfigure the previously mentioned modules.
