### ISSUE TITLE
Installer fails with Amavis is not installed

### ISSUE THREAD

**Issue by katsumag** [modoboa/modoboa-installer#369]
# Impacted versions

* Distribution: Centos
* Codename: Centos 7
* Arch: 64 Bits
* Database: PostgreSQL / MySQL

# Steps to reproduce

`python3 run.py <mydomain>` 

# Full trace using --debug option or current behaviour

https://bin.katsumag.me/silikubasa.txt

# Expected behavior

Installs modoboa

**Comment by kryskool** [comment]
Hi @katsumag 

It seem a problem with MySQL/Mariadb broken on Centos 7
