### ISSUE TITLE
New account creation fails at userdb lookup

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#37]
If I am creating a user, the interface tells me:

> Failed to retrieve mailbox location (userdb lookup: user name@domain.tld doesn't exist )

I understand the mailbox cannot be looked up, as it is yet to be created.
This used to work on a test instance only two weeks ago, plain debian without added packages.

The exception is raised in https://github.com/tonioo/modoboa/blob/master/modoboa/admin/models/mailbox.py#L149 but I am unable to reconstruct how this is called from the new mailbox dialogue.

**Comment by almereyda** [comment]
Switching from MySQL to PostgreSQL in the installer also didn't work.

**Comment by almereyda** [comment]
Currently investigating

* https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/files/dovecot/dovecot.conf.tpl
* https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/files/dovecot/dovecot-sql-postgres.conf.ext.tpl
* https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/files/dovecot/dovecot-dict-sql.conf.ext.tpl
* https://github.com/modoboa/modoboa-installer/tree/master/modoboa_installer/scripts/files/dovecot/conf.d
* https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/files/dovecot/conf.d/auth-sql.conf.ext
* https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/files/dovecot/conf.d/10-auth.conf

but not getting nowhere.

**Comment by tonioo** [comment]
@almereyda Thanks for your feedback.

I'll have some time tomorrow to take a look at it.

**Comment by almereyda** [comment]
@tonioo Thanks, I will be available during the day and will try another time to find out why it used to work in the past. Maybe debian upgraded some packages which break compatibility here?

**Comment by almereyda** [comment]
Okay, I am giving up for today, after three clean reinstalls with different settings (SQL engine, database password schemes), wondering a bit where the culprit could lie:

* Modoboa is successfully able to retrieve the user list when displaying the identities tab. Also login and changing passwords are possible, so it is most probably not the connection between Dovecot and its SQL backend. (Tested in both possible cases.)
* As I don't suppose the last commit in this repository can be blamed for the malfunction, the issue could derive from upstream: The recent version bump of modoboa to the 1.5 series in dependency of the django 1.9 series may have introduced small culprits which break the expected behaviour.

How can I provide more analytics of the case?
On @ecobytes' side it's kind of urgent, as we had chosen Modoboa as a mail hosting platform for a small ISP (and tested it against Mail-in-a-box, Mailcow, LEAP, Virtualmin and ISPConfig) and feel blocked in migration. Could I specify a desired Modoboa version within `installer.cfg` to generate more deterministic behaviour of the script?

**Comment by tonioo** [comment]
@almereyda Ok, I found the real issue: https://github.com/tonioo/modoboa/issues/875.
