### ISSUE TITLE
Debian 10 Buster unable to start the installation

### ISSUE THREAD

**Issue by dnigamer** [modoboa/modoboa-installer#372]
# Impacted versions

* Distribution: Debian
* Codename: Buster
* Arch: 64 Bits
* Kernel (if needed): 5.10.0-0.bpo.3-amd64

# Steps to reproduce
sudo python3 ./run.py

# Full trace using --debug option or current behaviour
```
Traceback (most recent call last):
  File "./run.py", line 13, in <module>
    from modoboa_installer import package
  File "/home/user/modoboa-installer/modoboa_installer/package.py", line 105, in <module>
    backend = get_backend()
  File "/home/user/modoboa-installer/modoboa_installer/package.py", line 101, in get_backend
    "Sorry, this distribution is not supported yet.")
NotImplementedError: Sorry, this distribution is not supported yet.
```

# Expected behavior
Start the installation i guess?

I have no idea why this is happening. This is a fresh debian install and i've cloned the repository just now, but it just doesn't want to start the installation.

**Comment by tonioo** [comment]
@dnigamer Are you sure this is a debian buster? Can you paste the result of this command please:
```
cat /etc/debian_version
``
Can you also check your python3 version please?

**Comment by aprbrown** [comment]
I am experiencing the same issue myself

`cat /etc/debian_version`
`10.8`

`python3 --version`
`Python 3.7.3`

**Comment by aprbrown** [comment]
A follow up on my scenario. My VM was the default Debian 10 "Buster" image on Microsoft Azure. I have just uninstalled all versions of python, along with any versions of postgres and related packages that I had installed when trying to manually configure Modoboa.

I restarted the vm and have installed python3 via apt, and now the installer is opening as expected.

**Comment by dnigamer** [comment]
I made a backup of all my data and reinstalled Debian 10 "Buster" aswell as all the required programs. 
The installer now could start just fine. 
The problem is solved for now.
