### ISSUE TITLE
Installer doesn't create certificate

### ISSUE THREAD

**Issue by Tobi696** [modoboa/modoboa-installer#377]
install.cfg:
```
[certificate]
generate = true
type = letsencrypt
```

After the installer is done, the nginx server doesn't start because the /etc/letsencrypt/live/... doesn't exist (No such file or directory).

When I run `certbot certificates`, It shows no certificates.
```
root@mail:/home/modoboa-installer# certbot certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
No certs found.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

**Comment by kryskool** [comment]
Hi @Tobi696 

Can you run the installer in debug mode, and send us the log ?

Regards,
