### ISSUE TITLE
Not install in ubuntu 20.04

### ISSUE THREAD

**Issue by craines** [modoboa/modoboa-installer#381]
# Impacted versions

* Distribution: Ubuntu 
* Codename: Focal
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
git clone https://github.com/modoboa/modoboa-installer
sudo python3 run.py rbsys.org --debug

![image](https://user-images.githubusercontent.com/10439940/125182727-dcea4380-e1e6-11eb-85a4-b3e40657ef3d.png)

**Comment by puneethkp8334** [comment]
Hi team ,i am also facing issues installer stuck on installing modoboa steps last 24hrs

**Comment by tonioo** [comment]
It should be fixed now.
