### ISSUE TITLE
Error after autoinstall on a clean mashine

### ISSUE THREAD

**Issue by MuffinAmor** [modoboa/modoboa-installer#383]
# Impacted versions

* Distribution: Debian
* Codename: Buster
* Database: PostgreSQL / MySQL 
^
^
^
idk where the autosetup saves their data

# Steps to reproduce
We have run the run.py script from the installations site https://modoboa.readthedocs.io/en/latest/installation.html
on a fresh installed server. 
The first thing, that we have done on this server was to install git and run the run.py script.
The installation throws no errors or warnings. 
![grafik](https://user-images.githubusercontent.com/55553342/129975864-4e931c8d-c340-4289-bfc4-ade8bb06f8ef.png)

We have an empty error log, but the site throws an internal error after trying to login with the default login data:
![grafik](https://user-images.githubusercontent.com/55553342/129975953-f855a3dc-7176-4d40-ac7e-d9dfa70a60bf.png)

What should we do now?
We have tried that multiple times now with the same output.

**Comment by solick** [comment]
same problem. Maybe we installed the beta version of Major version 2? The documentation describes, the installer will install the latest version by default but it is not clear if it is the latest stable version or the latest released version on GitHub.

**Comment by solick** [comment]
Found in the modoba issue tracker the solution: https://github.com/modoboa/modoboa/issues/2286#issuecomment-869730948

**Comment by tonioo** [comment]
The installer installs the latest stable version unless you use the --beta flag. Your issue should be fixed now.
