### ISSUE TITLE
Unsupported distribution in Debian with python 3.8

### ISSUE THREAD

**Issue by jahlives** [modoboa/modoboa-installer#385]
# Impacted versions

* Distribution: Debian 
* Python: 3.8

# Steps to reproduce
Just try to use installer on a debian (maybe other plattforms are affected as well) with Python >=3.8
`dist_info()` in `utils.py` uses this if present
```python
import distro
return distro.linux_distribution()
```
which returns something like `('Debian GNU/Linux', '11', 'bullseye')`. This leads to the fact that installer fails with "unsupported distribution"
Older versions of python return the expected distribution format `('debian', '10.10', '')`. The following change to `get_backend()` in `package.py`
```python
if distname in ["debian", "ubuntu", "debian gnu/linux"]:
        backend = DEBPackage
 ```
 solves the issue with python 3.8

**Comment by tonioo** [comment]
It should be fixed now
