### ISSUE TITLE
django-braces missing in virt env?

### ISSUE THREAD

**Issue by jahlives** [modoboa/modoboa-installer#386]
# Impacted versions

* Distribution: Debian
* Python 3.9

# Steps to reproduce
when running installer on a Debian 11 with python 3.9 the installer fails with an error that "braces" is missing. Short google tells me that it should be `django-braces`. Manually install the package via pip3 in virt env prior to calling the `run.py` solves the issue

**Comment by tonioo** [comment]
It should be fixed now.
