### ISSUE TITLE
debian 9 Internal Server Error

### ISSUE THREAD

**Issue by lultala** [modoboa/modoboa-installer#389]
I use auto install with command sudo python3 run.py <your domain>
all installed, but when i try enter to site i have error: Internal Server Error
I try install on ubuntu 20 (clear system) but install stoping on stage modoboa, i try start install with debug mode (screenshot)
![изображение](https://user-images.githubusercontent.com/52524303/132923593-f1f3262b-9c62-4d7f-a259-5f49b9ece7f8.png)
Can somebody help me pls)

**Comment by lultala** [comment]
after hours waiting stoping on this step
![изображение](https://user-images.githubusercontent.com/52524303/132925956-4a13ccf6-ce71-4f3d-a940-aff7288265f5.png)

**Comment by tonioo** [comment]
Debian 9 is not longer supported. I suggest you try on Debian 10

**Comment by lultala** [comment]
@tonioo i try on debian 10 , i have stoped on step "Downloading modoboa-webmail-1.1.4"

**Comment by tonioo** [comment]
@lultala Have you updated your installer local copy? (and you should also use the --beta flag with the installer)

**Comment by lultala** [comment]
I use:
> git clone https://github.com/modoboa/modoboa-installer
> cd modoboa-installer
> sudo ./run.py my_domain.ru

**Comment by lultala** [comment]
but i try on ubuntu 20.04 and have this error too
