### ISSUE TITLE
Install freeze during dovecot install (Ubuntu 14.04)

### ISSUE THREAD

**Issue by cthulhuely** [modoboa/modoboa-installer#4]
Hi I'm trying to make a quick setup on a fresh ubuntu, and the script seems to stop on `installing Dovecot`
(here's the output)
```shell
root@3015940:/home/modoboa-installer# ./run.py webmail.igotta.beer
Welcome to Modoboa installer!
Your mail server webmail.igotta.beer will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Installing modoboa
Installing uwsgi
Installing nginx
Installing postfix
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing dovecot
```
Then nothing for severals hours.
After some small verifications, Dovecot was not installed
Here's the installer.cfg (with obfusctated passwords)
```
[general]
tls_key_file = /etc/ssl/private/ssl-cert-snakeoil.key
tls_cert_file = /etc/ssl/certs/ssl-cert-snakeoil.pem

[database]
# Select database engine : postgres or mysql
#engine = postgres
engine = mysql
host = 127.0.0.1
install = true

[postgres]
user = postgres
password = 

[mysql]
user = root
password = password

[modoboa]
user = modoboa
home_dir = /srv/modoboa
venv_path = %(home_dir)s/env
instance_path = %(home_dir)s/instance
timezone = Europe/Paris
dbname = modoboa
dbuser = modoboa
dbpassword = password
# Extensions to install (you can use the 'all' shortcut)
extensions = modoboa-admin modoboa-admin-relaydomains modoboa-admin-limits modoboa-amavis modoboa-pdfcredentials modoboa-postfix-autoreply modoboa-sievefilters modoboa-stats modoboa-webmail

[amavis]
enabled = true
user = amavis
home_dir = /var/lib/amavis
config_dir = /etc/amavis/conf.d
max_servers = 1

dbname = amavis
dbuser = amavis
dbpassword = password

[clamav]
enabled = true
user = clamav

[dovecot]
enabled = true
config_dir = /etc/dovecot
user = vmail
home_dir = /srv/vmail
mailboxes_owner = vmail

[nginx]
enabled = true
config_dir = /etc/nginx

[razor]
enabled = true
config_dir = /etc/razor

[postfix]
enabled = true
config_dir = /etc/postfix
message_size_limit = 11534336

[spamassassin]
enabled = true
config_dir = /etc/spamassassin

dbname = spamassassin
dbuser = spamassassin
dbpassword = password

[uwsgi]
enabled = true
config_dir = /etc/uwsgi
nb_processes = 2
socket_path = /var/run/uwsgi/app/modoboa_instance/socket
```

**Comment by emsit** [comment]
Installation on Ubuntu 14.04 freezes on the dialog box. Use --debug parameter for continue.

./run.py webmail.igotta.beer --debug

**Comment by cthulhuely** [comment]
Many Thanks ! It works way better.

These annoying prompts can be bypassed on Debian-based distro.
I don't know how to do it in python but it's done like that with shell scripting :
- For certificate creation :
 - `echo "dovecot-core	dovecot-core/create-ssl-cert	boolean	true" | debconf-set-selections` (If Certs have to be generated)
 - `echo "dovecot-core	dovecot-core/create-ssl-cert	boolean	false" | debconf-set-selections` (If Certs don't have to be generated)

- And for hostname :
 - `echo "dovecot-core	dovecot-core/ssl-cert-name	string	$hostname" | debconf-set-selections` 

Now that Dovecot is Up and Running I'm getting 
```
Error: ['[AUTHENTICATIONFAILED] Authentication failed.']
```
While attemping to acces to the webmail tab with a newly created account (no problem for the other tabs though).

**Comment by tonioo** [comment]
The authentication error should be fixed by this: https://github.com/tonioo/modoboa/issues/769.

**Comment by marcusklaas** [comment]
Probably unrelated, but my install hangs on the uwsgi install..

**Comment by tonioo** [comment]
Can you try using the --debug option ?

**Comment by marcusklaas** [comment]
Hmmm.. it seems to continue this time around. My ssh session timed out last time, could that have blocked the process?

Apologies for the noise!
