### ISSUE TITLE
Docs : debug instructions

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#40]
Sometimes in modoboa deployments, certain components fail. As they are managed centrally from this installation script, instructions to debug each single component could be aggregated in the documentation.

Scenarios and locations that require further investigation can be:
- Sorry An internal error occured.  
  as seen on `/webmail/` and `/sfilters/`
- [Error: Connection to MANAGESIEVE server failed, check your configuration](https://github.com/modoboa/modoboa-installer/issues/42)
- `tail /var/log/nginx/*`

```
==> /var/log/nginx/email.ecobytes.net-error.log <==
2016/05/12 21:40:52 [error] 19675#0: *67 open() "/srv/modoboa/instance/sitestatic/bootstrap-select/dist/js/bootstrap-se
lect.js.map" failed (2: No such file or directory), client: 176.63.21.88, server: email.ecobytes.net, request: "GET /si
testatic/bootstrap-select/dist/js/bootstrap-select.js.map HTTP/1.1", host: "email.ecobytes.net"
```

Which other repeating debug scenarios are known in this software's community?

**Comment by cdbessig** [comment]
Agree, some basic troubleshooting would be good.

I too am receiving: Sorry An internal error occured.

In nginx: 
`2017/03/12 22:49:24 [crit] 525#0: *2 connect() to unix:/run/uwsgi/modoboa_instance.sock failed (2: No such file or directory) while connecting to upstream,`

Not a django expert, so been fighting this for a little while now.

**Comment by tonioo** [comment]
@cdbessig The message says `/run/uwsgi/modoboa_instance.sock` does not exist. Is uwsgi started?

**Comment by cdbessig** [comment]
@tonioo actually, yes uwsgi was started, I even restarted it a few times.  Turns out the issue was postgresql was stopped.

I'm using a centos 7 box, and it seems that some critical services were not set (possibly by the auto installer) to start up on reboot.

I am assuming all of the following are required to run on startup :
postgresql
uwsgi
postfix
dovecot
amavisd
nginx

Let me know if there are any others!

**Comment by tonioo** [comment]
Ok, I'll look into it asap.
