### ISSUE TITLE
Documentation update for Ubuntu20.04: install python3-crypto

### ISSUE THREAD

**Issue by fpiccinali** [modoboa/modoboa-installer#400]
# Impacted versions

* Distribution: Ubuntu 
* Codename: 20.04
* Arch: 64 Bits

# Steps to reproduce
* Install on a fresh ubuntu 20.04 and use modoboa installer
* in the GUI, Parameter "Default password scheme" contains only "plain text"

# Expected behavior
More scheme in the list: ..; sha256crypt, sha512crypt ...

**Comment by fpiccinali** [comment]
The answer is to install python3-crypto

```
apt install python3-crypto
```

Can someone add this to the installer or in the documentation ?

**Comment by robertsass** [comment]
> The answer is to install python3-crypto
> 
> ```
> apt install python3-crypto
> ```
> 
> Can someone add this to the installer or in the documentation ? Or if someone show the file impacted, i can make a pull request.

That package is abandoned ([see project's homepage](https://www.pycrypto.org)).

Use [PyCryptodome](https://www.pycryptodome.org/src/installation) instead:
```
apt-get install build-essential python3-dev
pip install pycryptodomex
```
