### ISSUE TITLE
The aioredis-2.0.0 issues problems

### ISSUE THREAD

**Issue by Perlover** [modoboa/modoboa-installer#401]
# Impacted versions

* Distribution: Ubuntu 20.04
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce

1) The default installation of `modoboa-installer` (current master branch as of 2021-12-10)
2) After installation a email is not being sent - there are errors like these ones:
```
NOQUEUE: reject: RCPT from unknown[***.***.***.***]: 451 4.3.5 <****@****.com>: Recipient address rejected: Server configuration
 problem; from=<****@****.com> to=<****@****.com> proto=ESMTP helo=<[***.***.***.***]>
```
3) I was only able to fix the downgrade to `aioredis==1.3.1` like described here: https://github.com/modoboa/modoboa/issues/2200#issuecomment-913231983

**Comment by Perlover** [comment]
I wrote here too: https://gitlab.com/amavis/amavis/-/issues/81

**Comment by maxcco** [comment]
Did a clean install today on ubuntu 22.04 ended up with a lot of problem and this one was still present 
So I'm reopening it for better tracking
