### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by topgg** [modoboa/modoboa-installer#402]
# Impacted versions

* Distribution: Debian / Ubuntu / Centos 
Centos 7 64
* Codename: Jessie / Trusty / Centos 7 / ...
* Arch: 32 Bits / 64 Bits
MySQL

1. Using the installer,  it gives below error 

● mariadb.service - MariaDB database server
   Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2021-12-16 17:59:56 UTC; 3min 17s ago
 Main PID: 13706 (mysqld_safe)
   CGroup: /system.slice/mariadb.service
           ├─13706 /bin/sh /usr/bin/mysqld_safe --basedir=/usr
           └─13870 /usr/libexec/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib64/mysql/plugin --log-error=/var/log/mariad...

Dec 16 17:59:54 ip-172-31-46-173.ap-southeast-1.compute.internal systemd[1]: Starting MariaDB database server...
Dec 16 17:59:54 ip-172-31-46-173.ap-southeast-1.compute.internal mariadb-prepare-db-dir[13669]: Database MariaDB is probably initialized in /...e.
Dec 16 17:59:54 ip-172-31-46-173.ap-southeast-1.compute.internal mariadb-prepare-db-dir[13669]: If this is not the case, make sure the /var/l...r.
Dec 16 17:59:54 ip-172-31-46-173.ap-southeast-1.compute.internal mysqld_safe[13706]: 211216 17:59:54 mysqld_safe Logging to '/var/log/maria...og'.
Dec 16 17:59:54 ip-172-31-46-173.ap-southeast-1.compute.internal mysqld_safe[13706]: 211216 17:59:54 mysqld_safe Starting mysqld daemon wit...ysql
Dec 16 17:59:56 ip-172-31-46-173.ap-southeast-1.compute.internal systemd[1]: Started MariaDB database server.
Hint: Some lines were ellipsized, use -l to show in full.
Redirecting to /bin/systemctl restart mariadb.service
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'amavis'@'%'
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'amavis'@'localhost'

Access denied for user 'root'@'localhost' (using password: NO)

The fixing should be add  "skip-grant-tables" to mysql config file , under the line [mysqld]

2. After that , still another error message 
  Redirecting to /bin/systemctl start mariadb.service
  ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'amavis'@'%'
  ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'amavis'@'localhost'

## FIX: NOT Yet Resolved

I tried Remove amavis and run the setup again，But no luck

# Full trace using --debug option or current behaviour

# Expected behavior

# Video/Screenshot link (optional)

**Comment by berniey** [comment]
I bypassed the issue by setting the root password of root@localhost to empty string

Platform
======

- Host OS: Ubuntu 18.04
- Python Version: 3.6.9
- Dataabase: MySQL

Details
=====

1. Run the installer with `./run.py --stop-after-configfile-check <your domain>`
2. Edit the created config file, change under section `[mysql]` to `password =`
3. Use self-generated cert (replace snakeoil cert with my cert after installation completion, see below)
4. Continue to run installer with `./run.py --interactive debug <your domain>`

Everything seems running fine:
1. I created 2 domains with DKIM, SPF, DMARC all green
2. Managed to send and received email via modoboa webmail interface via browser
3. Managed to setup iphone mail client to received email
4. **FAILED** in sending email via iphone mail client

Note
====

- I used my own X.509 cert by replacing cert and private in the following location:

```
# cert and private key location
/etc/ssl/certs/<hostname>.cert
/etc/ssl/private/<hostname>.key

# fix nginx conf file (.../site-available/<hostname>.conf) and dovecot
/etc/dovecot/private/dovecot.key
/etc/dovecot/private/dovecot.pem

# restart nginx and dovecot
```
