### ISSUE TITLE
Missing DKIM file when a new domain is created

### ISSUE THREAD

**Issue by T00rk** [modoboa/modoboa-installer#409]
# Impacted versions

* Distribution: Ubuntu 20.04.4 LTS
* Codename: Focal
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce

* Login as administrator
* Create a new domain (mydomain.tld [replace with correct dommain], enable DKIM)
* Go to the new created domain details and click "Show Key"

# Full trace using --debug option or current behaviour

The popup is showing the folling message :
`140289075017024:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('/var/lib/dkim/mydomain.tld.pem','r')140289075017024:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:unable to load Private Key`

On Terminal : 
`> ls -la /var/lib/dkim` => `empty`

# Expected behavior

* The popup is supposed to show the private key for DKIM
* There should be a `mydomain.tld.pem` file in `/var/lib/dkim`

# Video/Screenshot link (optional)

**Comment by poqdavid** [comment]
@T00rk Check if `/var/lib/dkim` has the right owner/group also the perm
