### ISSUE TITLE
Support for Ubuntu 22.04

### ISSUE THREAD

**Issue by SakuraIsayeki** [modoboa/modoboa-installer#411]
# Impacted versions
* Distribution: Ubuntu 22.04
* Codename: Jammy
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
Ran an upgrade for a broken Modoboa install. Web reported 500 ISE after upgrading Ubuntu from 20.04 to 22.04.
```sh
sudo ./run.py --interactive domain-name.com --beta --debug --upgrade
```

# Full trace using --debug option or current behaviour
Setup fails. 

Full log: https://gist.github.com/SakuraIsayeki/13b37c30293062a2fb3e62eada207184

# Expected behavior
Setup completes successfully

**Comment by tonioo** [comment]
According to this line:
```
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/srv/modoboa/env/lib/python3.10/site-packages/sievelib'
```
there is a permission issue, which is pretty strange. Can you check what permissions are applied to this folder?

**Comment by SakuraIsayeki** [comment]
> According to this line:
> 
> ```
> ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/srv/modoboa/env/lib/python3.10/site-packages/sievelib'
> ```
> 
> there is a permission issue, which is pretty strange. Can you check what permissions are applied to this folder?

Here are the perms:  
```
sakura@nsys-axon : ~$ ls -halu /srv/modoboa/env/lib/python3.10/site-packages/ | grep 'sievelib'                                                                                                                 
drwxrwxr-x   4 modoboa modoboa 4.0K May 11 01:14 sievelib
drwxrwxr-x   2 modoboa modoboa 4.0K May 11 01:13 sievelib-1.2.1.dist-info
```

I also tried deleting the whole `python3.10` folder, which strangely prevented further errors for me. So far so good, it fixed it on my end.
