### ISSUE TITLE
failed while instalation

### ISSUE THREAD

**Issue by Exepion** [modoboa/modoboa-installer#422]
# Impacted versions

Ubuntu
20.04
Arch:  64 Bits
Database:  MySQL

# Steps to reproduce
following this one : https://www.linuxbabe.com/mail-server/modoboa-email-server-ubuntu-20-04

# Full trace using --debug option or current behaviour

Collecting mysqlclient
  Using cached mysqlclient-2.1.1.tar.gz (88 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /bin/sh: 1: mysql_config: not found
      /bin/sh: 1: mariadb_config: not found
      /bin/sh: 1: mysql_config: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ahxr0p89/mysqlclient_4ab52d48138845598ace51ce9e6e6f13/setup.py", line 15, in <module>
          metadata, options = get_config()
        File "/tmp/pip-install-ahxr0p89/mysqlclient_4ab52d48138845598ace51ce9e6e6f13/setup_posix.py", line 70, in get_config
          libs = mysql_config("libs")
        File "/tmp/pip-install-ahxr0p89/mysqlclient_4ab52d48138845598ace51ce9e6e6f13/setup_posix.py", line 31, in mysql_config
          raise OSError("{} not found".format(_mysql_config_path))
      OSError: mysql_config not found
      mysql_config --version
      mariadb_config --version
      mysql_config --libs
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
bash: modoboa-admin.py: command not found
None

# Expected behavior

Im trying to install mdoboa, in instaler .cfg i have precise mysql for maria ( already install ) and say no for install.

**Comment by Esuk** [comment]
I had the same problem for Ubuntu 22.04, the solution for me was to install `libmysqlclient-dev`

`sudo apt install libmysqlclient-dev`

**Comment by Spitfireap** [comment]
Hey @Esuk and @Exepion. The "fix" has been merged, but it needs some changes. Would you mind posting the result of this command here, please ? `cat /etc/os-release`

Thanks !
