### ISSUE TITLE
how to change from default self sign cert to letsencrypt 

### ISSUE THREAD

**Issue by fitriyusuf** [modoboa/modoboa-installer#429]
# Impacted versions

* Distribution: Ubuntu 
* Codename: Jessie / Trusty / Centos 7 / ...
* Arch: 32 Bits / 64 Bits
* Database: PostgreSQL / MySQL

**Comment by tonioo** [comment]
@fitriyusuf There is a setting for that in the configuration file. Change the value and run the installer one more time.

**Comment by fitriyusuf** [comment]
> @fitriyusuf There is a setting for that in the configuration file. Change the value and run the installer one more time.

If i run the installer one more time how about all the email accounts that i already created?

**Comment by tonioo** [comment]
@fitriyusuf they won't be deleted. If you have any doubt, first create a backup of your DB before you run the installer.

**Comment by fitriyusuf** [comment]
> @fitriyusuf they won't be deleted. If you have any doubt, first create a backup of your DB before you run the installer.

Sorry I’m newbie ..can you tell me how to backup and restore sir

**Comment by tonioo** [comment]
@fitriyusuf The installer now provides a backup/restore feature. Look at the README file to learn more about it.
