### ISSUE TITLE
ssl.py - AttributeError: 'RPMPackage' object has no attribute 'update'

### ISSUE THREAD

**Issue by christophmas** [modoboa/modoboa-installer#437]
I was trying to install modoboa by running run.py, using centos default python3 Version Python 3.6.8

# Impacted versions

* Distribution: Centos
* Codename:  Centos 7 
* Arch:  64 Bits
* Database: MySQL

Generating new certificate using letsencrypt[...]
/modoboa-installer/modoboa_installer/ssl.py", line 100, in install_certbot
    package.backend.update()
AttributeError: 'RPMPackage' object has no attribute 'update'

Inside the package.py there is no function 'update' defined.

Trying to uncomment this line, did not workout either, as nginx does not find  files specified in /etc/letsencrypt/live/...

How to proceceed here?

**Comment by tonioo** [comment]
Looks like this part of the script is incomplete. Do you know if CentOS provides a package for nginx certbot plugin?
