### ISSUE TITLE
modoboa-installer and snapd certbot

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa-installer#438]
Hello,

What is happening with the modoboa-installer if certbot is already installed using snapd?

certbot package on most distribution are obsolete et people prefer to use snapd installer more uptodate.

Regards,

Install procedure on Debian bullseye
```
# apt purge certbot    # if certbot is already installed using Debian package.
# apt install snapd
# snap install core
# snap refresh core
# snap install --classic certbot
# ln -s /snap/bin/certbot /usr/bin/certbot
```

**Comment by tonioo** [comment]
@stefaweb Is it a question or a documentation you'd like to add?

**Comment by stefaweb** [comment]
Hi Antoine,

Can be both. ;)

I can phrase my question differently. Does modoboa-installer install the certbot distribution package even if there is already a certbot binary installed otherwise (using snapd in this case)?
