### ISSUE TITLE
util.py mkdir fails (ubuntu 16.04)

### ISSUE THREAD

**Issue by noyez** [modoboa/modoboa-installer#44]
I'm trying to get modoboa installed on ubuntu 16.04 Server. With a fresh install in a VM (plus git-core and python packages installed). I changed modoboa-installer/util.py mkdir() to get the installation script to complete. The change i made is pretty straightforward `os.mkdir()` -> `os.makedirs()`
```
def mkdir(path, mode, uid, gid):
    """Create a directory."""
    if not os.path.exists(path):
        #os.mkdir(path, mode)
        # make directories recursively with makedirs
        os.makedirs(path,mode)
    else:
        os.chmod(path, mode)
    os.chown(path, uid, gid)

```
Otherwise the modoboa-installer fails, with the following

```
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/home/brad/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/brad/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/home/brad/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 139, in post_run
    self.apply_settings()
  File "/home/brad/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 117, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/home/brad/modoboa-installer/modoboa_installer/utils.py", line 99, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'
```

**Comment by stevesbrain** [comment]
Funny enough, I opened a pull request for this exact same thing about an hour back - good timing! #43

**Comment by tonioo** [comment]
@noyez The directory does not exist because the installation of modoboa fails. Creating this directory won't be enough to solve the issue... You should run the installer once again with the --debug option, you should see the real error.
@stevesbrain Thanks for the PR but, as I said, it won't solve the real issue...

**Comment by stevesbrain** [comment]
Appreciate the detail - thanks :)

**Comment by noyez** [comment]
I cannot reproduce this anymore, so no sense in leaving this open.
