### ISSUE TITLE
Broken UI after Installation

### ISSUE THREAD

**Issue by rajeevrrs** [modoboa/modoboa-installer#448]
# Impacted versions

* Distribution: CentOS
* Codename: 
* Arch: 32 Bits / 64 Bits
* Database: PostgreSQL / MySQL

I installed this 3 times and everytime it broken

# Video/Screenshot link (optional)
![image](https://user-images.githubusercontent.com/10184446/199411090-ce634b90-2db7-4df4-98cd-83c2a24d9f26.png)
![image](https://user-images.githubusercontent.com/10184446/199411126-1d2be1aa-3b60-4968-afa6-c64846bb681f.png)

**Comment by tonioo** [comment]
@rajeevrrs How did you install Modoboa? What is your CentOS version?

**Comment by rajeevrrs** [comment]
@tonioo 

i followed 

for Ubuntu : https://www.linuxshelltips.com/install-modoboa-mail-server-ubuntu/
For centos : https://www.linuxbabe.com/mail-server/modoboa-email-server-ubuntu-20-04

I am tried with multiple time. 

CentOS 8 - never installed successfully
CentOS 7 : Broken UI
Ubuntu 22 : Broken UI

My Installed domain : https://tmail.serverhump.com - password is default

**Comment by tonioo** [comment]
It looks like you forgot to run the collectstatic command.
Another possibility is that you're trying to access the web interface using the development server (runserver) while your DEBUG setting is set to False.

**Comment by rajeevrrs** [comment]
@tonioo 

collectstatic command - What this?. I followed guide from above link. Can you tell me what the command? 

`Another possibility is that you're trying to access the web interface using the development server (runserver) while your DEBUG setting is set to False` - i used `./run.py --interactive your-domain-name` do you want me to use `./run.py --interactive --debug your-domain-name` ?

**Comment by Spitfireap** [comment]
Hi @rajeevrrs,

please follow [this guide](https://modoboa.readthedocs.io/en/latest/upgrade.html#modoboa) without executing the `pip` command and recheck your UI.
