### ISSUE TITLE
Management/Website doesn't load in Ubuntu 16.04

### ISSUE THREAD

**Issue by stevesbrain** [modoboa/modoboa-installer#45]
It appears after installing fresh in Ubuntu 16.04 that the website for management doesn't load properly. The Django page is presented: 

```text
It worked!
Congratulations on your first Django-powered page.

Of course, you haven't actually done any work yet. Next, start your first app by running python manage.py startapp [app_label].
You're seeing this message because you have DEBUG = True in your Django settings file and you haven't configured any URLs. Get to work!
```

I haven't had time to dig into why this is at this stage, however, it works perfectly fine on Ubuntu 14.04.

**Comment by tonioo** [comment]
I've just released a new release of the modoboa-stats plugin which was blocking the installer. It should work now.

**Comment by stevesbrain** [comment]
Awesome - will give this a shot tomorrow :) Thanks!

**Comment by tonioo** [comment]
@stevesbrain Any news ?

**Comment by stevesbrain** [comment]
@tonioo - sorry for the delayed response; had some sickness in the home. Yes, this all works now :) Thanks very much!

**Comment by tonioo** [comment]
Thanks for the feedback !
