### ISSUE TITLE
question on DB pre install and sqlite

### ISSUE THREAD

**Issue by cekvenich2** [modoboa/modoboa-installer#455]
1. Can I just use sqlite during install.

2. separate: Can I just pre install Maria and tell it to use it?

I plan to try this in next few days!

**Comment by Spitfireap** [comment]
Hi,


> 1. Can I just use sqlite during install.

Not with the installer, you can manually do it, but you would have to [do some change manually ](https://modoboa.readthedocs.io/en/latest/manual_installation/modoboa.html#database). It is recommended to use either mysql or postgres though.


> 2\. separate: Can I just pre install Maria and tell it to use it?

If you select `mysql` as db backend, it will use maria. If you plan on using the installer, do it on a clean server (do not install maria yourself) as stated in the README.
