### ISSUE TITLE
Missing plugin during --upgrade

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa-installer#457]
Hello,

If I try to upgrade modoboa (in this case from 2.0.2 to 2.0.3), the list of installed plugins does not match the list contained in the installer.cfg file. 

As it is a production server that I am trying to update, I stopped there while waiting to know more.

Regards,

```
root@mailhub:/home/modoboa-works/modoboa-installer# ./run.py --upgrade domain.tld
Welcome to Modoboa installer!

Your mail server is about to be upgraded and the following components will be impacted:
modoboa automx amavis clamav dovecot nginx razor postfix postwhite spamassassin uwsgi radicale opendkim
Do you confirm? (Y/n) n
```

In installer.cfg:

`extensions = modoboa-amavis modoboa-pdfcredentials modoboa-postfix-autoreply modoboa-sievefilters modoboa-webmail modoboa-contacts modoboa-radicale modoboa-imap-migration`

![sc](https://user-images.githubusercontent.com/12907102/200311491-2d5b5ee4-4ebd-453d-acd4-5449a443861c.png)

**Comment by stefaweb** [comment]
I forgot.

Version 2.0.3 of modoboa does not appear as it should be updated in the interface.

**Comment by Spitfireap** [comment]
Hi,

As for modoboa's extension: they don't appear for install nor update, but they will be updated if they are present in the `installer.cfg` file. 

For the 2.0.3 notification, please check `/etc/cron.d/modoboa` the `communicate with api` line, uncomment if commented, and I would advise randomizing when it's run, for example :
`27    8,20    *    *    *`

**Comment by stefaweb** [comment]
Hi [Spitfireap](https://github.com/Spitfireap)!

The default cron is:

```
# Public API communication
0       *       *       *       *       root    $PYTHON $INSTANCE/manage.py communicate_with_public_api
```

If I run it manually, no error message and the 2.0.3 version is not print on the GUI "/core/#info/" page.

`/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py communicate_with_public_api`

**Comment by Spitfireap** [comment]
Hi, the api should show 2.0.3 as current version now.
