### ISSUE TITLE
User Create failed --> Modoboa 1.5.3

### ISSUE THREAD

**Issue by adminsg** [modoboa/modoboa-installer#46]
Hello,

since an update to modoboa 1.5.3 i cant create new Email Users.
After filling out the fields with password, address etc. i cant finish the process. Nothing happens...
Can someone help me?
Other issues doesnt help really

**Comment by tonioo** [comment]
Hi,
could you set DEBUG to True inside settings.py and open a javascript console ? You should get a more explicit error message.

**Comment by adminsg** [comment]
First of all...thanks for your awnser and this brilliant for installing a mail server ;)

I fixed the Issue with an easy way...modoboa-installer over existent installation...
I know...not the best way, but with proxmox and my backup nothing can going bad :D

**Comment by tonioo** [comment]
Glad to ear it. I close the issue since your problem is solved.
