### ISSUE TITLE
Missing "webmail" directory after fresh install

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa-installer#461]
# Impacted versions

* OS Type: Debian
* OS Version: Bullseye
* Database Type: PostgreSQL
* Database version: 13.8-0+deb11u1
* Modoboa: 2.0.2
* installer used: Yes
* Webserver: Nginx
* Navigator: Safari OSX, Chrome OSX

# Current behavior

I discovered that after a fresh install the directory "webmail" and "modoboa_webmail" are missing.

When you compose an email in the webmail integrated into Modoboa and include a file, you get this error:

`Impossible d'enregistrer la pièce jointe : [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail/tmpgzoi51n9'
`

After manually creating the directories, everything is back to normal.

Regards,

![sc](https://user-images.githubusercontent.com/12907102/204292678-f335fb48-20e5-4e0b-8f10-b39753e7fea5.png)

**Comment by Spitfireap** [comment]
Hi,

What directories were missing ? If you simply create ``media/webmail`` does it work ?
