### ISSUE TITLE
source not found / modoboa user default shell is set to sh

### ISSUE THREAD

**Issue by nicosqc** [modoboa/modoboa-installer#463]
# Impacted versions

* Distribution: Debian
* Codename: 10 (buster)
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
run the installer with no modification on a clean install
run ``sudo -u modoboa -i``
run ``source /srv/modoboa/env/bin/activate``
results in ``-sh: 9: source: not found``

# Expected behavior
Install ``/bin/bash`` as login shell or adjust docs to reflect the additional step of starting ``bash`` before using ``source /srv/modoboa/env/bin/activate`` for the migration if ``sh`` is neccesary as default shell for other components.

A minor thing but maybe it trips up an inexperienced user just trying to follow the upgrade prodedure explained in [the upgrade documentation](https://modoboa.readthedocs.io/en/latest/upgrade.html#modoboa).

**Comment by tonioo** [comment]
@nicosqc Good catch. Could you create a PR with a documentation update?

**Comment by Spitfireap** [comment]
Documentation update, thanks !
