### ISSUE TITLE
Clean Install working on 23-Jan, broken on 24-Jan

### ISSUE THREAD

**Issue by nickbuller** [modoboa/modoboa-installer#472]
# Impacted versions

* Distribution: Ubuntu
* Codename: 20
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
Installed on new VM on 23rd Jan approx 21:00 UTC, worked perfectly.
Installed on new VM on 24th Jan 11:30 UTC, failed see below.

Commit Log:
commit 4fc540ddd8e7b733044bb375f600497119da7466 (HEAD -> master, origin/master, origin/HEAD)
Merge: 0fc15fc 81129d2
Author: Antoine Nguyen <tonio@ngyn.org>
Date:   Tue Jan 24 10:53:36 2023 +0100

    Merge pull request #471 from Spitfireap/fix-dovecot-ownership

    Fix dovecot ownership

commit 81129d287539cfb67fffeb35e15bc8068980d999
Author: Spitap <dev@asdrip.fr>
Date:   Tue Jan 24 09:29:51 2023 +0100

    Removed globally set mail_uid and mail_gid

    Co-Authored-By: Antoine Nguyen <tonio@ngyn.org>

commit a6935bba8948bf15e665ff0c13461d97a0212bec
Author: Spitap <dev@asdrip.fr>
Date:   Tue Jan 24 09:25:18 2023 +0100

    Simplifeid setup_user

    Co-Authored-By: Antoine Nguyen <tonio@ngyn.org>

commit 7cae12b32eee083127d83e6ddc785403c5988858
Author: Spitap <dev@asdrip.fr>
Date:   Mon Jan 23 19:24:28 2023 +0100

    Fix multiple hard-coded vmail

commit 0fc15fc0241713f4df00def45812183794751ea6

# Full trace using --debug option or current behaviour
Installing dovecot
User dovecot already exists, skipping creation but please make sure the /srv/vmail directory exists.
Traceback (most recent call last):
  File "./run.py", line 256, in <module>
    main(sys.argv[1:])
  File "./run.py", line 240, in main
    scripts.install(appname, config, args.upgrade, args.restore)
  File "/home/azureuser/modoboa-installer/modoboa_installer/scripts/__init__.py", line 29, in install
    getattr(script, appname.capitalize())(config, upgrade, archive_path).run()
  File "/home/azureuser/modoboa-installer/modoboa_installer/scripts/base.py", line 187, in run
    self.setup_user()
  File "/home/azureuser/modoboa-installer/modoboa_installer/scripts/dovecot.py", line 37, in setup_user
    system.create_user(self.mailbox_owner, self.home_dir)
AttributeError: 'Dovecot' object has no attribute 'mailbox_owner'

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@nickbuller should work better now
