### ISSUE TITLE
During Installation received "Failed to find amavis database schema", no version 13 sql files

### ISSUE THREAD

**Issue by mfsiii** [modoboa/modoboa-installer#477]
# Impacted versions

* CentOS
* OS Version: 9

# Steps to reproduce
Standard install procedure:
> git clone https://github.com/modoboa/modoboa-installer
> cd modoboa-installer
> sudo ./run.py <your domain>

# Current behavior

Get an error message: "Failed to find amavis database schema"

# Expected behavior

To not see this ;)

It looks like the amavis version it downloads is 2.13.0 and the configuration files in the amavis directory for modoboa has up to version 2.12.x. I bypassed it by copying 12 for 13.

**Comment by Spitfireap** [comment]
Hi, centos 9 is not yet supported indeed. You can try with `centos9-support` branch but it is not finished and it involves setting SE Linux to permissive mode. You can also proceed with a manual installation by following the documentation.
