### ISSUE TITLE
Installion failed - KeyError: "getpwnam(): name not found: 'postgres'"

### ISSUE THREAD

**Issue by terrysate** [modoboa/modoboa-installer#480]
CentOS 7 fresh install

run as root, debug option on

[root@mail modoboa-installer]# ./run.py xxxxx.au --debug
Welcome to Modoboa installer!

Warning:
Before you start the installation, please make sure the following DNS records exist for domain 'melit.au':
  mail IN A   <IP ADDRESS OF YOUR SERVER>
       IN MX  mail.xxxxx.au.

Your mail server will be installed with the following components:
fail2ban modoboa automx amavis clamav dovecot nginx razor postfix postwhite spamassassin uwsgi radicale opendkim backup
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Package sudo-1.8.23-10.el7_9.3.x86_64 already installed and latest version
Package wget-1.14-18.el7_6.1.x86_64 already installed and latest version
Overwrite the existing SSL certificate? (y/N) y
Generating new self-signed certificate
Generating a 4096 bit RSA private key
.........................................++
...................................................++
writing new private key to '/etc/pki/tls/private/mail.xxxxx.au.key'
-----
Installing amavis
Error: Nothing to do
Error: Nothing to do
/bin/sh: /usr/pgsql-10/bin/postgresql-10-setup: No such file or directory
Can't open /var/lib/pgsql/10/data/pg_hba.conf: No such file or directory.
Failed to execute operation: No such file or directory
Redirecting to /bin/systemctl status postgresql-10.service
Unit postgresql-10.service could not be found.
Redirecting to /bin/systemctl start postgresql-10.service
Failed to start postgresql-10.service: Unit not found.
Package amavis-2.12.0-10.el7.noarch already installed and latest version
Package arj-3.10.22-22.el7.x86_64 already installed and latest version
Package lz4-1.8.3-1.el7.x86_64 already installed and latest version
Package lzop-1.03-10.el7.x86_64 already installed and latest version
Package p7zip-16.02-20.el7.x86_64 already installed and latest version
Package perl-DBD-Pg-2.19.3-5.el7_9.x86_64 already installed and latest version
Package cabextract-1.9-7.el7.x86_64 already installed and latest version
Package unar-1.10.7-1.el7.x86_64 already installed and latest version
Package unzoo-4.4-16.el7.x86_64 already installed and latest version
sudo: unknown user: postgres
sudo: unable to initialize policy plugin
sudo: unknown user: postgres
sudo: unable to initialize policy plugin
sudo: unknown user: postgres
sudo: unable to initialize policy plugin
0
sudo: unknown user: postgres
sudo: unable to initialize policy plugin
Traceback (most recent call last):
  File "./run.py", line 257, in <module>

**Comment by wangshixiang1984** [comment]
Same issue too

**Comment by hongcanbin** [comment]
Check whether PostgreSQL is installed, if not installed, install it
