### ISSUE TITLE
Error right after installing

### ISSUE THREAD

**Issue by robinroloff** [modoboa/modoboa-installer#495]
<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">OperationalError at /</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">FATAL:  password authentication failed for user "modoboa"
FATAL:  password authentication failed for user "modoboa"
</pre>

Request Method: | GET
-- | --
https://url.url
3.2.18
OperationalError
FATAL:  password authentication failed for user "modoboa" FATAL:  password authentication failed for user "modoboa"
/srv/modoboa/env/lib/python3.9/site-packages/psycopg2/__init__.py, line 127, in connect
/usr/bin/uwsgi-core
3.9.2
['.',  '',  '/usr/lib/python39.zip',  '/usr/lib/python3.9',  '/usr/lib/python3.9/lib-dynload',  '/srv/modoboa/env/lib/python3.9/site-packages']
Sat, 29 Apr 2023 12:50:08 +0200

</body>
</html>

I get this error when opening the page using debug mode, can anyone help?

**Comment by tonioo** [comment]
@robinroloff Looks like the database credentials used in your settings.py file are not the right ones. Have you changed modoboa database user's password during the process?
