### ISSUE TITLE
Method not allowed when trying to edit entities

### ISSUE THREAD

**Issue by malteneu** [modoboa/modoboa-installer#496]
* Distribution: Ubuntu
* Database: PostgreSQL

Hey, trying to edit Domain or User settings throws an error method not allowed after fresh installation. I already reinstalled modoboa twice. I couldnt find a solution.

![grafik](https://user-images.githubusercontent.com/71597734/235488423-2069f5c1-a7bf-46d5-b7cd-dc4e32bbdad4.png)

Thanks in advance

**Comment by Spitfireap** [comment]
Hi, please see [this issue](https://github.com/modoboa/modoboa/issues/2966). It will be fixed in 2.1.2. You can use new-admin for now ;)
