### ISSUE TITLE
Failed to find amavis database schema on Debian Bookwyrm

### ISSUE THREAD

**Issue by Zatalyz** [modoboa/modoboa-installer#503]
# Impacted versions

* Distribution: Debian
* Codename: Bookwyrm
* Arch: 64 Bits

# Steps to reproduce
Fresh install of Debian Bookwyrm.

```
git clone https://github.com/modoboa/modoboa-installer
cd modoboa-installer/
sudo ./run.py mydomain.org
```

My real domain, not this example ;) DNS are configured for this domain, with MX.

# Full trace using --debug option or current behaviour
```
Welcome to Modoboa installer!

Configuration file installer.cfg not found, creating new one.
Warning:
Before you start the installation, please make sure the following DNS records exist for domain 'nordcantal.fr':
  mail IN A   <IP ADDRESS OF YOUR SERVER>
     @ IN MX  mail.nordcantal.fr.

Your mail server will be installed with the following components:
fail2ban modoboa automx amavis clamav dovecot nginx razor postfix postwhite spamassassin uwsgi radicale opendkim backup
Do you confirm? (Y/n) 
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing amavis
Failed to find amavis database schema

```

# Expected behavior
Don't fail with Amavis

# More
I see a lot of old and closed issue with this error, often "with an OS not supported". I know, Bookwyrm is not supported for now so probably that : something change since Bullseye ? But because you use Debian, I think it can be better to report the problem.

**Comment by skatrek47** [comment]
For some reason, copying modoboa-installer/modoboa_installer/scripts/files/amavis/amavis_postgres_2.12.X.sql to modoboa-installer/modoboa_installer/scripts/files/amavis/amavis_postgres_2.13.X.sql makes this work...

**Comment by samuraikid0** [comment]
> For some reason, copying modoboa-installer/modoboa_installer/scripts/files/amavis/amavis_postgres_2.12.X.sql to modoboa-installer/modoboa_installer/scripts/files/amavis/amavis_postgres_2.13.X.sql makes this work...

Were you able to install on bookworm after renaming it ?

**Comment by florealcab** [comment]
I made a MR to try to fix install on debian 12. For me it seems to work well now!

The MR is here -> https://github.com/modoboa/modoboa-installer/pull/508

**Comment by samuraikid0** [comment]
Thanks
 I'll try install it when I've some free time
