### ISSUE TITLE
postscreen setup probably incomplete

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#51]
My logs just spit out

```
Jun  7 19:46:36 email postfix/postscreen[17406]: close database /var/lib/postfix/postscreen_cache.db: No such file or directory (possible Berkeley DB bug)
```

Why is that the case and should we mitigate it?

**Comment by tonioo** [comment]
It is just a warning and it is due to the fact postfix is chrooted...
https://groups.google.com/forum/#!topic/mailing.postfix.users/XAncbBJV9JY

**Comment by almereyda** [comment]
Okay, this is a non-error, according to https://web.archive.org/web/20130630074218/http://tech.groups.yahoo.com/group/postfix-users/message/272609

Do we need a mention in the docs / FAQs of this little fact?

**Comment by tonioo** [comment]
We can do this. There is also a way to avoid this warning using a hard link but I don't know if it is a good idea... @almereyda ?

**Comment by TacoScheltema** [comment]
Hi,

The following fixes the issue, I don't see any harm in having the installer take care of this;

```
mkdir -p /var/spool/postfix/var/lib/postfix
mv /var/lib/postfix/postscreen_cache.db /var/spool/postfix/var/lib/postfix
ln -s /var/spool/postfix/var/lib/postfix/postscreen_cache.db /var/lib/postfix/postscreen_cache.db
```

**Comment by tonioo** [comment]
@TacoScheltema Don't think creating a symlink will fix the issue, a hardlink would be better.

**Comment by TacoScheltema** [comment]
@tonioo I'll try that in my setup. I did have a symlink and didn't see any issues but that doesn't mean there aren't any of course. I guess without the hard- or symlink the temporary whitelist can't be maintained so remote smtp connections will have to go through the same process to get past `PASS NEW` instead of getting a `PASS OLD` straight away.
