### ISSUE TITLE
GMail doesn't like a Modoboa sender

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#52]
In GMail, messages from our `email.ecobytes.net` are displayed with a beautiful red open lock, which states on hovering: **ecobytes.net did not encrypt this message**.

There is a [read more] link nearby which should explain the issue. What's going wrong here?

**Comment by tonioo** [comment]
This has nothing to do with Modoboa. Google added this check a few months ago and it only indicates that your setup does not support TLS encryption. (https://gmail.googleblog.com/2016/02/making-email-safer-for-you-posted-by.html)

**Comment by tonioo** [comment]
Following link should help:
http://wiki.lenux.org/configure-postfix-with-tls/
