### ISSUE TITLE
Fresh install not working in debian 11 - install modoboa 2.0 config files ?

### ISSUE THREAD

**Issue by Skamasle** [modoboa/modoboa-installer#526]
# Impacted versions 

* Distribution: Debian 
* Codename: bullseye
* Arch:  64 Bits
* Database: MySQL

With default options installer working fine and not get any errors, but Modoboa not working.

In my case, database tables are missing

And I see wrong information in settings.py

`MODOBOA_APPS = (
    'modoboa',
    'modoboa.core',
    'modoboa.lib',
    'modoboa.admin',
    'modoboa.transport',
    'modoboa.relaydomains',
    'modoboa.limits',
    'modoboa.parameters',
    'modoboa.dnstools',
    'modoboa.policyd',
    'modoboa.maillog',
    'modoboa.pdfcredentials', <<<<<<<<<<<<<<< This was removed from 2.1
    'modoboa.dmarc',
    'modoboa.imap_migration',
    # Modoboa extensions here.
    'modoboa_amavis',
    'modoboa_pdfcredentials', <<<<<<<<<<<<<  here its again
    'modoboa_postfix_autoreply',
    'modoboa_sievefilters',
    'modoboa_webmail',
    'modoboa_contacts',
    'modoboa_radicale',

)
`

I remove modoboa.pdfcredentials from settings.py, run python check and recreate database

Now uwsgi start without errors

But interface not loading CSS

I fix this by editing nginx conf

`
    location /sitestatic/ {
        try_files $uri $uri/ =404;
    }
`

for

`    location /static/ {
        try_files $uri $uri/ =404;
    }
`

I try install in 4 diferent servers with debian 11, and get same issue 4 times :/

**Comment by Spitfireap** [comment]
Hi are you running a recent clone of the installer ? 
In fact, it is the opposite : you should keep modoboa.pdfcredentials and remove modoboa_pdfcredentials...

**Comment by Skamasle** [comment]
Yes I download last installer in each install.

**Comment by Spitfireap** [comment]
@Skamasle, could you post the output of `cat /srv/modoboa/instance/instance/settings.py | grep static`?
