### ISSUE TITLE
modoboa installer doesn't work on lmde 6

### ISSUE THREAD

**Issue by aleczdr** [modoboa/modoboa-installer#529]
# Impacted versions
latest 
* Distribution: Linux Mint Debian Edition 6 (Debian 12)
* Codename: Faye (Bookworm)
* Arch: 64 Bits
* Database: MySQL

# Steps to reproduce
run modoboa installer following documentation
crashes and says operating system not supported

# Full trace using --debug option or current behaviour
raises a not implemented error and says the distribution isnt supported.

# Expected behavior
installer installs modoboa on a debian-based system

# Video/Screenshot link (optional)

**Comment by aleczdr** [comment]
i got it to work by editing package.py and forcing the output of get_backend() to debian

**Comment by tonioo** [comment]
@aleczdr That's a good news. Could you provide a PR?

**Comment by aleczdr** [comment]
@tonioo sorry for the late reply
I don't think a PR should be used here as what I did was force the installer to always think it's compatible by disregarding the compatibility check entirely. The real solution would be to add LMDE to the list of compatible systems, which I didn't do because I needed to get modoboa working quickly.

I did first try adding LMDE, Linux Mint, Mint, and other strings to the list of distros within package.py but I couldn't get it to work, which is the other reason why I resorted to the quick and dirty method.

**Comment by Spitfireap** [comment]
@aleczdr could post the output of `cat /etc/os-release` on LMDE please :) ?

**Comment by aleczdr** [comment]
@Spitfireap here you go

```
PRETTY_NAME="LMDE 6 (faye)"
NAME="LMDE"
VERSION_ID="6"
VERSION="6 (faye)"
VERSION_CODENAME=faye
ID=linuxmint
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
ID_LIKE=debian
DEBIAN_CODENAME=bookworm
```
Besides adding LMDE (and hopefully regular Mint as well) to the list of supported systems, it would be a good idea for Modoboa to also interpret the ID_LIKE value as there are other systems out there that are also based on Debian and probably have this value.

**Comment by aleczdr** [comment]
PR #548
