### ISSUE TITLE
Install on clean Ubuntu 22.04.3 fails (repeatedly).

### ISSUE THREAD

**Issue by jnaujok** [modoboa/modoboa-installer#532]
# Impacted versions
Latest

* Distribution: Debian / Ubuntu / Centos
Ubuntu 22.04.3 with latest installer. Updated to latest patches before start. Clean install on a VM.

* Codename: Jessie / Trusty / Centos 7 / ...
Jammy

* Arch: 32 Bits / 64 Bits
64 Bits

* Database: PostgreSQL / MySQL
Tried both with same results

# Steps to reproduce
Clean install of Ubuntu 22.04
sudo apt install python3-virtualenv python3-pip -y

sudo hostnamectl set-hostname %{domain-name}
sudo vi /etc/hosts

### NOTE: I added this because I found this directory was not built by the installer script resulting in the module being unable to create the "rights" file!
sudo mkdir /etc/modoboa-radicale
sudo chmod -R 777 /etc/modoboa-radicale

git clone https://github.com/modoboa/modoboa-installer.git

cd modoboa-installer

sudo ./run.py --stop-after-configfile-check %{domain-name}

# Set MySQL or Postgres, set Letsencrypt, set email for Letsencrypt -- note that the included log of the install does not actually use letsencrypt because it blocked me after 5 attempts to install. 
sudo vi installer.cfg

sudo ./run.py --interactive %{domain-name}

# Full trace using --debug option or current behaviour
See attached file. 

# Expected behavior
Modoboa installs correctly, and allows web login to set up the system.

[installer.log](https://github.com/modoboa/modoboa-installer/files/13852138/installer.log)

**Comment by byeuji** [comment]
This project seriously needs a cleaner script to rip out all the hidden little things it's using as keys to indicate that it's been installed before.

I can't figure out what it's detecting to think it's been installed before... and I just started down this rabbit hole to resolve a "Internal server error" that cropped up over night after nothing changed but a server reboot. Agggggh I want this to be simple but it just isn't.
