### ISSUE TITLE
First install error:  - Failed to get version of modoboa. Output is: b'WARNING: Package(s) not found: modoboa\n'

### ISSUE THREAD

**Issue by ejlkemper** [modoboa/modoboa-installer#534]
# Impacted versions

* Distribution: Debian 
* Codename:  Bookworm
* Arch:  64 Bits
* Database: PostgreSQL / MySQL

# Steps to reproduce
Run install 
# Full trace using --debug option or current behaviour
Collecting rrdtool
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)"))

WARNING: Package(s) not found: modoboa
Failed to get version of modoboa. Output is: b'WARNING: Package(s) not found: modoboa\n'
modoadmin@mx:~/modoboa-installer$ 

# Expected behavior
Succesfull install?
# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
Looks like a temporary connection issue with files.pythonhosted.org

**Comment by ejlkemper** [comment]
Neh....
This is for 3 days now...... 

-----addendum---------
With timeout of 999 in PIP.CONF....:
Collecting rrdtool
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=999.0)")': /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=999.0)")': /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=999.0)")': /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=999.0)")': /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=999.0)")': /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/b4/33/eab59a6f9b8fcc7f3edd4cde467abad49c3683dfa628dd7abd62763647ef/rrdtool-0.1.16.tar.gz (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=999.0)"))

WARNING: Package(s) not found: modoboa
Failed to get version of modoboa. Output is: b'WARNING: Package(s) not found: modoboa\n'

**Comment by tonioo** [comment]
Must be something on your side because I can access this website without any issue
