### ISSUE TITLE
Issue with MySQL database

### ISSUE THREAD

**Issue by Eliesemoule** [modoboa/modoboa-installer#54]
Hi,

If I set mysql as engine instead of postgre in installer.cfg, the mariadb-server is not installed CentOS 7 Build 1511. If I install and run it before running "./run.py mydomain.tld", the dababase was not created.

Can you resolve this issue, please. Thanks.

**Comment by cedr-x** [comment]
Hello
Please try this patch on database.py

[database.py.patch.txt](https://github.com/modoboa/modoboa-installer/files/469739/database.py.patch.txt)
