### ISSUE TITLE
Modoboa installation error

### ISSUE THREAD

**Issue by ericlau792** [modoboa/modoboa-installer#540]
# Impacted versions

* Distribution: Debian 
* Codename: Bullseye
* Arch:  64 Bits

# Steps to reproduce
modoboa-installer (run.py)
# Full trace using --debug option or current behaviour

Failed to get version of modoboa. Output is: b"sudo: utilisateur inconnu\xc2\xa0: modoboa\nsudo: erreur \xc3\xa0 l'initialisation du greffon d'audit sudoers_audit\n"

Installation stopped

Do you have any idea ?
Thanks

**Comment by tonioo** [comment]
@ericlau792 Do you have any logs to show?
