### ISSUE TITLE
Cant create letsencrypt certificate

### ISSUE THREAD

**Issue by enzoDev3** [modoboa/modoboa-installer#544]
* Distribution: Debian 
* Arm 64 Bits
* Database: PostgreSQL 

when i try to install with ssl cercificate its not finding the domain ip and its propagated to all internet servers

-i cant open nginx / i dont have nginx open if that is a problem
i cant open nginx because " nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/mail.example.com"
this is not the first run 
 i tried open port 80 on a basic web server and says "Problem binding to port 80: Could not bind to IPv4 or IPv6.
Can't open /etc/letsencrypt/renewal/mail.example.com.conf: No such file or directory."

# Expected behavior

![image](https://github.com/modoboa/modoboa-installer/assets/165719801/6b99abba-ab54-4786-b5f9-9327388dbc9f)
![image](https://github.com/modoboa/modoboa-installer/assets/165719801/34685b65-bd9c-409b-af66-74602d46def4)

**Comment by enzoDev3** [comment]
i tried to create the certificate with lego client (https://docs.bitnami.com/aws/apps/gitlab/administration/generate-configure-certificate-letsencrypt/) and i get the same problem 
![image](https://github.com/modoboa/modoboa-installer/assets/165719801/295c82db-5b2e-43e5-bedb-a1e92ca5e601)

**Comment by tonioo** [comment]
Looks like there is something wrong with your local resolution
