### ISSUE TITLE
I have finally succeeded in installing Modoboa using the modoboa-installer. However, I still have the following question I would like to ask.

### ISSUE THREAD

**Issue by lenmao** [modoboa/modoboa-installer#547]
# Impacted versions

* Distribution: Ubuntu 
* Codename: Jessie 
* Arch:  64 Bits
* Database: PostgreSQL

# Steps to reproduce

# Full trace using --debug option or current behaviour

# Expected behavior

# Video/Screenshot link (optional)

The Modoboa installed by the modoboa-installer script has fewer locales and libraries compared to what's in the Modoboa repository. How can I manually add them? Thank you.

**Comment by tonioo** [comment]
@lenmao What do you mean by less locales and libraries? Can you give an example?
