### ISSUE TITLE
how can i uninstall this ?

### ISSUE THREAD

**Issue by linbet-2024** [modoboa/modoboa-installer#550]
i can't find anything about how to uninstall it ,and the '  -- ' is not useable
`options:
  -h, --help            show this help message and exit
  --debug               Enable debug output
  --force               Force installation
  --configfile CONFIGFILE
                        Configuration file to use
  --version {latest,1.8.1,1.8.2,1.8.3,1.9.0,2.1.0}
                        Modoboa version to install
  --stop-after-configfile-check
                        Check configuration, generate it if needed and exit
  --interactive         Generate configuration file with user interaction
  --upgrade             Run the installer in upgrade mode
  --beta                Install latest beta release of Modoboa instead of the stable one
  --backup-path path    To use with --silent-backup, you must provide a valid path
  --backup              Backing up interactively previously installed instance
  --silent-backup       For script usage, do not require user interaction backup will be saved at ./modoboa_backup/Backup_M_Y_d_H_M if --backup-path is
                        not provided
  --restore path        Restore a previously backup up modoboa instance on a NEW machine. You MUST provide backup directory
root@VM71738:~/modoboa-installer# ./run.py   --interactive 
usage: run.py [-h] [--debug] [--force] [--configfile CONFIGFILE] [--version {latest,1.8.1,1.8.2,1.8.3,1.9.0,2.1.0}] [--stop-after-configfile-check]
              [--interactive] [--upgrade] [--beta] [--backup-path path] [--backup] [--silent-backup] [--restore path]
              domain
run.py: error: the following arguments are required: domain
root@VM71738:~/modoboa-installer# ./run.py   --
usage: run.py [-h] [--debug] [--force] [--configfile CONFIGFILE] [--version {latest,1.8.1,1.8.2,1.8.3,1.9.0,2.1.0}] [--stop-after-configfile-check]
              [--interactive] [--upgrade] [--beta] [--backup-path path] [--backup] [--silent-backup] [--restore path]
              domain
run.py: error: the following arguments are required: domain
`

**Comment by Spitfireap** [comment]
There is uninstall feature and it is not yet planned.
