### ISSUE TITLE
SSL cert and key inverted in installer

### ISSUE THREAD

**Issue by zenixLR** [modoboa/modoboa-installer#553]
Hi,
there is a small bug in ssl.py when we provide a manual cert and key file, they are inverted in the assignation code.
Then all config files that use them (postfix, dovecot and nginx) got inverted too..
Here is the bad swap:
https://github.com/modoboa/modoboa-installer/blob/e45a07f8cf4275ba88b7b89d1d44461007229526/modoboa_installer/ssl.py#L38-L41

And thanks a lot for the good work you'd done with modoboa, I love it!

**Comment by muslu** [comment]
And...

must be change READ.me

If you want to use already generated certs, simply edit the installer.cfg file and modify the following settings:

```
[certificate]
generate = true
type = manual
tls_cert_file_path = *path to tls key file*
tls_key_file_path = * path to tls fullchain file*
```
