### ISSUE TITLE
SORBS DNS deny list is depreciated

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#558]
The SORBS DNS deny list has been closed.

- https://www.mail-archive.com/mailop@mailop.org/msg22064.html

We need to remove this line from our template

https://github.com/modoboa/modoboa-installer/blob/ec12104f4427db7ade1c25eb782ab13927f97328/modoboa_installer/scripts/files/postfix/main.cf.tpl#L153

Installations need to be patched manually.

**Comment by Spitfireap** [comment]
Hi, can you open a PR ?

**Comment by tonioo** [comment]
See #559
