### ISSUE TITLE
clamd on debian 8

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#57]
There is an issue with the `clamav` package on debian 8.
As I suppose the `modoboa-installer` is the most official distribution, I am reporting here.

Commenting out `AllowSupplementaryGroups` helps.

---
- https://www.howtoforge.com/community/threads/clamav-daemon-stopped-working-with-update-to-version-0-99.73172/

**Comment by tonioo** [comment]
Looks like this issue has been fixed by the maintainer:
```
clamav (0.99.2+dfsg-0+deb8u2) stable; urgency=medium

  * Don't fail if AllowSupplementaryGroups is still set in the config file but
    ignore it and continue (Closes: #826406).

 -- Sebastian Andrzej Siewior <sebastian@breakpoint.cc>  Mon, 06 Jun 2016 22:06:52 +0200
```
