### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by jodumont** [modoboa/modoboa-installer#58]
Hi;
I hope I'm just a bad code reader and what I interpret it's not what happening
So I understood all password are password ?
If it's true; it is possible to use one of those technique to add some salt and pepper on those password ;)
http://www.howtogeek.com/howto/30184/10-ways-to-generate-a-random-password-from-the-command-line/

For the rest this installer and this packaging is just awesome ;)

**Comment by tonioo** [comment]
Hi,
the default password used for the initial super admin and the domain administrators created automatically (when creating new domains) is actually "password". About the installer, all passwords (database users, etc.) can be changed, just look at the installer.cfg file.

**Comment by tonioo** [comment]
@jodumont Does it answer your question ?

**Comment by tonioo** [comment]
@jodumont ping

**Comment by almereyda** [comment]
This discussion may as well link to the following upstream issues:

1. https://github.com/tonioo/modoboa/issues/892
2. https://github.com/tonioo/modoboa/issues/966
3. https://github.com/tonioo/modoboa/issues/634

**Comment by CyberfoxDK** [comment]
If it is not to much work, an integration to clickatell or other sms providers could be nice.
This way, when generating a password, there could be a checkmark, allowing password to be delivered to sms instead of pdf.
This option could also be used ot provide two factor authentication when logging in to webmail.

But my real request...   where do i change the standard password for generating accounts ?
Would like somthing other than password.

**Comment by tonioo** [comment]
I need to take a look into but I guess those services aren't free, right?
About the default password, you change change the ones used by the installer (look at the installer.cfg file) but if you're talking about domain administrators, it can't be changed for now. Maybe a new option in the admin panel, something like "Default password for generated accounts" would be a first answer?

**Comment by CyberfoxDK** [comment]
That would be great. (an option to change default passwords)

 

Regarding two factor authentication, no the providers are not free….   But  I bet, that if the option to use two factor authentication was available, many would use it.
Basically it would pass a token through http command, and wait for the token input, as well as a http connector of cause.

 

Work with both smspasscode (now censornet) and RSA Authentication manager..   

 

Might not be top-of-priorities, but a feature request sill J

 

Have a great day !

 

Fra: Antoine Nguyen [mailto:notifications@github.com] 
Sendt: 16. januar 2017 09:14
Til: modoboa/modoboa-installer
Cc: CyberfoxDK; Comment
Emne: Re: [modoboa/modoboa-installer] Password (#58)

 

I need to take a look into but I guess those services aren't free, right?
About the default password, you change change the ones used by the installer (look at the installer.cfg file) but if you're talking about domain administrators, it can't be changed for now. Maybe a new option in the admin panel, something like "Default password for generated accounts" would be a first answer?

**Comment by jodumont** [comment]
Yes! thank @tonioo and sorry for the delay ;)

**Comment by tonioo** [comment]
Closing this issue since this original issue is resolved. Do not hesitate to open a new one (in modoboa repository) about 2-factor authentication.
