### ISSUE TITLE
Installing on a fresh Debian install fails, give HTTP error 400

### ISSUE THREAD

**Issue by thatging3rkid** [modoboa/modoboa-installer#63]
As the title states, if I try installing onto a fresh Debian 8 install, I get a Bad Request, and no error is logged in the nginx log file. I have tried using w3m to access it locally, IE (don't ask) on a network pc, and Chrome over an nginx reverse proxy (it's final configuration) and all fail. I can provide any log files if needed. 

After reading #61, I do have python-pip installed, and I am getting similar issues if I try removing the /srv/modoboa directory. My first install without --debug took ~20 minutes and did not have any errors. I tried adding os.makedirs over os.makedir in utils.py and installation says it was successful. But, nginx now gives a 503 Bad Gateway in all three test locations/browsers. In the nginx error log, it now says that uwsgi refuses the connection.

**Comment by tonioo** [comment]
Hi,
what hostname did you use to install modoboa ? Are you using the same to access the web interface ?

**Comment by thatging3rkid** [comment]
Yeah, and I get a 502 Bad Gateway.

**Comment by tonioo** [comment]
Ok. Can you set DEBUG to True inside `/srv/modoboa/instance/instance/settings.py`, reload uwsgi and retry ? You should get more information.

**Comment by thatging3rkid** [comment]
I actually did not have any files in `/srv/modoboa`, only some directories, and `/srv/modoboa` was owned by root. I then changed the owner and permissions to modoboa and 755 respectively and reinstalled. Now, it works! Do you want me to make a PR with code to fix this?

**Comment by tonioo** [comment]
Have you found where the issue could be ?

**Comment by thatging3rkid** [comment]
I think the issue is in `utils.mkdir`, it needs to use `os.makedirs` if applicable. I was also gonna throw in a check if pip in installed, it seems like that was an issue in #61.

**Comment by tonioo** [comment]
That's strange because the /srv/modoboa directory should be created by the `adduser` command (home directory for user modoboa) and so permissions should be applied too... You tried to install on a fresh OS ?

**Comment by thatging3rkid** [comment]
My current working version is on a Frankenstein OS, I've been tinkering with it, trying to make it work, so I might have broken something in the process. I was gonna make a new VM and try installing from scratch with my fork of the code, and see how it goes.

**Comment by almereyda** [comment]
This has once resulted into a Pull Request at #66.
