### ISSUE TITLE
same old no such file or directory : '/srv/modoboa'

### ISSUE THREAD

**Issue by guillaumedk** [modoboa/modoboa-installer#67]
Hello ! so i'm really not used to github so if i'm doing stuff wrong, kick me out, but with a note of how should i do thing ^^'

i try to install modoboa with the installer script on a vm with 2go of ram and debian jessie.
i create a user name modoboa in sudoer, but i did get the same result with the root account.

i try to find similar issue on the web, but only found 2015 post with a commit solving the issue....

here is the "log" i get, i only switch to mysql in the install.cfg

```
modoboa@Modoboa:~/modoboa-installer$ sudo ./run.py test.domain.com --debug
[sudo] password for modoboa: 
Welcome to Modoboa installer!
Your mail server test.domain.com will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Ign http://ftp.fr.debian.org jessie InRelease
Get:1 http://ftp.fr.debian.org jessie-updates InRelease [145 kB]
Hit http://ftp.fr.debian.org jessie Release.gpg
Hit http://ftp.fr.debian.org jessie Release
Get:2 http://ftp.fr.debian.org jessie-updates/main Sources [15.5 kB]
Get:3 http://ftp.fr.debian.org jessie-updates/main i386 Packages/DiffIndex [5,932 B]
Get:4 http://ftp.fr.debian.org jessie-updates/main Translation-en/DiffIndex [2,704 B]
Hit http://ftp.fr.debian.org jessie/main Sources
Hit http://ftp.fr.debian.org jessie/main i386 Packages
Hit http://ftp.fr.debian.org jessie/main Translation-en
Hit http://security.debian.org jessie/updates InRelease
Hit http://security.debian.org jessie/updates/main Sources
Hit http://security.debian.org jessie/updates/main i386 Packages
Hit http://security.debian.org jessie/updates/main Translation-en
Fetched 169 kB in 10s (16.9 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
sudo is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Overwrite the existing SSL certificate? (y/N) y
Generating new self-signed certificate
Generating a 4096 bit RSA private key
................................................................................++
.......................................................................................++
writing new private key to '/etc/ssl/private/test.domain.com.key'
-----
Installing modoboa
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version.
cron is already the newest version.
libffi-dev is already the newest version.
libjpeg-dev is already the newest version.
libxml2-dev is already the newest version.
libxslt1-dev is already the newest version.
python-dev is already the newest version.
librrd-dev is already the newest version.
rrdtool is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
libmysqlclient-dev is already the newest version.
mysql-server is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'modoboa'@'%'
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'modoboa'@'localhost'
Reading package lists...
Building dependency tree...
Reading state information...
python-virtualenv is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Running virtualenv with interpreter /usr/bin/python2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2378, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 830, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 999, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1198, in install_python
    mkdir(lib_dir)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 451, in mkdir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/srv/modoboa'
-bash: /srv/modoboa/env/bin/pip: No such file or directory
-bash: /srv/modoboa/env/bin/pip: No such file or directory
Traceback (most recent call last):
  File "./run.py", line 73, in <module>
    main()
  File "./run.py", line 63, in main
    scripts.install("modoboa", config)
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/base.py", line 151, in run
    self.post_run()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 156, in post_run
    self._deploy_instance()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 110, in _deploy_instance
    sudo_user=self.user, cwd=self.home_dir)
  File "/home/modoboa/modoboa-installer/modoboa_installer/utils.py", line 61, in exec_cmd
    process = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/srv/modoboa'
```

on the long run i would like to install it "by hand" to understand it, but for now i just need to see if i can get it to work and if it useful in my case.

thank you for the awesome work on the project !

**Comment by thatging3rkid** [comment]
What is the output of `ls -lash /srv/modoboa`?

**Comment by guillaumedk** [comment]
well, when i do sudo ls -lash /srv/
total 8.0K
4.0K drwxr-xr-x  2 root root 4.0K Oct 27 20:51 .
4.0K drwxr-xr-x 21 root root 4.0K Oct 27 20:53 ..

but sudo ls -lash /srv/modoboa obviously give me
ls: cannot access /srv/modoboa: No such file or directory

**Comment by thatging3rkid** [comment]
What happens if you delete the directory or make the modoboa user and group the owner?

**Comment by guillaumedk** [comment]
so because there is no modoboa folder, i guess you were talking about the /srv/ folder.
if i delete it, that happens :
`modoboa@modoboa:~/modoboa-installer$ sudo ls -al /srv/
total 8
drwxr-xr-x  2 root root 4096 Oct 27 20:51 .
drwxr-xr-x 21 root root 4096 Oct 27 20:53 ..
modoboa@modoboa:~/modoboa-installer$ sudo rm -r /srv/
modoboa@modoboa:~/modoboa-installer$ sudo ./run.py modoboa.test.domain.com
Welcome to Modoboa installer!
Your mail server modoboa.test.domain.com will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing modoboa
Traceback (most recent call last):
  File "./run.py", line 73, in <module>
    main()
  File "./run.py", line 63, in main
    scripts.install("modoboa", config)
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/base.py", line 151, in run
    self.post_run()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 156, in post_run
    self._deploy_instance()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 110, in _deploy_instance
    sudo_user=self.user, cwd=self.home_dir)
  File "/home/modoboa/modoboa-installer/modoboa_installer/utils.py", line 61, in exec_cmd
    process = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/srv/modoboa'
modoboa@modoboa:~/modoboa-installer$ sudo ls -al /srv/
ls: cannot access /srv/: No such file or directory
`
if i chown it to the modoboa user, that happens : 
`modoboa@modoboa:~$ sudo chown modoboa:modoboa /srv/
modoboa@modoboa:~$ sudo ls -al /srv/
total 8
drwxr-xr-x  2 modoboa modoboa 4096 Oct 27 20:51 .
drwxr-xr-x 21 root    root    4096 Oct 27 20:53 ..
modoboa@modoboa:~$ cd modoboa-installer
modoboa@modoboa:~/modoboa-installer$ sudo ./run.py modoboa.test.domain.com
Welcome to Modoboa installer!
Your mail server modoboa.test.domain.com will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) Y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing modoboa
Traceback (most recent call last):
  File "./run.py", line 73, in <module>
    main()
  File "./run.py", line 63, in main
    scripts.install("modoboa", config)
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/base.py", line 151, in run
    self.post_run()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 157, in post_run
    self.apply_settings()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 132, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/home/modoboa/modoboa-installer/modoboa_installer/utils.py", line 79, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'
modoboa@modoboa:~/modoboa-installer$ ls -al /srv/modoboa/
total 20
drwxr-xr-x 5 modoboa modoboa 4096 Nov 12 11:21 .
drwxr-xr-x 3 modoboa modoboa 4096 Nov 12 11:18 ..
drwxr-xr-x 6 modoboa modoboa 4096 Nov 12 11:20 env
drwxr-x--- 2 modoboa modoboa 4096 Nov 12 11:21 pdfcredentials
drwxr-x--- 2 modoboa modoboa 4096 Nov 12 11:21 rrdfiles`

**Comment by guillaumedk** [comment]
don't know why but github refuse to put go in a new line this time

**Comment by thatging3rkid** [comment]
You could try my [fork](https://github.com/thatging3rkid/modoboa-installer) and see if that works. But, there may be a problem when installing `rrdtool`, so this installer might be broken at the minute. Try my fork and see if you get any results though.

**Comment by tonioo** [comment]
@guillaumedk any news about this ?

**Comment by guillaumedk** [comment]
@tonioo, I honestly didn't try the fork. I had my fair share of lost time with this and just cut the loss. I have tried the manual installation to but it was not precise enough for me to make it work. I can still try thing if needed.

**Comment by guillaumedk** [comment]
I will try again when I'm back home, I just see the new dependency.

**Comment by guillaumedk** [comment]
Not a single change from the first log ...

**Comment by tonioo** [comment]
Do you have a trace to show? (using the --debug option)

**Comment by thatging3rkid** [comment]
The pull request with the code to fix this has not been merged in yet, try [this fork](https://github.com/senner/modoboa-installer/tree/patch-1) (you should rename your original clone of the repo with `mv modoboa-installer modoboa-installer-back`, then do `git clone https://github.com/senner/modoboa-installer` then `cd modoboa-installer`, then `git checkout patch-1`)

**Comment by guillaumedk** [comment]
@tonioo i do but it's the exact same one as my first trace.

@thatging3rkid here is the log without --debug on a clean vm
```
modoboa@modoboa:~$ git clone https://github.com/senner/modoboa-installer
Cloning into 'modoboa-installer'...
remote: Counting objects: 579, done.
remote: Total 579 (delta 0), reused 0 (delta 0), pack-reused 579
Receiving objects: 100% (579/579), 131.80 KiB | 0 bytes/s, done.
Resolving deltas: 100% (373/373), done.
Checking connectivity... done.
modoboa@modoboa:~$ cd modoboa-installer/
modoboa@modoboa:~/modoboa-installer$ git checkout patch-1 
Branch patch-1 set up to track remote branch patch-1 from origin.
Switched to a new branch patch-1
modoboa@modoboa:~/modoboa-installer$ ./run.py modoboa.test.domain.com
Welcome to Modoboa installer!
Your mail server modoboa.test.domain.com will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) Y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing modoboa
Traceback (most recent call last):
  File "./run.py", line 73, in <module>
    main()
  File "./run.py", line 63, in main
    scripts.install("modoboa", config)
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/base.py", line 164, in run
    self.create_user()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/base.py", line 94, in create_user
    self._chown(path, uid, gid)
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/base.py", line 72, in _chown
    os.chown(path, uid, gid)
OSError: [Errno 2] No such file or directory: '/srv/modoboa'

```

**Comment by thatging3rkid** [comment]
You need to use `sudo ./run.py <domain name>`

**Comment by guillaumedk** [comment]
I feel dumb, this is what happens when you try to compute after a long day
of work. Sorry...

**Comment by thatging3rkid** [comment]
Don't worry about it, we've all made mistakes like that after long days. The more important question is, did it work?

**Comment by guillaumedk** [comment]
Still at work, i replied at 8am and it's 7pm right now. The times to get
back and eat a thing and I will tell you ;-)

**Comment by guillaumedk** [comment]
sorry i really didn't had time ....
```
sudo ./run.py modoboa.test.domain.com
[sudo] password for modoboa: 
Welcome to Modoboa installer!
Your mail server modoboa.test.domain.com will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing modoboa
Traceback (most recent call last):
  File "./run.py", line 73, in <module>
    main()
  File "./run.py", line 63, in main
    scripts.install("modoboa", config)
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/base.py", line 164, in run
    self.create_user()
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/base.py", line 94, in create_user
    self._chown(path, uid, gid)
  File "/home/modoboa/modoboa-installer/modoboa_installer/scripts/base.py", line 72, in _chown
    os.chown(path, uid, gid)
OSError: [Errno 2] No such file or directory: '/srv/modoboa'
```
sudoing the script didn't help.

**Comment by tonioo** [comment]
Looks like the modoboa system user already exists on your system.

Can you check that ? If it exists then remove it and relaunch the
installer like this:

$ sudo  ./run.py modoboa.test.domain.com --debug

**Comment by guillaumedk** [comment]
but i have run the script with a modoboa user since the begin !
> i create a user name modoboa in sudoer, but i did get the same result with the root account.

what the point to run the script with sudo if you don't use another account than root ?

```
root@modoboa:~# userdel modoboa
root@modoboa:~# cd /home/modoboa/modoboa-installer/
root@modoboa:/home/modoboa/modoboa-installer# sudo ./run.py modoboa.test.domain.com
Welcome to Modoboa installer!
Your mail server modoboa.test.domain.com will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Overwrite the existing SSL certificate? (y/N) y
Generating new self-signed certificate
Installing modoboa
Installing uwsgi
Installing nginx
Installing postfix
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing dovecot
Congratulations! You can enjoy Modoboa at https://modoboa.test.domain.com (admin:password)
```
it did work. with @thatging3rkid fork, will try with the original during the day.

**Comment by tonioo** [comment]
The installer is supposed to create this user, that's maybe why it fails since the beginning...

**Comment by guillaumedk** [comment]
that's my guess ... there isn't any warning about that anywhere sadly

**Comment by tonioo** [comment]
Indeed, but the documentation never says to create a modoboa user before starting the installer...

**Comment by thatging3rkid** [comment]
Did you test it in your browser? Sometimes the script says it was successful, but there is a problem with your uwsgi config.

**Comment by guillaumedk** [comment]
i can confirm that the webserver work. i would recommend adding a check for modoboa user, i know it's my mistake, but i'm sure other will do it. (i hope soo, would feel dumb if i was alone XD)

**Comment by tonioo** [comment]
Ok, I'll add something. I close this issue and create a new one.
