### ISSUE TITLE
Installer fails on CentOS 7 due to an error in installing rrdtool using pip

### ISSUE THREAD

**Issue by m3t4lukas** [modoboa/modoboa-installer#68]
I think the --debug output says more than I can say.
I already tried installing the yum package rrdtool-python.

[modoboa-installer_output.txt](https://github.com/modoboa/modoboa-installer/files/585714/modoboa-installer_output.txt)

**Comment by tonioo** [comment]
Looks like the rrdtool extension has been updated yesterday (0.1.7, the one you installed) and is broken due to a compilation issue (https://github.com/commx/python-rrdtool/commit/22476ba2fcdded7e3ee7d3f1ed323229d9a308ce).
A new version has been released today (0.1.8) and should fix your issue.
Could you try with the new version please ?

**Comment by m3t4lukas** [comment]
It looks like now that the include issue is fixed, they missed a c99 or c11 switch in their build definition. Still not able to compile using version 0.1.8. I just posted an issue on https://github.com/commx/python-rrdtool so they can fix their build process.
I will try to somehow set c99 as my default.

**Comment by m3t4lukas** [comment]
I now tried again after following these steps: [http://stackoverflow.com/a/26600693](http://stackoverflow.com/a/26600693). It is not a permanent solutions by any means. But for anyone facing the same problem, you can get it to run that way.

Btw: @Antoine: thanks for that really nice piece of software

**Comment by pavinjosdev** [comment]
m3t4lukas, thank you for the fix; can confirm it works!

**Comment by m3t4lukas** [comment]
The issue should have boon fixed now, as the dev of python-rrdtool states [https://github.com/commx/python-rrdtool/issues/15](https://github.com/commx/python-rrdtool/issues/15).
Anyone evaluate please?

**Comment by tonioo** [comment]
It is fixed with version 0.1.11 of rrdtool. I made it the minimum required version.
