### ISSUE TITLE
Adding the Radicale extension doesn't invoke Radicale installation

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#72]
A simple expectation for the installer could be to be as declarative as possible, shortly speaking using *sane defaults*. Likely if I am already handing over a machine to this script, it shall resolve dependencies automatically. Thus, adding the Radicale extension to `installer.cfg` could by itself take care of the sufficient dependency.

**Comment by tonioo** [comment]
That's something I plan to do but I need time and it looks like Radicale is beeing deeply rewritten...

**Comment by almereyda** [comment]
Also my `postmaster@email.ecobytes.net` mailbox (the former `admin`) now contains 20000 messages from cron, sent every 5 minutes, stating:

```
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 10, in 
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_radicale/management/commands/generate_rights.py", line 17, in 
    class Command(BaseCommand):
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_radicale/management/commands/generate_rights.py", line 23, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

I will remove it for now, and probably users already have ownCloud for Calendars and Contacts.

**Comment by tonioo** [comment]
@almereyda That's strange, what django version are you using?

**Comment by almereyda** [comment]
Following maintenance routines as in https://github.com/modoboa/modoboa-installer/issues/39#issuecomment-235992040, we are currently on `Django (1.9.12)`.

**Comment by tonioo** [comment]
Are you sure that the cron script uses the right virtualenv? The `option_list` atttribute has been indeed deprecated and is not present anymore with version 1.10 of Django. But it is still present with the 1.9.x branch...

**Comment by tonioo** [comment]
@almereyda Any news about this issue, I still don't manage to reproduce it...

**Comment by CyberfoxDK** [comment]
I noticed the same issue.

**Comment by tonioo** [comment]
@CyberfoxDK Are you talking about the option_list error ? Can you describe your environment please?

**Comment by CyberfoxDK** [comment]
Enviroment is Ubuntu 14.04 installed with modoboa-installer.

No changes or customizations have been made.

 

 

 

Fra: Antoine Nguyen [mailto:notifications@github.com] 
Sendt: 19. januar 2017 20:23
Til: modoboa/modoboa-installer
Cc: CyberfoxDK; Mention
Emne: Re: [modoboa/modoboa-installer] Adding the Radicale extension doesn't invoke Radicale installation (#72)

 

@CyberfoxDK <https://github.com/CyberfoxDK>  Are you talking about the option_list error ? Can you describe your environment please?

**Comment by tonioo** [comment]
@CyberfoxDK Have you added the radicale extension manually?

**Comment by CyberfoxDK** [comment]
no it was through pip as an extension

**Comment by tonioo** [comment]
But after the installation? Or have you modified the config file before the first run?

**Comment by CyberfoxDK** [comment]
After the initial installation.

 

Fra: Antoine Nguyen [mailto:notifications@github.com] 
Sendt: 20. januar 2017 17:17
Til: modoboa/modoboa-installer
Cc: CyberfoxDK; Mention
Emne: Re: [modoboa/modoboa-installer] Adding the Radicale extension doesn't invoke Radicale installation (#72)

 

But after the installation? Or have you modified the config file before the first run?

**Comment by tonioo** [comment]
@CyberfoxDK Could you describe how you installed it? I don't reproduce your issue...

**Comment by CyberfoxDK** [comment]
installed modoboa using the installer.
followed the guidelines for extensions, using pip to try to install radicle

i will try again on my new server running 1.6.3

**Comment by tonioo** [comment]
Have you installed the package inside the virtualenv?

**Comment by CyberfoxDK** [comment]
No, no virtualenv on my ubuntu.
Thought that pip did the installation ?
pip install <EXTENSION>==<VERSION>

**Comment by CyberfoxDK** [comment]
Would the virtualenv  be  
/srv/modoboa/env$     ?

**Comment by tonioo** [comment]
Yes.Le 20 janv. 2017 7:14 PM, CyberfoxDK <notifications@github.com> a écrit :Would the virtualenv  be
/srv/modoboa/env$     ?

**Comment by CyberfoxDK** [comment]
Just tryed again, following this guide, step by step.
https://github.com/modoboa/modoboa-radicale

after reboot, i get "internal server error"

**Comment by tonioo** [comment]
Make sure to follow this procedure to install the plugin:
http://modoboa.readthedocs.io/en/latest/installation.html#extensions.

In your case, the user is modoboa and the virtualenv path is
/srv/modoboa/env. The instance dir is /srv/modoboa/instance.

About the internal error, you can enable debug traces by setting DEBUG
to True inside settings.py. Do not forget to reload uwsgi.

**Comment by CyberfoxDK** [comment]
I followed stepbystep, and no internal server error.

Then i added the 'modoboa_radicale', to the settings.py   rebooted, and reault = internal server error.
removed the line from settings.py = no internal server error.

**Comment by tonioo** [comment]
Have you tried with debug traces enabled?

**Comment by CyberfoxDK** [comment]
yes, but in doubt what logfile to look at.
syslog does not seem to contain anything.

**Comment by tonioo** [comment]
Looks like the package was not installed inside the virtualenv...

**Comment by CyberfoxDK** [comment]
okey, back to start.
`
running "sudo -i modoboa"   fails    but you wrote earlier,   

"sudo -u modoboa -i"
$ /srv/modoboa/env/bin/activate
-sh: 1: /srv/modoboa/env/bin/activate: Permission denied
$
'

(Its a steep learningcurve...)

**Comment by CyberfoxDK** [comment]
okey so it must be like this.
`
sudo -i -u modoboa
$
$bash
modoboa@mail:~$ cd /srv/modoboa/env
modoboa@mail:~/env$ . bin/activate
(env)modoboa@mail:~/env$
'
this should bring me into the virtual env.  (i hope)

**Comment by CyberfoxDK** [comment]
This fixed the issue ! 
Tonioo - Thank you very much for your help, and your patiance !
I really appreciate it !

**Comment by CyberfoxDK** [comment]
Well i looks like there is some right issues now..
Tried to follow this, https://github.com/modoboa/modoboa-radicale/blob/master/docs/setup.rst    but i must admit, that there apparent is a lot of implied knowledge regarding editing these files..
when creating a calendar in modoboa webinterface, nothing happens after clicking "next"

**Comment by CyberfoxDK** [comment]
I must be doing somthing wrong...

`(env)modoboa@mail:~/env/bin$ python /srv/modoboa/instance/manage.py generate_rights
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_radicale/management/commands/generate_rights.py", line 117, in handle
    self._generate_file(path)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_radicale/management/commands/generate_rights.py", line 79, in _generate_file
    self._cfgfile = open(target, "w")
IOError: [Errno 2] No such file or directory: u'/etc/modoboa_radicale/rights'
(env)modoboa@mail:~/env/bin$
`

**Comment by CyberfoxDK** [comment]
Case closed from my side -  found the solution.
the folder /etc/modoboa_radicale was missing.
once created manually, the rights file was populated.

Also, these steps (1), were to be done while in "sudo -i -u modoboa" enviroment, and i had not done that.

(1)
$ cd <modoboa_instance_dir>
$ python manage.py migrate
$ python manage.py load_initial_data
$ python manage.py collectstatic

**Comment by CyberfoxDK** [comment]
(Should i write a new in modoboa_radicale.  i kind of hijacked this thread, and thats not polite)

well so far so good (this is almost becomming my diary...)   i can now create calendars, and assign rights.
But a other issue has appered..
The calendar url link, does not end on .ics
The url should be     "https://mail.svendsen.me/svendsen.me/user/henrik/asdf"  but the message at that webpage is "Sorry the requested page does not exist".
Learning more every day,,    will update when i discover somthing new.

**Comment by tonioo** [comment]
The path you created is the default one but you can change it (using the online panel). I guess the installer should create this directory when the radicale is beeing installed...
Just one stupid question: have you installed Radicale?

**Comment by CyberfoxDK** [comment]
as i understand, im installing radicale when using the "pip install modoboa_radicale"
If thats correct, then yes.

**Comment by tonioo** [comment]
Unfortunately, no. Radicale is a separate component and the installer does not setup it yet. When you run the command you describe, you're just installing the modoboa extension which allows calendar management.

**Comment by CyberfoxDK** [comment]
Well then i makes sense J

**Comment by tonioo** [comment]
Support for Radicale has been added to the installer.
