### ISSUE TITLE
Hardcoded settings.py values

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#73]
The upgrade instructions suggest to customise ones API URL. Yet they are hardcoded to

```
LANGUAGE_CODE = 'en-us'

SWAGGER_SETTINGS = {
    "is_authenticated": False,
    "api_version": "1.0",
    "exclude_namespaces": [],
    "info": {
        "contact": "contact@modoboa.com",
        "description": ("Modoboa API, requires a valid token."),
        "title": "Modoboa API",
    }
}

# Modoboa settings
#MODOBOA_CUSTOM_LOGO = os.path.join(MEDIA_URL, "custom_logo.png")

#DOVECOT_LOOKUP_PATH = ('/path/to/dovecot', )

MODOBOA_API_URL = 'https://api.modoboa.org/1/'
```

Does this require custom templates or is it advisable for all users to have access to these variables via the installer?

Also: Does one need a translation project (a.k.a. Transifex, Weblate) into multiple languages?

**Comment by almereyda** [comment]
Could be linked to https://github.com/tonioo/modoboa/issues/594

**Comment by tonioo** [comment]
There are only three settings that could be managed through the installer or the web interface (as tonioo/modoboa#594 is): LANGUAGE_CODE, MODOBOA_CUSTOM_LOGO and DOVECOT_LOOKUP_PATH. The others are not supposed to be changed.

I don't understand your point about a translation project. Are you talking about this: https://www.transifex.com/tonio/modoboa/ ?

**Comment by tonioo** [comment]
@almereyda ping

**Comment by figassis** [comment]
There are quite a few settings that could (should?) be customizable in the admin UI. For example, the admin dashboard feed URL is set to modoboa's latest news, but this is only useful for the superadmins and not domain admins or resellers, which should be able to see whatever feed the superadmin sets for them.

Right now I can change it in env/lib/python2.7/site-packages/modoboa/core/views/dashboard.pyc, but of course it will be gone by the next upgrade.
