### ISSUE TITLE
SSL Labs grade C

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#75]
After running the SSL Labs test against Modoboa, I am astonished about the [C result for our server](https://www.ssllabs.com/ssltest/analyze.html?d=email.ecobytes.net&hideResults=on).

Hardening the nginx, postfix and dovecot TLS configuration may appear useful here.

**Comment by tonioo** [comment]
@almereyda What you think about those modifications?

**Comment by jprasmussen** [comment]
Manually applied these changes and my SSL Labs test Gives me an A. So I'd say it's good to go into the installer.

**Comment by almereyda** [comment]
Hadn't seen this, good progress indeed.
