### ISSUE TITLE
Unable to Install Modoboa - Unable to create directory

### ISSUE THREAD

**Issue by tei06398** [modoboa/modoboa-installer#77]
Traceback and steps leading to traceback:

```
user@server:~$ cd modoboa-installer/
user@server:~/modoboa-installer$ sudo python run.py deceptionhub.pro
[sudo] password for user:
Welcome to Modoboa installer!
Your mail server domain.tld will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Overwrite the existing SSL certificate? (y/N) y
Generating new self-signed certificate
Installing modoboa
Traceback (most recent call last):
  File "run.py", line 73, in <module>
    main()
  File "run.py", line 63, in main
    scripts.install("modoboa", config)
  File "/home/user/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/user/modoboa-installer/modoboa_installer/scripts/base.py", line 151, in run
    self.post_run()
  File "/home/user/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 156, in post_run
    self._deploy_instance()
  File "/home/user/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 110, in _deploy_instance
    sudo_user=self.user, cwd=self.home_dir)
  File "/home/user/modoboa-installer/modoboa_installer/utils.py", line 61, in exec_cmd
    process = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/srv/modoboa'
```
What exactly can I do to make this work?
Distro: Ubuntu Server 14.04 LTS 64-bit

**Comment by tei06398** [comment]
Distro: Ubuntu Server 14.04 LTS 64-bit

**Comment by tonioo** [comment]
Please make sure you did not create a 'modoboa' user before the installation. Then, run the installer using the --debug option.

**Comment by tei06398** [comment]
’inferno09@server:~$ deluser modoboa
/usr/sbin/deluser: Only root may remove a user or group from the system.
inferno09@server:~$ sudo deluser modoboa
[sudo] password for inferno09: 
/usr/sbin/deluser: The user `modoboa' does not exist.
inferno09@server:~$ cd modoboa-installer/
inferno09@server:~/modoboa-installer$ sudo python run.py deceptionhub.pro --debug
Welcome to Modoboa installer!
Your mail server deceptionhub.pro will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Get:1 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
Ign http://gb.archive.ubuntu.com trusty InRelease
Get:2 http://gb.archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Hit http://download.virtualbox.org trusty InRelease
Hit http://download.virtualbox.org trusty/contrib amd64 Packages
Get:3 http://security.ubuntu.com trusty-security/main Sources [124 kB]
Hit http://gb.archive.ubuntu.com trusty-backports InRelease
Hit http://gb.archive.ubuntu.com trusty Release.gpg
Hit http://download.virtualbox.org trusty/contrib i386 Packages
Get:4 http://gb.archive.ubuntu.com trusty-updates/main Sources [387 kB]
Get:5 http://security.ubuntu.com trusty-security/restricted Sources [4,613 B]
Ign http://repos.azulsystems.com stable InRelease
Get:6 http://security.ubuntu.com trusty-security/universe Sources [46.3 kB]
Get:7 http://security.ubuntu.com trusty-security/multiverse Sources [3,207 B]
Get:8 http://security.ubuntu.com trusty-security/main amd64 Packages [566 kB]
Hit http://repos.azulsystems.com stable Release.gpg
Hit http://repos.azulsystems.com stable Release
Hit http://repos.azulsystems.com stable/main amd64 Packages
Hit http://repos.azulsystems.com stable/main i386 Packages
Get:9 http://gb.archive.ubuntu.com trusty-updates/restricted Sources [5,888 B]
Get:10 http://gb.archive.ubuntu.com trusty-updates/universe Sources [170 kB]
Ign http://download.virtualbox.org trusty/contrib Translation-en_GB
Ign http://download.virtualbox.org trusty/contrib Translation-en
Get:11 http://gb.archive.ubuntu.com trusty-updates/multiverse Sources [7,522 B]
Get:12 http://gb.archive.ubuntu.com trusty-updates/main amd64 Packages [929 kB]
Get:13 http://security.ubuntu.com trusty-security/restricted amd64 Packages [13.3 kB]
Get:14 http://security.ubuntu.com trusty-security/universe amd64 Packages [146 kB]
Get:15 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [4,138 B]
Get:16 http://security.ubuntu.com trusty-security/main i386 Packages [523 kB]
Hit https://repo.zimbra.com trusty InRelease
Get:17 http://security.ubuntu.com trusty-security/restricted i386 Packages [13.1 kB]
Get:18 http://gb.archive.ubuntu.com trusty-updates/restricted amd64 Packages [16.4 kB]
Get:19 http://security.ubuntu.com trusty-security/universe i386 Packages [146 kB]
Get:20 http://gb.archive.ubuntu.com trusty-updates/universe amd64 Packages [390 kB]
Get:21 http://security.ubuntu.com trusty-security/multiverse i386 Packages [4,289 B]
Get:22 http://security.ubuntu.com trusty-security/main Translation-en [311 kB]
Get:23 http://gb.archive.ubuntu.com trusty-updates/multiverse amd64 Packages [14.0 kB]
Get:24 http://security.ubuntu.com trusty-security/multiverse Translation-en [2,201 B]
Get:25 http://gb.archive.ubuntu.com trusty-updates/main i386 Packages [889 kB]
Get:26 http://security.ubuntu.com trusty-security/restricted Translation-en [3,349 B]
Get:27 http://security.ubuntu.com trusty-security/universe Translation-en [86.1 kB]
Hit https://repo.zimbra.com trusty/zimbra Sources
Get:28 http://gb.archive.ubuntu.com trusty-updates/restricted i386 Packages [16.2 kB]
Get:29 http://gb.archive.ubuntu.com trusty-updates/universe i386 Packages [392 kB]
Get:30 http://gb.archive.ubuntu.com trusty-updates/multiverse i386 Packages [14.5 kB]
Get:31 http://gb.archive.ubuntu.com trusty-updates/main Translation-en [452 kB]
Get:32 http://gb.archive.ubuntu.com trusty-updates/multiverse Translation-en [7,340 B]
Hit https://repo.zimbra.com trusty/zimbra amd64 Packages
Get:33 http://gb.archive.ubuntu.com trusty-updates/restricted Translation-en [3,842 B]
Get:34 http://gb.archive.ubuntu.com trusty-updates/universe Translation-en [206 kB]
Ign http://repos.azulsystems.com stable/main Translation-en_GB
Hit http://gb.archive.ubuntu.com trusty-backports/main Sources
Hit http://gb.archive.ubuntu.com trusty-backports/restricted Sources
Hit http://gb.archive.ubuntu.com trusty-backports/universe Sources
Hit http://gb.archive.ubuntu.com trusty-backports/multiverse Sources
Hit http://gb.archive.ubuntu.com trusty-backports/main amd64 Packages
Hit http://gb.archive.ubuntu.com trusty-backports/restricted amd64 Packages
Ign http://repos.azulsystems.com stable/main Translation-en
Hit http://gb.archive.ubuntu.com trusty-backports/universe amd64 Packages
Hit http://gb.archive.ubuntu.com trusty-backports/multiverse amd64 Packages
Hit http://gb.archive.ubuntu.com trusty-backports/main i386 Packages
Hit http://gb.archive.ubuntu.com trusty-backports/restricted i386 Packages
Hit http://gb.archive.ubuntu.com trusty-backports/universe i386 Packages
Hit http://gb.archive.ubuntu.com trusty-backports/multiverse i386 Packages
Hit http://gb.archive.ubuntu.com trusty-backports/main Translation-en
Hit http://gb.archive.ubuntu.com trusty-backports/multiverse Translation-en
Hit http://gb.archive.ubuntu.com trusty-backports/restricted Translation-en
Hit http://gb.archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://gb.archive.ubuntu.com trusty Release
Hit http://gb.archive.ubuntu.com trusty/main SourcesHit http://gb.archive.ubuntu.com trusty/restricted Sources
Get:35 https://repo.zimbra.com trusty/zimbra Translation-en_GB
Hit http://gb.archive.ubuntu.com trusty/universe Sources
Hit http://gb.archive.ubuntu.com trusty/multiverse Sources
Hit http://gb.archive.ubuntu.com trusty/main amd64 Packages
Hit http://gb.archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://gb.archive.ubuntu.com trusty/universe amd64 Packages
Hit http://gb.archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://gb.archive.ubuntu.com trusty/main i386 Packages
Hit http://gb.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://gb.archive.ubuntu.com trusty/universe i386 Packages
Hit http://gb.archive.ubuntu.com trusty/multiverse i386 Packages
Get:36 https://repo.zimbra.com trusty/zimbra Translation-en
Hit http://gb.archive.ubuntu.com trusty/main Translation-en_GB
Hit http://gb.archive.ubuntu.com trusty/main Translation-en
Hit http://gb.archive.ubuntu.com trusty/multiverse Translation-en_GB
Hit http://gb.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://gb.archive.ubuntu.com trusty/restricted Translation-en_GB
Get:37 https://repo.zimbra.com trusty/zimbra Translation-en_GB
Hit http://gb.archive.ubuntu.com trusty/restricted Translation-en
Hit http://gb.archive.ubuntu.com trusty/universe Translation-en_GB
Hit http://gb.archive.ubuntu.com trusty/universe Translation-en
Get:38 https://repo.zimbra.com trusty/zimbra Translation-en
Get:39 https://repo.zimbra.com trusty/zimbra Translation-en_GB
Get:40 https://repo.zimbra.com trusty/zimbra Translation-en
Get:41 https://repo.zimbra.com trusty/zimbra Translation-en_GB
Get:42 https://repo.zimbra.com trusty/zimbra Translation-en
Get:43 https://repo.zimbra.com trusty/zimbra Translation-en_GB
Ign https://repo.zimbra.com trusty/zimbra Translation-en_GB
Get:44 https://repo.zimbra.com trusty/zimbra Translation-en
Ign https://repo.zimbra.com trusty/zimbra Translation-en
Fetched 6,029 kB in 4s (1,310 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
sudo is already the newest version.
The following package was automatically installed and is no longer required:
  libudev1:i386
Use 'apt-get autoremove' to remove it.
0 to upgrade, 0 to newly install, 0 to remove and 78 not to upgrade.
Overwrite the existing SSL certificate? (y/N) y
Generating new self-signed certificate
Generating a 4096 bit RSA private key
................................++
........................................................................................++
writing new private key to '/etc/ssl/private/deceptionhub.pro.key'
-----
Installing modoboa
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version.
cron is already the newest version.
libjpeg-dev is already the newest version.
librrd-dev is already the newest version.
libxslt1-dev is already the newest version.
python-dev is already the newest version.
rrdtool is already the newest version.
libffi-dev is already the newest version.
libxml2-dev is already the newest version.
The following package was automatically installed and is no longer required:
  libudev1:i386
Use 'apt-get autoremove' to remove it.
0 to upgrade, 0 to newly install, 0 to remove and 78 not to upgrade.
useradd: group modoboa exists - if you want to add this user to that group, use -g.
chmod: cannot access ‘/srv/modoboa’: No such file or directory
Reading package lists...
Building dependency tree...
Reading state information...
libmysqlclient-dev is already the newest version.
mysql-server is already the newest version.
The following package was automatically installed and is no longer required:
  libudev1:i386
Use 'apt-get autoremove' to remove it.
0 to upgrade, 0 to newly install, 0 to remove and 78 not to upgrade.
start: Job is already running: mysql
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'localhost'
Reading package lists...
Building dependency tree...
Reading state information...
python-virtualenv is already the newest version.
The following package was automatically installed and is no longer required:
  libudev1:i386
Use 'apt-get autoremove' to remove it.
0 to upgrade, 0 to newly install, 0 to remove and 78 not to upgrade.
sudo: unknown user: modoboa
sudo: unable to initialise policy plug-in
sudo: unknown user: modoboa
sudo: unable to initialise policy plug-in
sudo: unknown user: modoboa
sudo: unable to initialise policy plug-in
Traceback (most recent call last):
  File "run.py", line 73, in <module>
    main()
  File "run.py", line 63, in main
    scripts.install("modoboa", config)
  File "/home/inferno09/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/inferno09/modoboa-installer/modoboa_installer/scripts/base.py", line 151, in run
    self.post_run()
  File "/home/inferno09/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 156, in post_run
    self._deploy_instance()
  File "/home/inferno09/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 110, in _deploy_instance
    sudo_user=self.user, cwd=self.home_dir)
  File "/home/inferno09/modoboa-installer/modoboa_installer/utils.py", line 61, in exec_cmd
    process = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/srv/modoboa'
inferno09@server:~/modoboa-installer$ ’
I previo Censored username and domain, so this is under the same user as before.

**Comment by tonioo** [comment]
Looks like the creation of the modoboa user fails because there is already a modoboa group... Can you try to remove this group and try again?

**Comment by tei06398** [comment]
It installed "successfully" but upon going to https://deceptionhub.pro, it
asks if I trust certificate and I say yes. It then gives me 502 Bad Gateway

**Comment by tei06398** [comment]
Also, is there a way to make nginx and apache2 work simultaneously, or
switch modoboa over to apache2?

**Comment by tonioo** [comment]
If you did not choose the "Let's Encrypt" option for certificate generation, then the installer has generated a self-signed certificate so this warning is normal.
The "bad gateway" issue is strange, can you check uwsgi logs in /var/log/uwsgi/app/instance.log?
You can run both nginx and apache2 if they don't use the same ports. Why would you need a switch to apache?

**Comment by tei06398** [comment]
I prefer apache over nginx, I'll just set nginx to the https port and
apache to default 80.
Also happens to be that that file is nonexistent.

**Comment by tei06398** [comment]
*poke*

**Comment by tonioo** [comment]
What's your distribution?

**Comment by tei06398** [comment]
Ubuntu 14.04 64 bit

**Comment by tonioo** [comment]
Is there any log file talking about uwsgi in /var/log?

**Comment by tei06398** [comment]
2 files: modoboa_instance.log and modoboa_instance.log.1

**Comment by tonioo** [comment]
And do you see something interesting inside?

**Comment by tei06398** [comment]
Which one should I paste?

**Comment by tonioo** [comment]
Both?

**Comment by tei06398** [comment]
Okay
.log:
Literally nothing

.log.1:
http://deceptionhub.pro/log.txt

**Comment by tei06398** [comment]
Fixed

**Comment by tei06398** [comment]
(Now accessible)

**Comment by tonioo** [comment]
Looks like you have an issue with you MySQL credentials:
`django.db.utils.OperationalError: (1045, "Access denied for user 'modoboa'@'localhost' (using password: YES)")`
Have you changed the password?

**Comment by tei06398** [comment]
Not sure. I think I have, yes. Where are the credentials modoboa uses
during install configured?

**Comment by tonioo** [comment]
In the installer.cfg file, section [modoboa].

**Comment by tei06398** [comment]
Yes I have. Will you be able to reply in an hour? I have to shovel the
driveway.

**Comment by tonioo** [comment]
yes.

**Comment by tei06398** [comment]
I'm back

**Comment by tei06398** [comment]
Do I need a database for each module to be installed, or do they each prefix their tables?

**Comment by tonioo** [comment]
No you don't, tables are prefixed.

**Comment by tei06398** [comment]
Would you mind contacting me by Skype?

**Comment by tonioo** [comment]
Send me a message to my email address with your ID. (tonio@ngyn.org)
(and I also use Jabber/xmpp on this address)

**Comment by victorschinaider** [comment]
I think i'm having the same problem.

I'm having this with the --debug option

```
Command "/srv/modoboa/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-exvgfF/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-oJmPm2-record/install-record.txt --single-version-externally-managed --compile --install-headers /srv/modoboa/env/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-build-exvgfF/lxml/
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/modoboa-admin.py", line 7, in <module>
```

**Comment by tonioo** [comment]
@victorschinaider Your issue is different. If you're running a VPS, make sure you have at least 1GB of RAM.
