### ISSUE TITLE
DKIM on install?

### ISSUE THREAD

**Issue by jprasmussen** [modoboa/modoboa-installer#78]
Is it possible to have the installer generate a DKIM and setup email signing for the primary domain?

**Comment by tonioo** [comment]
I see two difficulties with about your idea:
* The installer can't setup the DNS part
* It does not know the primary domain at installation time (unless you're talking about the hostname?)

**Comment by jprasmussen** [comment]
Valid point... the installer would need to know what domain you intended to use. 

As for the DNS, although not ideal, was thinking that once the DKIM was generated it would provide instructions to go add it to your DNS. Sort of lifting that idea from iRedMail, except their installer just does it and it's up to you to read the docs to know you have to do that.

So for both your points perhaps the installer is not the place for that feature but instead when a domain is setup in the UI.

**Comment by mkkeck** [comment]
Perhabs, a comment in Postfix `main.cf` (or `master.conf`) for DKIM-Milter would be option.
Sample of my `master.cf`
```ini
#--------------------------------------------------------------------------
# (Open-) DKIM Milter
#--------------------------------------------------------------------------

milter_default_action = accept
milter_protocol = 2
smtpd_milters = inet:127.0.0.1:8891
non_smtpd_milters = $smtpd_milters
```

**Comment by senner** [comment]
There are two different areas of configuration needed, outbound signage and inbound verification of signature.

For signing,

1. Installer for the integration of amavisd or open-dkim milter for the signing (we've used a milter for years for dkim) which would just do a lookup against the location of where the domain is configured (the database) and how to sign messages if configured via the UI
2. The ONLY thing published in DNS is the public key.  Modoboa doesn't need to host the DNS and public key.  Modoboa/milter/amavis just signs the outbound messages with the key/private key.
The modoboa UI would only have to give a domain admin the key to publish in DNS whomever and wherever they host DNS.i.e.   in the UI just show the TXT record to create, and a button to generate a new one if needed and an admin publishes this say at there DNS provider:
20170219._domainkey v=DKIM1;p=MIIBIjANBgkqhsfasfaskdfjalsdkfjaskldfjakldsfjaldsfkladsjfklasdfjklasdjfklasdjfklasdjflasdjklfasjdfoiweufweoeiruoiweafuoweifuaosuozduaod

The outbound message tells the receiving side what DNS txt key to validate the signature against.

I think the discussion about DNS hosting in modooba is out of scope as referenced in other issues like #8 in modoboa-amavis.

It's an entirely different thing for modoboa to validate the DKIM signatures on receipt of emails.

**Comment by kryskool** [comment]
Hi guys

Since this [commit](https://github.com/modoboa/modoboa-installer/commit/8a650e699843889c607319161357030886d838de), OpenDKIM is installed and configure

In the Web interface you can configure it see [PR 1352](https://github.com/modoboa/modoboa/pull/1352) and [PR 1421](https://github.com/modoboa/modoboa/pull/1421)

I think we can close this issue

Regards,

**Comment by tonioo** [comment]
Yes.
