### ISSUE TITLE
Connection to amavis database not configured when 'all' shortcut is used for extensions

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa-installer#79]
_From @bashfulrobot on December 1, 2016 0:39_

SYSTEM:
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

Your mail server e.srvrs.co will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
```
I just performed a fresh install (on AWS) with Ubuntu 16.04, and had ran the script. I had modified the installer.cfg to use mysql, letsencrypt, changed the time zone, to load all modules and use different passwords.

At the end of the install I rebooted to be safe, and then tried to log into the web interface with the default credentials. The page moves over to "/dashboard" and displays the following:

Sorry

An internal error occured.

Did I miss something?

_Copied from original issue: tonioo/modoboa#982_

**Comment by tonioo** [comment]
Can you set DEBUG to True inside settings.py, reload uwsgi and try again please?

**Comment by tonioo** [comment]
@bashfulrobot ping

**Comment by cmdtstof** [comment]
same for me "sorry an internal error occured" after given the initial credentials.

installation with default installer.cfg works!
doing change in installer.cfg (letsencrypt, and pwds) installation works, but login throws the "sorry..."

thansk

**Comment by tonioo** [comment]
Are you saying you're running the installer a second time in top of the
first installation?

**Comment by cmdtstof** [comment]
nop, i did not say this :-)
it was a fresh installation on a virgin ub1604 maschine from ovh.
(would be i nice feature to reinstall modoboa then to reinstall the full host everytime. but for a live maschine i would suggest to install it from a virgin maschine)

i guess if i using the modoboa-installer from some days before (when installation was working) will bring no success since the problem has nothing to do with the installer?
can i give you some other helpfull informations? the debug flag during installation isn't showing some trouble and the log file also gives no information.
???
thanks

**Comment by tonioo** [comment]
I just tried a fresh installation on a debian jessie (with mysql a custom password for modoboa user) and it works. I'm going to try on a ubuntu system but I don't understand why it fails...

**Comment by cmdtstof** [comment]
remember, the installation was working (means login was possible) without any change of the config file (ie selfsign cert).
with changing the config file (extensions=all, letsencrypt, and all pwd changed (inkl. postgres) the installation was succesfull but login to modoboa gives the "sorry..."
i havn't a glue in the moment where the problem could be.

**Comment by tonioo** [comment]
Must be something related to extensions (all), I'll check.

**Comment by tonioo** [comment]
@cmdtstof I removed the 'all' shortcut (easy fix) so now it should work as expected. Could you check please?

**Comment by cmdtstof** [comment]
i tried a new installation without "all" (with code before you made a changes).
run.py with --debug
the "Generating DH parameters, 4096 bit long safe prime, generator 2" was running 20min with 100% cpu until i killed the installation procedure (just before getting complains from ovh :-) )
i guess it has nothing to do with modoboa but with openssl?
will try to install it again...

**Comment by tonioo** [comment]
Yes... 4096 is a big key size so it requires a lot of entropy from the system. Maybe your VM does not have enough. Maybe I should lower to size to 2048.

**Comment by cmdtstof** [comment]
yes it will take some time but i guess not 20min? the 4 installation trials on the same host typ today needed about 5mins for installing the whole modoboa.

**Comment by cmdtstof** [comment]
strange strange about openssl. the new installation is working (in about 5min). login is possible.
thanks
