### ISSUE TITLE
Email doesn´t work @ Debian 8.2

### ISSUE THREAD

**Issue by huggenknubbel** [modoboa/modoboa-installer#8]
after a clean install i get this if i try to send an Email

Nov  4 17:18:45 mail postfix/postscreen[7657]: close database /var/lib/postfix/postscreen_cache.db: No such file or directory (possible Berkeley DB bug)
Nov  4 17:18:59 mail postfix/postscreen[7705]: CONNECT from [127.0.0.1]:55041 to [127.0.0.1]:25
Nov  4 17:18:59 mail postfix/postscreen[7705]: WHITELISTED [127.0.0.1]:55041
Nov  4 17:18:59 mail postfix/smtpd[7706]: error: open /etc/postfix/sql-relaydomains.cf: No such file or directory
Nov  4 17:18:59 mail postfix/smtpd[7706]: error: open /etc/postfix/sql-aliases.cf: No such file or directory
Nov  4 17:18:59 mail postfix/smtpd[7706]: error: open /etc/postfix/sql-sender-login-mailboxes.cf: No such file or directory
Nov  4 17:18:59 mail postfix/smtpd[7706]: error: open /etc/postfix/sql-sender-login-aliases.cf: No such file or directory
Nov  4 17:18:59 mail postfix/smtpd[7706]: error: open /etc/postfix/sql-maintain.cf: No such file or directory
Nov  4 17:18:59 mail postfix/smtpd[7706]: error: open /etc/postfix/sql-relay-recipient-verification.cf: No such file or directory
Nov  4 17:18:59 mail postfix/smtpd[7706]: connect from localhost[127.0.0.1]
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: error: open /etc/postfix/sql-domain-aliases.cf: No such file or directory
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: error: open /etc/postfix/sql-domains.cf: No such file or directory
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: error: open /etc/postfix/sql-relaydomains.cf: No such file or directory
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: error: open /etc/postfix/sql-spliteddomains-transport.cf: No such file or directory
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: error: open /etc/postfix/sql-relaydomains-transport.cf: No such file or directory
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: error: open /etc/postfix/sql-autoreplies-transport.cf: No such file or directory
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: warning: pgsql:/etc/postfix/sql-spliteddomains-transport.cf is unavailable. open /etc/postfix/sql-spliteddomains-transport.cf: No such file or directory
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: warning: pgsql:/etc/postfix/sql-spliteddomains-transport.cf lookup error for "*"
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: warning: pgsql:/etc/postfix/sql-spliteddomains-transport.cf is unavailable. open /etc/postfix/sql-spliteddomains-transport.cf: No such file or directory
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: warning: pgsql:/etc/postfix/sql-spliteddomains-transport.cf lookup error for "*"
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: warning: pgsql:/etc/postfix/sql-domain-aliases.cf is unavailable. open /etc/postfix/sql-domain-aliases.cf: No such file or directory
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: warning: pgsql:/etc/postfix/sql-domain-aliases.cf: table lookup problem
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: warning: virtual_alias_domains lookup failure
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: warning: pgsql:/etc/postfix/sql-domain-aliases.cf is unavailable. open /etc/postfix/sql-domain-aliases.cf: No such file or directory
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: warning: pgsql:/etc/postfix/sql-domain-aliases.cf: table lookup problem
Nov  4 17:18:59 mail postfix/trivial-rewrite[7708]: warning: virtual_alias_domains lookup failure
Nov  4 17:18:59 mail postfix/smtpd[7706]: NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 451 4.3.0 <a@b.comr>: Temporary lookup failure; from=<c@d.com> to=<a@b.com> proto=ESMTP helo=<c@d.com>
Nov  4 17:18:59 mail postfix/smtpd[7706]: lost connection after RSET from localhost[127.0.0.1]
Nov  4 17:18:59 mail postfix/smtpd[7706]: disconnect from localhost[127.0.0.1]

**Comment by tonioo** [comment]
Looks like something went wrong during the installation process...

Can you run it once again with the --debug option please ? (and remove the /srv/modoboa/instance directory before)

**Comment by huggenknubbel** [comment]
i try it again. there are some errors while the Postfix installation:

● postfix.service - LSB: Postfix Mail Transport Agent
   Loaded: loaded (/etc/init.d/postfix)
  Drop-In: /run/systemd/generator/postfix.service.d
           └─50-postfix-$mail-transport-agent.conf
   Active: active (running) since Wed 2015-11-04 17:56:29 CET; 22min ago
  Process: 8680 ExecStop=/etc/init.d/postfix stop (code=exited, status=0/SUCCESS)
  Process: 8703 ExecStart=/etc/init.d/postfix start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/postfix.service
           ├─8827 /usr/lib/postfix/master
           ├─8828 pickup -l -t unix -u -c
           ├─8829 qmgr -l -t unix -u
           ├─8899 trivial-rewrite -n rewrite -t unix -u -c
           ├─9914 cleanup -z -t unix -u -c
           └─9915 cleanup -z -t unix -u -c

Nov 04 18:18:34 mail.1337tower.de postfix/cleanup[9914]: warning: pgsql:/etc/postfix/sql-aliases.cf lookup error for "root@mail.13...er.de"
Nov 04 18:18:34 mail.1337tower.de postfix/cleanup[9914]: warning: C50311C13E4: virtual_alias_maps map lookup problem for root@mail... later
Nov 04 18:18:35 mail.1337tower.de postfix/pickup[8828]: C59231C13FC: uid=1001 from=<vmail>
Nov 04 18:18:35 mail.1337tower.de postfix/cleanup[9915]: warning: pgsql:/etc/postfix/sql-aliases.cf is unavailable. open /etc/post...ectory
Nov 04 18:18:35 mail.1337tower.de postfix/cleanup[9915]: warning: pgsql:/etc/postfix/sql-aliases.cf lookup error for "vmail@mail.1...er.de"
Nov 04 18:18:35 mail.1337tower.de postfix/cleanup[9915]: warning: C59231C13FC: virtual_alias_maps map lookup problem for vmail@mai... later
Nov 04 18:18:36 mail.1337tower.de postfix/pickup[8828]: C64641C14F3: uid=0 from=<root>
Nov 04 18:18:36 mail.1337tower.de postfix/cleanup[9914]: warning: pgsql:/etc/postfix/sql-aliases.cf is unavailable. open /etc/post...ectory
Nov 04 18:18:36 mail.1337tower.de postfix/cleanup[9914]: warning: pgsql:/etc/postfix/sql-aliases.cf lookup error for "root@mail.13...er.de"
Nov 04 18:18:36 mail.1337tower.de postfix/cleanup[9914]: warning: C64641C14F3: virtual_alias_maps map lookup problem for root@mail... later

**Comment by tonioo** [comment]
Can you paste the configuration file you use ?

**Comment by huggenknubbel** [comment]
i didn't change any things exept the extensions:

[general]
tls_key_file = /etc/ssl/private/ssl-cert-snakeoil.key
tls_cert_file = /etc/ssl/certs/ssl-cert-snakeoil.pem

[database]
# Select database engine : postgres or mysql
engine = postgres
#engine = mysql
host = 127.0.0.1
install = true

[postgres]
user = postgres
password =

[mysql]
user = root
password = password

[modoboa]
user = modoboa
home_dir = /srv/modoboa
venv_path = %(home_dir)s/env
instance_path = %(home_dir)s/instance
timezone = Europe/Paris
dbname = modoboa
dbuser = modoboa
dbpassword = password
# Extensions to install (you can use the 'all' shortcut)
extensions = 'all'

[amavis]
enabled = true
user = amavis
home_dir = /var/lib/amavis
config_dir = /etc/amavis/conf.d
max_servers = 1

dbname = amavis
dbuser = amavis
dbpassword = password

[clamav]
enabled = true
user = clamav

[dovecot]
enabled = true
config_dir = /etc/dovecot
user = vmail
home_dir = /srv/vmail
mailboxes_owner = vmail

[nginx]
enabled = true
config_dir = /etc/nginx

[razor]
enabled = true
config_dir = /etc/razor

[postfix]
enabled = true
config_dir = /etc/postfix
message_size_limit = 11534336

[spamassassin]
enabled = true
config_dir = /etc/spamassassin

dbname = spamassassin
dbuser = spamassassin
dbpassword = password

[uwsgi]
enabled = true
config_dir = /etc/uwsgi
nb_processes = 2
socket_path = /var/run/uwsgi/app/modoboa_instance/socket

**Comment by tonioo** [comment]
Ok, the problem comes from 'all' value. There is a little bug, I'll fix it soon.

**Comment by huggenknubbel** [comment]
i installed my server new and try it again.
things i did bevore:
installing python
installing git
installing vim

change /etc/hostname to: "mail.1337tower.de"
change /etc hosts to: "mail.1337tower.de"

install with ./run.py mail.1337tower.de --debug

while the postfix installation i get that output:

Setting up postfix (2.11.3-1) ...
Adding group `postfix' (GID 112) ...
Done.
Adding system user `postfix' (UID 106) ...
Adding new user `postfix' (UID 106) with group `postfix' ...
Not creating home directory `/var/spool/postfix'.
Creating /etc/postfix/dynamicmaps.cf
Adding tcp map entry to /etc/postfix/dynamicmaps.cf
Adding sqlite map entry to /etc/postfix/dynamicmaps.cf
Adding group `postdrop' (GID 113) ...
Done.
/etc/aliases does not exist, creating it.

Postfix was not set up.  Start with
  cp /usr/share/postfix/main.cf.debian /etc/postfix/main.cf
.  If you need to make changes, edit
/etc/postfix/main.cf (and others) as needed.  To view Postfix configuration
values, see postconf(1).

After modifying main.cf, be sure to run '/etc/init.d/postfix reload'.

Setting up postfix-mysql (2.11.3-1) ...
Adding mysql map entry to /etc/postfix/dynamicmaps.cf
Processing triggers for systemd (215-17+deb8u2) ...
Processing triggers for libc-bin (2.19-18+deb8u1) ...
● postfix.service - LSB: Postfix Mail Transport Agent
   Loaded: loaded (/etc/init.d/postfix)
  Drop-In: /run/systemd/generator/postfix.service.d
           └─50-postfix-$mail-transport-agent.conf
   Active: inactive (dead)

in mail.log i found some auth. errors like this:

Nov  5 16:39:44 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 6 secs): user=<huggenknubbel@1337tower.de>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, secured, session=<KPNJ78wjVwB/AAAB>

**Comment by tonioo** [comment]
Hi, could you try once again using the fix I just pushed ?

**Comment by huggenknubbel** [comment]
i try it again and got the same errors.

maybe i did anything wrong?

2015-11-06 9:48 GMT+01:00 Antoine Nguyen <notifications@github.com>:

**Comment by tonioo** [comment]
In your config file, please replace 'all' by all.

**Comment by huggenknubbel** [comment]
I didn't change anything in the config file at the last 2 try's. So there are no 'all' or all

----- Ursprüngliche Nachricht -----
Von: "Antoine Nguyen" <notifications@github.com>
Gesendet: ‎11.‎11.‎2015 14:07
An: "modoboa/modoboa-installer" <modoboa-installer@noreply.github.com>
Cc: "huggenknubbel" <hirsch.steffen@googlemail.com>
Betreff: Re: [modoboa-installer] Email doesn´t work @ Debian 8.2 (#8)

In your config file, please replace 'all' by all.

**Comment by tonioo** [comment]
In your config. file, in the [modoboa] section, you've set extensions = 'all', right ?

**Comment by huggenknubbel** [comment]
No, not at the last 2 trials. I clone the git and didn't change anything. 

----- Ursprüngliche Nachricht -----
Von: "Antoine Nguyen" <notifications@github.com>
Gesendet: ‎11.‎11.‎2015 14:55
An: "modoboa/modoboa-installer" <modoboa-installer@noreply.github.com>
Cc: "huggenknubbel" <hirsch.steffen@googlemail.com>
Betreff: Re: [modoboa-installer] Email doesn´t work @ Debian 8.2 (#8)

In your config. file, in the [modoboa] section, you've set extensions = 'all', right ?

**Comment by tonioo** [comment]
Ok, sorry :)

So the map files are still not generated ?

**Comment by huggenknubbel** [comment]
how can  check that?
in /etc/postfix i found just one dynamicmaps.cf

2015-11-11 15:00 GMT+01:00 Antoine Nguyen <notifications@github.com>:

**Comment by tonioo** [comment]
Map files are created using the modoboa-admin command. If you don't see them in the /etc/postfix directory, it means the installation of modoboa (before postfix) has failed for some reason...
Running the command once again using the --debug option should provide more information (make sure to delete the /srv/modoboa/instance directory before). Could you then paste the entire result somewhere please ?

**Comment by tonioo** [comment]
@huggenknubbel ping
