### ISSUE TITLE
Wrong path for razor_config in local.cf for Spamassassin?

### ISSUE THREAD

**Issue by mkkeck** [modoboa/modoboa-installer#82]
### Wrong path for razor_config in local.cf for Spamassassin?

Hello,
I am not shure, but I think in the file `/etc/mail/spamassassin/local.cf` there may be a wrong config param:
```ini
# Razor
use_razor2      1
razor_config    /etc/razor/razor-agent.conf
```
I can not find the file `/etc/razor/razor-agent.conf`, but the `/etc/razor.conf` with follow content:
```ini
#
# Razor2 config file
# 
# Autogenerated by Razor-Agents v2.84 
# Tue Dec 27 17:47:17 2016
# Non-default values taken from /var/spool/amavisd/.razor/razor-agent.conf 
# 
# see razor-agent.conf(5) man page 
#

debuglevel             = 3
identity               = identity
ignorelist             = 0
listfile_catalogue     = servers.catalogue.lst
listfile_discovery     = servers.discovery.lst
listfile_nomination    = servers.nomination.lst
logfile                = razor-agent.log
logic_method           = 4
min_cf                 = ac
razordiscovery         = discovery.razor.cloudmark.com
rediscovery_wait       = 172800
report_headers         = 1
turn_off_discovery     = 0
use_engines            = 4,8
whitelist              = razor-whitelist
```

Have I to fix this for my system? Have I forgotten something to install?

#### OS
CentOs 7.3
width Postfix, Dovecot, Spamass, Amavisd-New, Pyzor.

#### Modobo
Version 1.6.2

**Comment by tonioo** [comment]
@mkkeck Thank you for reporting this. Looks like the razor config directory is not the same on CentOS. It should be fixed now.
