### ISSUE TITLE
Add virtualenv package

### ISSUE THREAD

**Issue by themsay** [modoboa/modoboa-installer#84]
I got this error below while trying out modoboa-installer with --debug option on new Debian 8 cloud server with 512M memory. At first I thought it was low memory but is not. 

Reading package lists...
Building dependency tree...
Reading state information...
python-virtualenv is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
-sh: 1: virtualenv: not found
-sh: 1: /srv/modoboa/env/bin/pip: not found
-sh: 1: /srv/modoboa/env/bin/pip: not found
bash: /srv/modoboa/env/bin/activate: No such file or directory
bash: modoboa-admin.py: command not found
Traceback (most recent call last):
  File "./run.py", line 73, in <module>
    main()
  File "./run.py", line 63, in main
    scripts.install("modoboa", config)
  File "/home/user/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/user/modoboa-installer/modoboa_installer/scripts/base.py", line 151, in run
    self.post_run()
  File "/home/user/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 156, in post_run
    self.apply_settings()
  File "/home/user/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 131, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/home/user/modoboa-installer/modoboa_installer/utils.py", line 79, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'

Solution:
- 'sudo apt-get install virtualenv' before running modoboa installer.
- Or simply add "virtualenv" inside modoboa-installer/modoboa_installer/scripts/modoboa.py at deb packages list.

**Comment by tonioo** [comment]
The installer already install the `python-virtualenv` package which should provide the `virtualenv` command. What's the difference with the `virtualenv` package you added?

**Comment by themsay** [comment]
Well, the difference could be clear when you try it by spinning up new server without `virtualenv` installed. Then try modoboa installer with --debug option. You can try it on e.g Digitalocean or Vultr but in my case I used Vultr server (Debian Jessie 512MB memory).

I'll like to know your experience after the test?

If modoboa support python3 this would have been easier with module venv `python3 -m venv env-name`.

**Comment by tonioo** [comment]
I'm surprised by this behaviour because I've realized a lot of installations on the same distribution but I've never seen this... Anyway, I guess it is safe to add this extra package.

**Comment by lpossamai** [comment]
I have got this same issue, with an AWS Ubuntu linux... Already tried:

`apt-get install virtualenv`

Should I open a new case?

**Comment by gianks** [comment]
Same here...

**Comment by tonioo** [comment]
@gianks AWS too ?
