### ISSUE TITLE
modoboa-installer fails during install

### ISSUE THREAD

**Issue by CyberfoxDK** [modoboa/modoboa-installer#85]
Hi 
Just installed a modoboa a couple of hours ago, and wanted to do another one, but this time ít fails.
Did you update the installer script ?

clean Ubuntu 14.04 running modoboa-installer.
Error output looks like this...

`Welcome to Modoboa installer!
Your mail server mail.svendsen.me will be installed with the following component                                                                                                 s:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing modoboa
Traceback (most recent call last):
  File "./run.py", line 73, in <module>
    main()
  File "./run.py", line 63, in main
    scripts.install("modoboa", config)
  File "/home/hsadmin/modoboa-installer/modoboa_installer/scripts/__init__.py",                                                                                                  line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/hsadmin/modoboa-installer/modoboa_installer/scripts/base.py", line                                                                                                  151, in run
    self.post_run()
  File "/home/hsadmin/modoboa-installer/modoboa_installer/scripts/modoboa.py", l                                                                                                 ine 156, in post_run
    self.apply_settings()
  File "/home/hsadmin/modoboa-installer/modoboa_installer/scripts/modoboa.py", l                                                                                                 ine 131, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/home/hsadmin/modoboa-installer/modoboa_installer/utils.py", line 79, in                                                                                                  mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webma                                                                                                 il'
`

**Comment by CyberfoxDK** [comment]
Additional log when running in debug mode.

`Læser tilstandsoplysninger...
E: Kunne ikke lokalisere pakken virtualenv  (translates to "could not locate the package virtualenv")
-sh: 1: virtualenv: not found
-sh: 1: /srv/modoboa/env/bin/pip: not found
-sh: 1: /srv/modoboa/env/bin/pip: not found
bash: /srv/modoboa/env/bin/activate: Ingen sådan fil eller filkatalog
bash: modoboa-admin.py: kommando ikke fundet
Traceback (most recent call last):
`

**Comment by tonioo** [comment]
Indeed, I made a change this morning... I'll check asap.

**Comment by tonioo** [comment]
Last commit I made: https://github.com/modoboa/modoboa-installer/commit/dfc51d52f9d615905ddff01a5ac44b73505fbc99

**Comment by CyberfoxDK** [comment]
yep, it looks like it fails if not able to locate the package virtualenv

**Comment by tonioo** [comment]
Looks like the virtualenv package is not available on Ubuntu.

**Comment by tonioo** [comment]
@CyberfoxDK is it better now?

**Comment by CyberfoxDK** [comment]
Changed back to the original, but will try the new distib within the next couple of hours.
Will get back to you  -  thanks !

**Comment by CyberfoxDK** [comment]
looks like the change did the job - thank you for the fast respond !

**Comment by CyberfoxDK** [comment]
Hi Antoine

Only thing i noticed now, it that the instllation (nginx part) seems to take forever…

Ongoing for 2+ hours.

 

Fra: Antoine Nguyen [mailto:notifications@github.com] 
Sendt: 5. januar 2017 14:02
Til: modoboa/modoboa-installer
Cc: CyberfoxDK; Mention
Emne: Re: [modoboa/modoboa-installer] modoboa-installer fails during install (#85)

 

@CyberfoxDK <https://github.com/CyberfoxDK>  is it better now?

**Comment by tonioo** [comment]
Strange... is it still running?

**Comment by CyberfoxDK** [comment]
Restarted it at 23:30 last night, and let it run overnight.

When I checked this morning at 06:30 it was finished…    

 

When I ran debug last evening, it seemed as the DH algorithm was the one taking a long time.

Just seems strange, that it all of a sudden should take longer than normal…  so I can’t rule out, that it may be my system lacking resources at the time of installation.

 

 

 

Fra: Antoine Nguyen [mailto:notifications@github.com] 
Sendt: 6. januar 2017 09:29
Til: modoboa/modoboa-installer
Cc: CyberfoxDK; Mention
Emne: Re: [modoboa/modoboa-installer] modoboa-installer fails during install (#85)

 

Strange... is it still running?

**Comment by tonioo** [comment]
Maybe I should lower the key length ?

4096 require a lot of entropy from the system and it might take a while
(infinite loop?) a small VM.

**Comment by CyberfoxDK** [comment]
Some would argue that the keylength should be 4096…   perhaps an option to choose 2048 would be nice.

But as you state during the installation, “it might take a long time”.

 

My system is vmware esxi 4.1 on Fujitsu Primergy TX120

Intel Xeon 3040@1,84GHz

8190 Mb RAM

 

The VM (modoboa) had dedicated resources,.

CPU:                   1500

Ram:                   2048

Disk:                   High (only shared with one other vm)

 

 

 

Fra: Antoine Nguyen [mailto:notifications@github.com] 
Sendt: 6. januar 2017 13:51
Til: modoboa/modoboa-installer
Cc: CyberfoxDK; Mention
Emne: Re: [modoboa/modoboa-installer] modoboa-installer fails during install (#85)

 

Maybe I should lower the key length ?

4096 require a lot of entropy from the system and it might take a while
(infinite loop?) a small VM.

**Comment by tonioo** [comment]
I guess a new setting to indicate the key length is the best answer.
I'll fix it asap.
