### ISSUE TITLE
Let's Encrypt cannot auto-update

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#86]
The issue found in https://github.com/modoboa/modoboa-installer/issues/39#issuecomment-271004120 also means the standard crontab for `letsencrypt` cannot be executed, why our instance fell short today.

The issue is nginx which still uses the HTTP(S) ports, as `certbot` expects to take them over.
Two possibilities come into mind:

1. Using certbot's `--pre-hook` and `--post-hook`s to stop and restart nginx. See their documentation.
2. As per #39, https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/nginx_location.conf is an example of an inline nginx configuration, which would allow `certbot` to run with the `--webroot`

For testing purposes I adapted the crontab entry and could successfully run

    /opt/certbot-auto renew --no-self-upgrade --force-renewal --pre-hook "systemctl stop nginx" --post-hook "systemctl restart nginx && systemctl restart postfix && systemctl restart dovecot"

**Comment by tonioo** [comment]
Looks like hooks are the quickest answer to this issue.
