### ISSUE TITLE
Generation of Diffie-Hellman parameters takes too long

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#87]
Running the installer with generation of Diffie-Hellmann parameters can take an enormous amount of time, as running with the `--debug` option and looking at the process structure reveals `openssl` to be the culprit.

http://security.stackexchange.com/questions/95178/diffie-hellman-parameters-still-calculating-after-24-hours suggests to add the parameter `-dsaparam` to its command line.

**Comment by pavinjosdev** [comment]
@almereyda Thank you for the fix; it works :) Was taking hours otherwise.
