### ISSUE TITLE
gcc dependency missing

### ISSUE THREAD

**Issue by strowi** [modoboa/modoboa-installer#9]
Hi,

running on a fresh Ubuntu 12/14.04, but i guess this also applies to all Debian derivatives...
It seems build-essential (or at least some gcc-compiler) is missing at some point and breaks the installation.

If needed i can supply a debug log...

regards,
strowi

**Comment by tonioo** [comment]
Yes please, it would be useful.

**Comment by tonioo** [comment]
@strowi ping

**Comment by tonioo** [comment]
see #13
