### ISSUE TITLE
Install on FreeBSD - anyone?

### ISSUE THREAD

**Issue by mk-conn** [modoboa/modoboa-installer#91]
Are there plans to make this work on FreeBSD?

**Comment by tonioo** [comment]
Yes, when I'll have some time. Since I'm not a FreeBSD user, I'll certainly take me more time so any help on this would be really appreciated.

**Comment by marcotuna** [comment]
Thumbs up for this!

**Comment by marcotuna** [comment]
Bump

**Comment by marcotuna** [comment]
Any updates?

**Comment by tonioo** [comment]
@marcotuna As I said, I'm not a freebsd user. I would really appreciate some help here...

**Comment by herrbischoff** [comment]
@tonioo: Sure, feel free to ask away where exactly you need assistance. I will gladly answer any question I can and help out in testing.

**Comment by tonioo** [comment]
@herrbischoff Great, thank you. Have you already tried a manual modoboa setup on FreeBSD?

**Comment by marcotuna** [comment]
I've been able to run the modoboa panel on FreeBSD but I struggled with Amavis, Postfix, Dovecot configuration which is a bit different from the one's generated from the scripts for Linux

**Comment by tonioo** [comment]
@marcotuna Can you tell me what are the differences please?

**Comment by marcotuna** [comment]
As soon as I get some time, I will post here some things that I've done. Since I've done this a few months ago I don't quite remember straight away.

**Comment by herrbischoff** [comment]
I recently had some time to spend on the manual FreeBSD installation. However, I got stuck on the Green Unicorn/uWSGI instructions. There are certain terms which are no clear at all.

For example, what does `<modoboa dir>` in the gunicorn command mean:

```
$ cd <modoboa dir>
$ gunicorn -c gunicorn.conf.py <modoboa dir>.wsgi:application
```

Also, into what folder does a uwsgi config file go?

> Where Modoboa’s settings.py resides. This is also where the sitestatic and media directories reside.

Not true. `settings.py` is nested one folder deeper than `sitestatic` and `media`.

There are several more issues with the documentation. This part appears to be written by a person very familiar with Python deployment, whereas users like me might not be.

FWIW, I have started logging the commands needed to install the necessary dependencies on FreeBSD:

```
pkg install python py27-virtualenv py27-pip libxml2 libxslt libjpeg-turbo rrdtool libffi sudo bash curl postgresql96-server
sysrc postgresql_enable="YES"
service postgresql start
mkdir /home/modoboa
pw user add modoboa -d /home/modoboa
chown moboboa:modoboa /home/modoboa
su - modoboa
[...]
``

**Comment by kr1pt0ph0b14** [comment]
Bad bump, but any update on this?

**Comment by savegame** [comment]
yestoday i was install it, in FreeNAS 12 Jail (TrueNAS) ) 
but now has error, when try login 
```
CSRF cookie not set.
```
maybe some wrong configuration ...

**Comment by basbebe** [comment]
+1

**Comment by ozgurkazancci** [comment]
+1

**Comment by NuLL3rr0r** [comment]
+1

**Comment by Mark0x01** [comment]
It has taken a while to revisit this, but I should have a revamped and working modoboa-installer for FreeBSD 13.5 available shortly.

It will be tested with postgresql, and will require port builds for security_clamav, mail_dovecot, mail_dovecot-pigeonhole, www_nginx, databases_opendbx, mail_opendkim, mail_postfix, mail_spamassassin (and all the depend pkg's as well - 192 extra's). 

I'll add the details here where to find it.
Full instructions, including port build, using synth, will be included.
