### ISSUE TITLE
Upgrading to 1.6.3

### ISSUE THREAD

**Issue by CyberfoxDK** [modoboa/modoboa-installer#94]
Hi again - and sorry if this is posted the wrong place.
It might be due to my limited knowledge of linux, but the guide regarding the upgrading procedures, i need some help with.

In case you use a dedicated user and/or a virtualenv, do not forget to use them:

> sudo -i <modoboa_user>      (I used the modoboa installer, what should i choose)
> source <virtuenv_path>/bin/activate     (What virtuenv_path is this, the new download perhaps _?)
Then, run the following commands:

> pip install modoboa==<VERSION>   
> cd <modoboa_instance_dir>    (guessing   /srv/modoboa/instance/instance$    ?)
> python manage.py migrate
> python manage.py collectstatic

Is this it ?

**Comment by tonioo** [comment]
If you used the installer, the user is `modoboa` and virtualenv path is `/srv/modoboa/env`. `instance_dir` is `/srv/modoboa/instance`.

**Comment by CyberfoxDK** [comment]
thanks for clearing that up.
When running "sudo -i modoboa"  it returns "command not found"
sudo -i modoboa
-bash: modoboa: kommando ikke fundet

What is the "source" actually..   is it the new version of modoboa ?
source <virtuenv_path>/bin/activate

(Dont use to much time on me, as im installing the new version at a new server as well...)

**Comment by tonioo** [comment]
Sorry, wrong command syntax. Try this: `sudo -u modoboa -i`.
`source` is a bash builtin. Using it, you can load your virualenv (which mostly consists in modifying environment variables)

**Comment by CyberfoxDK** [comment]
Thanks.

**Comment by Seiikatsu** [comment]
Sorry for pushing this old issue, but i run into the same issue:
`-bash: modoboa: command not found`

In the current version of the docs, the wrong syntax `sudo -i modoboa` is still used.
https://modoboa.readthedocs.io/en/latest/manual_installation/modoboa.html

Would be nice if you could change that.
