### ISSUE TITLE
Problem with fresh install of 1.6.3 when using letsencrypt

### ISSUE THREAD

**Issue by CyberfoxDK** [modoboa/modoboa-installer#95]
When modifying the installer.cfg to use letsencrypt, the installation finishes without problems, but fails to listen to port 80 or 443.

`root@mail:~# netstat -an |grep 443`
`root@mail:~#`

`root@mail:~# netstat -an |grep 80`
`unix  3      [ ]         STREAM     CONNECTED     13080`
`root@mail:~#`

--------------------------------------------------------------

Version 1.6.2 shows the following.

`root@mail:~# netstat -an |grep 443`
`tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN`
`unix  3      [ ]         STREAM     CONNECTED     11443`
`unix  3      [ ]         STREAM     CONNECTED     13443`
`root@mail:~#`

`root@mail:~# netstat -an |grep 80`
`tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN`
`tcp6       0      0 :::80                   :::*                    LISTEN`
`unix  2      [ ACC ]     STREAM     LISTENING     13480    private/anvil`
`unix  2      [ ]         STREAM     CONNECTED     18068`
`unix  2      [ ]         DGRAM                    8807`
`unix  2      [ ]         DGRAM                    18070`
`unix  3      [ ]         STREAM     CONNECTED     10180`
`root@mail:~#`

**Comment by tonioo** [comment]
@CyberfoxDK Can you check nginx log files please?

**Comment by CyberfoxDK** [comment]
Sure...
`root@mail:/var/log/nginx# cat error.log
2017/01/19 21:35:35 [emerg] 32421#0: BIO_new_file("/etc/letsencrypt/live/mail.svendsen.me/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/mail.svendsen.me/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2017/01/19 21:49:11 [emerg] 1613#0: BIO_new_file("/etc/letsencrypt/live/mail.svendsen.me/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/mail.svendsen.me/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
root@mail:/var/log/nginx#
`

**Comment by CyberfoxDK** [comment]
Theres more in the letsencrypt folder, but would rather send those to you, and not post them here.

**Comment by tonioo** [comment]
Looks like generation has failed. could you run the installer once again using `--debug` and retry the letsencrypt part?

**Comment by CyberfoxDK** [comment]
Deffently - think i know why.
The ssl port was not forwarded to the new modoboa server during install, and because of that the ssl certificate could not verify the newly generated file.
Will change this, so the new server has forwarded 443, and use --debug as well.
Think the port change will do the trick though.

**Comment by CyberfoxDK** [comment]
forwarding port 443 so it worked during installation, fixed the issue.
ssl check when using letsencrypt, need to be able to verify that the mail server is reachable on 443, otherwise it will fail during install.
Case closed - Thanks for helping Tonioo
